import type { Feature, FeatureArticle, RankItem } from "./data";

const date = "2026-05-14";
const author = "マチノワ編集部";

type GuideSeed = {
  id: string;
  no: string;
  tag: "観光" | "デート" | "街歩き" | "雨の日" | "家族";
  area: string;
  title: string;
  subtitle: string;
  kicker: string;
  angle: string;
  spots: [string, string, string, string, string];
};

function spot(rankNum: number, city: string, name: string, angle: string, image: string): RankItem {
  const time =
    rankNum === 1 ? "午前" : rankNum === 2 ? "昼前後" : rankNum === 3 ? "午後" : rankNum === 4 ? "夕方" : "夜または締め";
  return {
    rank: `SPOT ${String(rankNum).padStart(2, "0")}`,
    rankNum,
    name,
    cuisine: rankNum % 2 === 0 ? "街歩き・観光" : "名所・散策",
    area: city,
    purpose: `${time}に使いやすい、${angle}の候補`,
    desc:
      `${name}は、${city}で予定を組むときに軸にしやすいスポット。` +
      `写真を撮る、少し歩く、次の目的地へ移るという流れが作りやすく、食事だけに頼らない一日の満足度を上げてくれる。` +
      `初めて訪れる人にも説明しやすく、${angle}の記事の中で自然に紹介しやすい場所だ。`,
    images: [image],
    specs: [
      { k: "おすすめ時間", v: time },
      { k: "滞在目安", v: rankNum === 5 ? "30〜60分" : "45〜120分" },
      { k: "使い方", v: rankNum <= 2 ? "旅の前半の目的地にする" : "食事前後の余白に入れる" },
    ],
  };
}

/**
 * 各ガイド記事のヒーロー画像（Wikimedia Commons、HTTP 200 疎通済み）。
 * 旧来の /guide-assets/*.svg プレースホルダーは廃止。地名・施設名と
 * 一致する実写画像を割り当てる。出典確認日 2026-05-15。
 */
const GUIDE_IMG: Record<string, string> = {
  // 神奈川
  "guide-yokohama-sightseeing-spots":   "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Yamashita_Park_%40_Yokohama_%289054590638%29.jpg/1280px-Yamashita_Park_%40_Yokohama_%289054590638%29.jpg",
  "guide-yokohama-minatomirai-date":    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Yokohama_Landmark_Tower_and_Minato-Mirai_waterfront_seen_from_the_boat.jpg/1280px-Yokohama_Landmark_Tower_and_Minato-Mirai_waterfront_seen_from_the_boat.jpg",
  "guide-yokohama-rainy-day-spots":     "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Yamashita_Park_%40_Yokohama_%289054590638%29.jpg/1280px-Yamashita_Park_%40_Yokohama_%289054590638%29.jpg",
  "guide-kamakura-daytrip-spots":       "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Tsurugaoka_Hachimangu_001.jpg/1280px-Tsurugaoka_Hachimangu_001.jpg",
  "guide-kamakura-rainy-day-spots":     "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Engakuji%2C_Kamakura.jpg/1280px-Engakuji%2C_Kamakura.jpg",
  "guide-hakone-daytrip-spots":         "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Owakudani_%40_Hakone_%2810621413133%29.jpg/1280px-Owakudani_%40_Hakone_%2810621413133%29.jpg",
  "guide-odawara-castle-town":          "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Odawara_Castle_20211201.jpg/1280px-Odawara_Castle_20211201.jpg",
  "guide-kawasaki-family-spots":        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Kawasaki_Industrial_Area_Japan_08_%2894111183%29.jpeg/1280px-Kawasaki_Industrial_Area_Japan_08_%2894111183%29.jpeg",
  "guide-enoshima-date-spots":          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Enoshima_20170210-2.jpg/1280px-Enoshima_20170210-2.jpg",
  // 東京
  "guide-tokyo-first-trip-spots":       "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Asakusa_Nakamise_2021-12_ac.jpg/1280px-Asakusa_Nakamise_2021-12_ac.jpg",
  "guide-tokyo-rainy-day-spots":        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Cherry_tree_in_blossom_%40_Ueno_Park_%2813438972635%29.jpg/1280px-Cherry_tree_in_blossom_%40_Ueno_Park_%2813438972635%29.jpg",
  "guide-tokyo-family-spots":           "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Cherry_tree_in_blossom_%40_Ueno_Park_%2813438972635%29.jpg/1280px-Cherry_tree_in_blossom_%40_Ueno_Park_%2813438972635%29.jpg",
  "guide-asakusa-ueno-walk":            "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Asakusa_Nakamise_2021-12_ac.jpg/1280px-Asakusa_Nakamise_2021-12_ac.jpg",
  "guide-shibuya-harajuku-date":        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Tokyo_Shibuya_Scramble_Crossing_2018-10-09.jpg/1280px-Tokyo_Shibuya_Scramble_Crossing_2018-10-09.jpg",
  // 京都
  "guide-kyoto-rainy-day-spots":        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Kiyomizu-dera%2C_Kyoto%2C_November_2016_-01.jpg/1280px-Kiyomizu-dera%2C_Kyoto%2C_November_2016_-01.jpg",
  "guide-kyoto-arashiyama-halfday":     "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Togetsu-ky%C5%8D_bridge_at_golden_hour%2C_Kyoto%2C_Japan.jpg/1280px-Togetsu-ky%C5%8D_bridge_at_golden_hour%2C_Kyoto%2C_Japan.jpg",
  "guide-kyoto-gion-date":              "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Gion_Hanamik%C3%B4ji-d%C3%B4ri.jpg/1280px-Gion_Hanamik%C3%B4ji-d%C3%B4ri.jpg",
  "guide-kyoto-family-spots":           "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Kiyomizu-dera%2C_Kyoto%2C_November_2016_-01.jpg/1280px-Kiyomizu-dera%2C_Kyoto%2C_November_2016_-01.jpg",
  // 大阪
  "guide-osaka-rainy-day-spots":        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Osaka_Castle%2C_Keep_tower%2C_South_view_20190415_1.jpg/1280px-Osaka_Castle%2C_Keep_tower%2C_South_view_20190415_1.jpg",
  "guide-osaka-namba-date":             "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Dotonbori_Glico_LED_signs_at_night%2C3rd_November_2014.JPG/1280px-Dotonbori_Glico_LED_signs_at_night%2C3rd_November_2014.JPG",
  "guide-osaka-family-spots":           "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Osaka_Castle%2C_Keep_tower%2C_South_view_20190415_1.jpg/1280px-Osaka_Castle%2C_Keep_tower%2C_South_view_20190415_1.jpg",
  "guide-osaka-umeda-date":             "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Umeda_Sky_Building%2C_Osaka%2C_November_2016_-01.jpg/1280px-Umeda_Sky_Building%2C_Osaka%2C_November_2016_-01.jpg",
  // 神戸
  "guide-kobe-rainy-day-spots":         "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Kobe_Meriken_Park01bs3200.jpg/1280px-Kobe_Meriken_Park01bs3200.jpg",
  "guide-kobe-kitano-walk":             "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Weathercock_House_Kobe_Kitano_Ijinkan_%E9%A2%A8%E8%A6%8B%E9%B6%8F%E3%81%AE%E9%A4%A8%EF%BC%88%E6%97%A7%E3%83%88%E3%83%BC%E3%83%9E%E3%82%B9%E4%BD%8F%E5%AE%85%EF%BC%89.jpg/1280px-Weathercock_House_Kobe_Kitano_Ijinkan_%E9%A2%A8%E8%A6%8B%E9%B6%8F%E3%81%AE%E9%A4%A8%EF%BC%88%E6%97%A7%E3%83%88%E3%83%BC%E3%83%9E%E3%82%B9%E4%BD%8F%E5%AE%85%EF%BC%89.jpg",
  // 名古屋
  "guide-nagoya-rainy-day-spots":       "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Nagoya_Castle%28Larger%29.jpg/1280px-Nagoya_Castle%28Larger%29.jpg",
  "guide-nagoya-family-spots":          "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Nagoya_Castle%28Larger%29.jpg/1280px-Nagoya_Castle%28Larger%29.jpg",
  // 奈良
  "guide-nara-rainy-day-spots":         "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/T%C5%8Ddai-ji_Kon-d%C5%8D.jpg/1280px-T%C5%8Ddai-ji_Kon-d%C5%8D.jpg",
  "guide-nara-family-spots":            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/T%C5%8Ddai-ji_Kon-d%C5%8D.jpg/1280px-T%C5%8Ddai-ji_Kon-d%C5%8D.jpg",
  // 広島
  "guide-hiroshima-sightseeing-spots":  "https://upload.wikimedia.org/wikipedia/commons/5/51/A-Bomb_Dome.jpg",
  "guide-hiroshima-rainy-day-spots":    "https://upload.wikimedia.org/wikipedia/commons/5/51/A-Bomb_Dome.jpg",
  "guide-hiroshima-miyajima-daytrip":   "https://upload.wikimedia.org/wikipedia/commons/f/fe/Itsukushima_torii_angle.jpg",
  // 福岡
  "guide-fukuoka-sightseeing-spots":    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Hakata_Station_20180306.jpg/1280px-Hakata_Station_20180306.jpg",
  "guide-fukuoka-date-spots":           "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Hakata_Station_20180306.jpg/1280px-Hakata_Station_20180306.jpg",
  "guide-fukuoka-rainy-day-spots":      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Hakata_Station_20180306.jpg/1280px-Hakata_Station_20180306.jpg",
  // 静岡
  "guide-shizuoka-fuji-view-spots":     "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Mount_Fuji_at_sunset%2C_March_2025.jpg/1280px-Mount_Fuji_at_sunset%2C_March_2025.jpg",
  "guide-shizuoka-family-spots":        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Mount_Fuji_at_sunset%2C_March_2025.jpg/1280px-Mount_Fuji_at_sunset%2C_March_2025.jpg",
  // 北海道
  "guide-sapporo-sightseeing-spots":    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Sapporo_TV_tower_20230709_01.jpg/1280px-Sapporo_TV_tower_20230709_01.jpg",
  "guide-sapporo-winter-spots":         "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Sapporo_TV_tower_20230709_01.jpg/1280px-Sapporo_TV_tower_20230709_01.jpg",
  // 埼玉
  "guide-saitama-omiya-spots":          "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Hikawa_Shrine%2C_Omiya_-_Jan_2%2C_2025.jpg/1280px-Hikawa_Shrine%2C_Omiya_-_Jan_2%2C_2025.jpg",
  "guide-kawagoe-sightseeing-spots":    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Kawagoe_Toki_no_Kane_1.jpg/1280px-Kawagoe_Toki_no_Kane_1.jpg",
  // 滋賀
  "guide-shiga-biwako-spots":           "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Top_view_of_Lake_Biwa.jpg/1280px-Top_view_of_Lake_Biwa.jpg",
  "guide-otsu-date-spots":              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Otsu_Mangetsu-ji_Ukimido_18.jpg/1280px-Otsu_Mangetsu-ji_Ukimido_18.jpg",
  // 和歌山
  "guide-wakayama-sightseeing-spots":   "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Wakayama_Castle_Nishinomaru_Garden04bs3200.jpg/1280px-Wakayama_Castle_Nishinomaru_Garden04bs3200.jpg",
  "guide-koyasan-spots":                "https://upload.wikimedia.org/wikipedia/commons/b/bf/Koyasan%2C_Kongobu-ji_%282005%29_01.jpg",
  // 鹿児島
  "guide-kagoshima-sightseeing-spots":  "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Sakurajima55.jpg/1280px-Sakurajima55.jpg",
  "guide-kagoshima-family-spots":       "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Sakurajima55.jpg/1280px-Sakurajima55.jpg",
  // 群馬
  "guide-gunma-onsen-spots":            "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/2023.04.26_Yubatake_%28Kusatsu_Onsen%29.jpg/1280px-2023.04.26_Yubatake_%28Kusatsu_Onsen%29.jpg",
  "guide-takasaki-maebashi-spots":      "https://upload.wikimedia.org/wikipedia/commons/f/f0/Takasaki-byakui-dai-Kannon.jpg",
  // 兵庫
  "guide-himeji-sightseeing-spots":     "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Himeji_Castle%2C_November_2016_-02.jpg/1280px-Himeji_Castle%2C_November_2016_-02.jpg",
  "guide-nishinomiya-date-spots":       "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Nishinomiya-jinja01s4592.jpg/1280px-Nishinomiya-jinja01s4592.jpg",
};

const FALLBACK_GUIDE_IMG =
  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Yamashita_Park_%40_Yokohama_%289054590638%29.jpg/1280px-Yamashita_Park_%40_Yokohama_%289054590638%29.jpg";

function guideImage(id: string): string {
  return GUIDE_IMG[id] ?? FALLBACK_GUIDE_IMG;
}

const seeds: GuideSeed[] = [
  {
    id: "guide-yokohama-sightseeing-spots",
    no: "G06",
    tag: "観光",
    area: "横浜",
    title: "横浜観光スポット5選。初めての横浜で外さない場所",
    subtitle: "みなとみらい、中華街、山下公園。港町の定番を半日で歩く",
    kicker: "YOKOHAMA GUIDE",
    angle: "横浜観光",
    spots: ["みなとみらい21", "横浜赤レンガ倉庫", "山下公園", "横浜中華街", "港の見える丘公園"],
  },
  {
    id: "guide-yokohama-minatomirai-date",
    no: "G07",
    tag: "デート",
    area: "横浜・みなとみらい",
    title: "みなとみらいデート5選。昼から夜景までつながる場所",
    subtitle: "海沿い、夜景、ショッピング。会話が続く横浜デート",
    kicker: "MINATOMIRAI DATE",
    angle: "みなとみらいデート",
    spots: ["汽車道", "横浜ハンマーヘッド", "臨港パーク", "横浜ランドマークタワー", "大さん橋"],
  },
  {
    id: "guide-kamakura-daytrip-spots",
    no: "G08",
    tag: "観光",
    area: "鎌倉",
    title: "鎌倉日帰り観光5選。寺社と海を一日で楽しむ",
    subtitle: "鶴岡八幡宮、大仏、長谷、由比ヶ浜。歩く距離で選ぶ鎌倉案内",
    kicker: "KAMAKURA DAYTRIP",
    angle: "鎌倉日帰り観光",
    spots: ["鶴岡八幡宮", "小町通り", "鎌倉大仏", "長谷寺", "由比ヶ浜"],
  },
  {
    id: "guide-hakone-daytrip-spots",
    no: "G09",
    tag: "観光",
    area: "箱根",
    title: "箱根日帰り観光5選。温泉だけで終わらない巡り方",
    subtitle: "芦ノ湖、神社、美術館、山の景色。東京から行きやすい非日常",
    kicker: "HAKONE DAYTRIP",
    angle: "箱根日帰り観光",
    spots: ["芦ノ湖", "箱根神社", "大涌谷", "彫刻の森美術館", "箱根湯本"],
  },
  {
    id: "guide-odawara-castle-town",
    no: "G10",
    tag: "街歩き",
    area: "小田原",
    title: "小田原城下町さんぽ5選。駅近で歴史を感じる半日旅",
    subtitle: "城、海、商店街。箱根の手前で立ち寄りたい小田原案内",
    kicker: "ODAWARA WALK",
    angle: "小田原街歩き",
    spots: ["小田原城", "報徳二宮神社", "小田原宿なりわい交流館", "御幸の浜", "ミナカ小田原"],
  },
  {
    id: "guide-kawasaki-family-spots",
    no: "G11",
    tag: "家族",
    area: "川崎",
    title: "川崎で家族と行きたい5選。駅近から自然まで",
    subtitle: "公園、科学館、工場夜景。子ども連れでも予定を組みやすい場所",
    kicker: "KAWASAKI FAMILY",
    angle: "川崎家族おでかけ",
    spots: ["川崎市 藤子・F・不二雄ミュージアム", "生田緑地", "東芝未来科学館", "ラ チッタデッラ", "川崎工場夜景"],
  },
  {
    id: "guide-enoshima-date-spots",
    no: "G12",
    tag: "デート",
    area: "江の島・藤沢",
    title: "江の島デート5選。海沿いを歩いて夕景まで楽しむ",
    subtitle: "展望、参道、海岸。昼から夕方が気持ちいい湘南デート",
    kicker: "ENOSHIMA DATE",
    angle: "江の島デート",
    spots: ["江島神社", "江の島シーキャンドル", "弁財天仲見世通り", "稚児ヶ淵", "片瀬東浜海水浴場"],
  },
  {
    id: "guide-tokyo-first-trip-spots",
    no: "G13",
    tag: "観光",
    area: "東京都心",
    title: "東京観光スポット5選。初めてでも回りやすい王道",
    subtitle: "浅草、上野、丸の内、渋谷、東京タワー。東京らしさをつかむ",
    kicker: "TOKYO GUIDE",
    angle: "東京観光",
    spots: ["浅草寺", "上野公園", "東京駅丸の内駅舎", "渋谷スクランブル交差点", "東京タワー"],
  },
  {
    id: "guide-tokyo-rainy-day-spots",
    no: "G14",
    tag: "雨の日",
    area: "東京都心",
    title: "東京雨の日観光5選。濡れにくく楽しめる屋内スポット",
    subtitle: "美術館、駅ナカ、水族館。天気に左右されにくい東京の過ごし方",
    kicker: "TOKYO RAINY DAY",
    angle: "東京雨の日観光",
    spots: ["東京国立博物館", "国立新美術館", "東京駅一番街", "サンシャイン水族館", "チームラボプラネッツ"],
  },
  {
    id: "guide-asakusa-ueno-walk",
    no: "G15",
    tag: "街歩き",
    area: "浅草・上野",
    title: "浅草・上野さんぽ5選。下町と文化を半日で歩く",
    subtitle: "寺社、公園、博物館、商店街。東京東側の定番街歩き",
    kicker: "ASAKUSA UENO WALK",
    angle: "浅草上野街歩き",
    spots: ["浅草寺", "仲見世通り", "隅田公園", "上野恩賜公園", "アメ横"],
  },
  {
    id: "guide-shibuya-harajuku-date",
    no: "G16",
    tag: "デート",
    area: "渋谷・原宿",
    title: "渋谷・原宿デート5選。買い物と散歩がつながる場所",
    subtitle: "公園、路地、展望。予定を詰めすぎない都心デート",
    kicker: "SHIBUYA DATE",
    angle: "渋谷原宿デート",
    spots: ["渋谷スカイ", "MIYASHITA PARK", "キャットストリート", "表参道", "代々木公園"],
  },
  {
    id: "guide-kyoto-rainy-day-spots",
    no: "G17",
    tag: "雨の日",
    area: "京都市",
    title: "京都雨の日観光5選。屋内と回廊で楽しむ古都",
    subtitle: "市場、博物館、駅ビル、寺院。雨でも予定を崩しにくい京都",
    kicker: "KYOTO RAINY DAY",
    angle: "京都雨の日観光",
    spots: ["京都国立博物館", "錦市場", "京都駅ビル", "三十三間堂", "京都文化博物館"],
  },
  {
    id: "guide-kyoto-arashiyama-halfday",
    no: "G18",
    tag: "観光",
    area: "京都・嵐山",
    title: "嵐山半日観光5選。竹林と川辺をゆっくり歩く",
    subtitle: "渡月橋、竹林、寺院、川沿い。午前か午後を使いたい嵐山案内",
    kicker: "ARASHIYAMA GUIDE",
    angle: "嵐山半日観光",
    spots: ["渡月橋", "竹林の小径", "天龍寺", "嵯峨野トロッコ列車", "保津川沿い"],
  },
  {
    id: "guide-kyoto-gion-date",
    no: "G19",
    tag: "デート",
    area: "京都・祇園",
    title: "祇園デート5選。夕方から夜に歩きたい京都",
    subtitle: "花見小路、白川、八坂。静かに歩く大人の京都デート",
    kicker: "GION DATE",
    angle: "祇園デート",
    spots: ["花見小路", "祇園白川", "八坂神社", "円山公園", "先斗町"],
  },
  {
    id: "guide-osaka-rainy-day-spots",
    no: "G20",
    tag: "雨の日",
    area: "大阪市",
    title: "大阪雨の日観光5選。屋内中心で一日を楽しむ",
    subtitle: "水族館、展望、商業施設、博物館。天気に強い大阪案内",
    kicker: "OSAKA RAINY DAY",
    angle: "大阪雨の日観光",
    spots: ["海遊館", "グランフロント大阪", "大阪市立科学館", "あべのハルカス", "なんばパークス"],
  },
  {
    id: "guide-osaka-namba-date",
    no: "G21",
    tag: "デート",
    area: "大阪・なんば",
    title: "なんばデート5選。笑って歩ける大阪の中心地",
    subtitle: "道頓堀、法善寺、劇場、裏なんば。気取らない夜の街歩き",
    kicker: "NAMBA DATE",
    angle: "なんばデート",
    spots: ["道頓堀", "法善寺横丁", "なんばグランド花月", "裏なんば", "湊町リバープレイス"],
  },
  {
    id: "guide-osaka-family-spots",
    no: "G22",
    tag: "家族",
    area: "大阪市",
    title: "大阪で家族と行きたい5選。子ども連れでも動きやすい場所",
    subtitle: "公園、水族館、博物館。食事以外の時間も楽しい大阪",
    kicker: "OSAKA FAMILY",
    angle: "大阪家族おでかけ",
    spots: ["海遊館", "天王寺動物園", "大阪城公園", "キッズプラザ大阪", "長居公園"],
  },
  {
    id: "guide-kobe-rainy-day-spots",
    no: "G23",
    tag: "雨の日",
    area: "神戸市",
    title: "神戸雨の日観光5選。屋内でも港町らしさを楽しむ",
    subtitle: "水族館、博物館、商業施設。天気が崩れても使いやすい神戸",
    kicker: "KOBE RAINY DAY",
    angle: "神戸雨の日観光",
    spots: ["神戸海洋博物館", "atoa", "神戸ハーバーランドumie", "南京町", "神戸市立博物館"],
  },
  {
    id: "guide-kobe-kitano-walk",
    no: "G24",
    tag: "街歩き",
    area: "神戸・北野",
    title: "北野異人館街さんぽ5選。坂道と洋館をゆっくり歩く",
    subtitle: "異人館、神社、カフェ通り。神戸らしい山側の街歩き",
    kicker: "KITANO WALK",
    angle: "北野街歩き",
    spots: ["風見鶏の館", "北野天満神社", "うろこの家", "北野坂", "トアロード"],
  },
  {
    id: "guide-nagoya-rainy-day-spots",
    no: "G25",
    tag: "雨の日",
    area: "名古屋市",
    title: "名古屋雨の日観光5選。屋内で文化と買い物を楽しむ",
    subtitle: "科学館、地下街、ミュージアム。天候に左右されにくい名古屋",
    kicker: "NAGOYA RAINY DAY",
    angle: "名古屋雨の日観光",
    spots: ["名古屋市科学館", "オアシス21", "ノリタケの森", "リニア・鉄道館", "大須商店街"],
  },
  {
    id: "guide-nagoya-family-spots",
    no: "G26",
    tag: "家族",
    area: "名古屋市",
    title: "名古屋で家族と行きたい5選。学びと遊びを一日で",
    subtitle: "動物園、科学館、港、水族館。親子で予定を組みやすい名古屋",
    kicker: "NAGOYA FAMILY",
    angle: "名古屋家族おでかけ",
    spots: ["東山動植物園", "名古屋港水族館", "名古屋市科学館", "リニア・鉄道館", "久屋大通公園"],
  },
  {
    id: "guide-nara-rainy-day-spots",
    no: "G27",
    tag: "雨の日",
    area: "奈良市",
    title: "奈良雨の日観光5選。屋内と回廊で古都を楽しむ",
    subtitle: "博物館、寺院、町家。雨の日でも奈良らしく歩く",
    kicker: "NARA RAINY DAY",
    angle: "奈良雨の日観光",
    spots: ["奈良国立博物館", "東大寺ミュージアム", "興福寺国宝館", "ならまち", "春日大社国宝殿"],
  },
  {
    id: "guide-nara-family-spots",
    no: "G28",
    tag: "家族",
    area: "奈良市",
    title: "奈良で家族と行きたい5選。歩きやすい古都の親子旅",
    subtitle: "公園、寺院、資料館。子どもと一緒に歴史へ触れる奈良",
    kicker: "NARA FAMILY",
    angle: "奈良家族おでかけ",
    spots: ["奈良公園", "東大寺", "平城宮跡歴史公園", "奈良県立万葉文化館", "ならまち"],
  },
  {
    id: "guide-hiroshima-sightseeing-spots",
    no: "G29",
    tag: "観光",
    area: "広島市",
    title: "広島市観光スポット5選。平和記念公園から水辺まで",
    subtitle: "歴史、水辺、展望。初めての広島市で外しにくい定番",
    kicker: "HIROSHIMA GUIDE",
    angle: "広島市観光",
    spots: ["平和記念公園", "原爆ドーム", "広島城", "おりづるタワー", "縮景園"],
  },
  {
    id: "guide-hiroshima-rainy-day-spots",
    no: "G30",
    tag: "雨の日",
    area: "広島市",
    title: "広島市雨の日観光5選。屋内で学びながら街を巡る",
    subtitle: "資料館、美術館、商業施設。天気を気にせず広島を知る",
    kicker: "HIROSHIMA RAINY DAY",
    angle: "広島市雨の日観光",
    spots: ["広島平和記念資料館", "ひろしま美術館", "広島市現代美術館", "おりづるタワー", "広島駅 ekie"],
  },
  {
    id: "guide-fukuoka-sightseeing-spots",
    no: "G31",
    tag: "観光",
    area: "福岡市",
    title: "福岡市観光スポット5選。半日でも街の魅力が見える場所",
    subtitle: "天神、博多、海辺、神社。コンパクトに動ける福岡案内",
    kicker: "FUKUOKA GUIDE",
    angle: "福岡市観光",
    spots: ["大濠公園", "福岡タワー", "櫛田神社", "キャナルシティ博多", "天神地下街"],
  },
  {
    id: "guide-fukuoka-date-spots",
    no: "G32",
    tag: "デート",
    area: "福岡市",
    title: "福岡市デート5選。公園から夜景まで気軽に回る",
    subtitle: "水辺、展望、買い物。食事前後に使いやすい福岡デート",
    kicker: "FUKUOKA DATE",
    angle: "福岡市デート",
    spots: ["大濠公園", "福岡タワー", "ベイサイドプレイス博多", "天神中央公園", "中洲の夜景"],
  },
  {
    id: "guide-shizuoka-fuji-view-spots",
    no: "G33",
    tag: "観光",
    area: "静岡市・清水",
    title: "静岡市・清水で富士山を感じる5選。景色で選ぶ日帰り旅",
    subtitle: "三保、富士宮、日本平。眺望を軸に組む静岡観光",
    kicker: "SHIZUOKA FUJI VIEW",
    angle: "静岡市富士山観光",
    spots: ["三保松原", "日本平夢テラス", "富士山本宮浅間大社", "田貫湖", "薩埵峠"],
  },
  {
    id: "guide-shizuoka-family-spots",
    no: "G34",
    tag: "家族",
    area: "静岡市・清水",
    title: "静岡市で家族と行きたい5選。自然と学びを楽しむ",
    subtitle: "水族館、動物園、公園。子ども連れで予定を組みやすい静岡",
    kicker: "SHIZUOKA FAMILY",
    angle: "静岡市家族おでかけ",
    spots: ["日本平動物園", "東海大学海洋科学博物館", "三保松原", "駿府城公園", "エスパルスドリームプラザ"],
  },
  {
    id: "guide-sapporo-sightseeing-spots",
    no: "G35",
    tag: "観光",
    area: "札幌市",
    title: "札幌観光スポット5選。街中で北海道らしさを感じる",
    subtitle: "大通、時計台、夜景、市場。初札幌で外さない街歩き",
    kicker: "SAPPORO GUIDE",
    angle: "札幌観光",
    spots: ["大通公園", "札幌市時計台", "さっぽろテレビ塔", "藻岩山", "二条市場"],
  },
  {
    id: "guide-sapporo-winter-spots",
    no: "G36",
    tag: "観光",
    area: "札幌市",
    title: "札幌冬の観光5選。雪の日に楽しみたい街の定番",
    subtitle: "雪景色、夜景、屋内施設。冬の札幌で予定を崩さない",
    kicker: "SAPPORO WINTER",
    angle: "札幌冬観光",
    spots: ["大通公園", "藻岩山", "白い恋人パーク", "札幌駅前通地下歩行空間", "北海道大学"],
  },
  {
    id: "guide-saitama-omiya-spots",
    no: "G37",
    tag: "街歩き",
    area: "大宮",
    title: "大宮さんぽ5選。駅近で神社と公園を歩く",
    subtitle: "氷川神社、盆栽、鉄道。半日で回りやすい大宮案内",
    kicker: "OMIYA WALK",
    angle: "大宮街歩き",
    spots: ["武蔵一宮氷川神社", "大宮公園", "鉄道博物館", "盆栽村", "氷川参道"],
  },
  {
    id: "guide-kawagoe-sightseeing-spots",
    no: "G38",
    tag: "観光",
    area: "川越",
    title: "川越観光スポット5選。小江戸を半日で歩く",
    subtitle: "蔵造り、時の鐘、神社、菓子屋横丁。日帰りで楽しい川越",
    kicker: "KAWAGOE GUIDE",
    angle: "川越観光",
    spots: ["蔵造りの町並み", "時の鐘", "菓子屋横丁", "川越氷川神社", "喜多院"],
  },
  {
    id: "guide-shiga-biwako-spots",
    no: "G39",
    tag: "観光",
    area: "大津市",
    title: "大津市湖畔観光5選。琵琶湖を感じる日帰り旅",
    subtitle: "湖畔、寺院、港、公園。大津で水辺を感じる街歩き",
    kicker: "BIWAKO GUIDE",
    angle: "大津市湖畔観光",
    spots: ["大津港", "なぎさ公園", "三井寺", "石山寺", "びわ湖大津館"],
  },
  {
    id: "guide-otsu-date-spots",
    no: "G40",
    tag: "デート",
    area: "大津",
    title: "大津デート5選。湖畔と夜景をゆっくり楽しむ",
    subtitle: "琵琶湖、港、寺院、展望。京都から足を伸ばす湖畔デート",
    kicker: "OTSU DATE",
    angle: "大津デート",
    spots: ["大津港", "なぎさ公園", "三井寺", "びわ湖大津館", "比叡山ドライブウェイ"],
  },
  {
    id: "guide-wakayama-sightseeing-spots",
    no: "G41",
    tag: "観光",
    area: "和歌山市",
    title: "和歌山市観光スポット5選。城と海辺を一日で巡る",
    subtitle: "城、港、温泉、海岸。関西から行きやすい和歌山案内",
    kicker: "WAKAYAMA GUIDE",
    angle: "和歌山市観光",
    spots: ["和歌山城", "和歌山マリーナシティ", "紀三井寺", "加太", "友ヶ島"],
  },
  {
    id: "guide-koyasan-spots",
    no: "G42",
    tag: "観光",
    area: "高野山",
    title: "高野山観光スポット5選。静かな山上で歴史に触れる",
    subtitle: "奥之院、壇上伽藍、宿坊。日帰りでも記憶に残る高野山",
    kicker: "KOYASAN GUIDE",
    angle: "高野山観光",
    spots: ["奥之院", "壇上伽藍", "金剛峯寺", "大門", "高野山霊宝館"],
  },
  {
    id: "guide-kagoshima-sightseeing-spots",
    no: "G43",
    tag: "観光",
    area: "鹿児島市",
    title: "鹿児島市観光スポット5選。桜島を望む街歩き",
    subtitle: "火山、庭園、港、歴史。鹿児島らしさを一日で感じる",
    kicker: "KAGOSHIMA GUIDE",
    angle: "鹿児島市観光",
    spots: ["桜島", "仙巌園", "城山展望台", "いおワールドかごしま水族館", "天文館"],
  },
  {
    id: "guide-kagoshima-family-spots",
    no: "G44",
    tag: "家族",
    area: "鹿児島市",
    title: "鹿児島市で家族と行きたい5選。火山と海を学ぶ旅",
    subtitle: "水族館、展望、フェリー。親子で動きやすい鹿児島案内",
    kicker: "KAGOSHIMA FAMILY",
    angle: "鹿児島市家族おでかけ",
    spots: ["いおワールドかごしま水族館", "桜島フェリー", "桜島ビジターセンター", "城山公園", "鹿児島市維新ふるさと館"],
  },
  {
    id: "guide-gunma-onsen-spots",
    no: "G45",
    tag: "観光",
    area: "草津温泉街",
    title: "草津温泉街さんぽ5選。湯畑から歩く温泉旅",
    subtitle: "湯畑、足湯、寺社、自然。草津温泉で半日歩く定番",
    kicker: "GUNMA ONSEN",
    angle: "草津温泉街歩き",
    spots: ["草津温泉 湯畑", "西の河原公園", "熱乃湯", "光泉寺", "草津温泉スキー場"],
  },
  {
    id: "guide-takasaki-maebashi-spots",
    no: "G46",
    tag: "街歩き",
    area: "高崎市",
    title: "高崎市さんぽ5選。だるまと城址をゆっくり巡る",
    subtitle: "だるま、歴史、公園、観音。高崎駅から足を伸ばす街歩き",
    kicker: "TAKASAKI MAEBASHI",
    angle: "高崎市街歩き",
    spots: ["少林山達磨寺", "高崎城址公園", "高崎白衣大観音", "高崎市美術館", "慈眼院"],
  },
  {
    id: "guide-himeji-sightseeing-spots",
    no: "G47",
    tag: "観光",
    area: "姫路",
    title: "姫路観光スポット5選。世界遺産の城下町を歩く",
    subtitle: "姫路城、庭園、商店街。神戸から足を伸ばす日帰り旅",
    kicker: "HIMEJI GUIDE",
    angle: "姫路観光",
    spots: ["姫路城", "好古園", "大手前通り", "姫路市立美術館", "書写山圓教寺"],
  },
  {
    id: "guide-nishinomiya-date-spots",
    no: "G48",
    tag: "デート",
    area: "西宮",
    title: "西宮デート5選。海辺と街を穏やかに歩く",
    subtitle: "神社、海浜公園、甲子園。落ち着いた阪神間デート",
    kicker: "NISHINOMIYA DATE",
    angle: "西宮デート",
    spots: ["西宮神社", "夙川公園", "甲子園球場", "御前浜公園", "阪急西宮ガーデンズ"],
  },
  {
    id: "guide-kyoto-family-spots",
    no: "G49",
    tag: "家族",
    area: "京都市",
    title: "京都で家族と行きたい5選。子どもと歩きやすい古都",
    subtitle: "水族館、鉄道、庭園、市場。親子で予定を組みやすい京都",
    kicker: "KYOTO FAMILY",
    angle: "京都家族おでかけ",
    spots: ["京都水族館", "京都鉄道博物館", "梅小路公園", "京都市動物園", "錦市場"],
  },
  {
    id: "guide-osaka-umeda-date",
    no: "G50",
    tag: "デート",
    area: "大阪・梅田",
    title: "梅田デート5選。雨の日も夜景も使える大阪の中心地",
    subtitle: "展望、商業施設、水辺。食事前後に歩ける梅田案内",
    kicker: "UMEDA DATE",
    angle: "梅田デート",
    spots: ["梅田スカイビル", "グランフロント大阪", "HEP FIVE観覧車", "中之島", "大阪駅時空の広場"],
  },
  {
    id: "guide-yokohama-rainy-day-spots",
    no: "G51",
    tag: "雨の日",
    area: "横浜",
    title: "横浜雨の日観光5選。屋内中心で港町を楽しむ",
    subtitle: "博物館、水族館、商業施設。天気が崩れても使いやすい横浜",
    kicker: "YOKOHAMA RAINY DAY",
    angle: "横浜雨の日観光",
    spots: ["カップヌードルミュージアム 横浜", "横浜ワールドポーターズ", "横浜ランドマークタワー", "横浜・八景島シーパラダイス", "横浜美術館"],
  },
  {
    id: "guide-kamakura-rainy-day-spots",
    no: "G52",
    tag: "雨の日",
    area: "鎌倉",
    title: "鎌倉雨の日観光5選。しっとり歩く寺社と屋内スポット",
    subtitle: "寺院、美術館、商店街。雨の鎌倉で予定を崩さない",
    kicker: "KAMAKURA RAINY DAY",
    angle: "鎌倉雨の日観光",
    spots: ["長谷寺", "鶴岡八幡宮", "鎌倉文学館", "小町通り", "鎌倉彫資料館"],
  },
  {
    id: "guide-tokyo-family-spots",
    no: "G53",
    tag: "家族",
    area: "東京都心",
    title: "東京で家族と行きたい5選。学びと遊びを一日で",
    subtitle: "動物園、科学館、水族館。親子で回りやすい東京案内",
    kicker: "TOKYO FAMILY",
    angle: "東京家族おでかけ",
    spots: ["上野動物園", "国立科学博物館", "葛西臨海水族園", "日本科学未来館", "井の頭恩賜公園"],
  },
  {
    id: "guide-fukuoka-rainy-day-spots",
    no: "G54",
    tag: "雨の日",
    area: "福岡市",
    title: "福岡市雨の日観光5選。駅近と屋内で楽しむ街歩き",
    subtitle: "地下街、博物館、商業施設。天気に左右されにくい福岡",
    kicker: "FUKUOKA RAINY DAY",
    angle: "福岡市雨の日観光",
    spots: ["天神地下街", "福岡市博物館", "キャナルシティ博多", "JR博多シティ", "福岡アジア美術館"],
  },
  {
    id: "guide-hiroshima-miyajima-daytrip",
    no: "G55",
    tag: "観光",
    area: "宮島",
    title: "宮島日帰り観光5選。海と参道をゆっくり歩く",
    subtitle: "厳島神社、弥山、表参道。広島旅で足を伸ばしたい島時間",
    kicker: "MIYAJIMA DAYTRIP",
    angle: "宮島日帰り観光",
    spots: ["厳島神社", "表参道商店街", "宮島ロープウエー", "弥山", "紅葉谷公園"],
  },
];

export const CITY_GUIDE_FEATURES: Feature[] = seeds.map((seed) => ({
  id: seed.id,
  no: seed.no,
  tag: seed.tag,
  kicker: seed.kicker,
  title: seed.title,
  sub: seed.subtitle,
  image: guideImage(seed.id),
}));

export const CITY_GUIDE_FEATURE_ARTICLES: Record<string, FeatureArticle> = Object.fromEntries(
  seeds.map((seed, index) => {
    const sideSeeds = [seeds[(index + 1) % seeds.length], seeds[(index + 7) % seeds.length]];
    const article: FeatureArticle = {
      id: seed.id,
      no: seed.no,
      articleType: "guide",
      kicker: seed.kicker,
      title: seed.title,
      titleHTML: seed.title.replace("。", "。<br>"),
      subtitle: seed.subtitle,
      lede:
        `${seed.area}で「何をするか」を決めたい人に向けて、${seed.angle}の候補を5つに絞った。` +
        `店舗紹介へ急いでつなげるのではなく、街の見どころ、歩きやすさ、食事前後の余白を基準に、初めてでも予定に入れやすい場所を選んでいる。`,
      date,
      reading: "約5分",
      author,
      heroImage: guideImage(seed.id),
      ranking: seed.spots.map((name, i) => spot(i + 1, seed.area, name, seed.angle, guideImage(seed.id))),
      sideArticles: sideSeeds.map((s) => ({
        t: s.title,
        h: `/feature/${s.id}`,
        img: guideImage(s.id),
      })),
      quote: `${seed.area}の記事は、店を選ぶ前に「街でどう過ごすか」を決める入口になる。`,
      quoteCite: author,
      closing:
        `${seed.title}は、食事ありきではなく、街そのものを目的地にするための記事として設計した。` +
        `この先は、季節、雨の日、家族、デート、半日観光のように検索意図を分けて増やすと、地域ポータルとしての厚みが出る。`,
    };
    return [seed.id, article];
  })
);
