import type { Feature, FeatureArticle, RankItem } from "./data";

const date = "2026-05-14";
const author = "マチノワ編集部";

// ——— Image URLs (Wikimedia Commons) ———
const I = {
  mm_blue:    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Minato_Mirai_In_Blue.jpg/1280px-Minato_Mirai_In_Blue.jpg",
  mm_sakura:  "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Minato_mirai_21_sakura-0332.jpg/1280px-Minato_mirai_21_sakura-0332.jpg",
  cosmo:      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Cosmo_Clock_21_at_night.jpg/1280px-Cosmo_Clock_21_at_night.jpg",
  kishamichi: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Kishamichi_Promenade_%40_Yokohama_%289052296957%29.jpg/1280px-Kishamichi_Promenade_%40_Yokohama_%289052296957%29.jpg",
  kisha2:     "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Kisha-michi-Yokohama-02.jpg/1280px-Kisha-michi-Yokohama-02.jpg",
  akarenga:   "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Yokohama_Red_Brick_Warehouse_2012.JPG/1280px-Yokohama_Red_Brick_Warehouse_2012.JPG",
  osanbashi:  "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Osanbashi.jpg/1280px-Osanbashi.jpg",
  osanbashi2: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Osanbashi_Pier_from_Sea.jpg/1280px-Osanbashi_Pier_from_Sea.jpg",
  yamashita:  "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/View_of_Minato_Mirai_21_from_Yamashita_Park.jpg/1280px-View_of_Minato_Mirai_21_from_Yamashita_Park.jpg",
  yamashita2: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Parque_Yamashita_2.JPG/1280px-Parque_Yamashita_2.JPG",
  chinatown:  "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Yokohama_Chinatown_signage_2015.jpg/1280px-Yokohama_Chinatown_signage_2015.jpg",
  china_nite: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Yokohama_Chinatowns_East_Gate_At_Night.jpg/1280px-Yokohama_Chinatowns_East_Gate_At_Night.jpg",
  museum:     "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Kanagawa_prefectural_museum_of_cultural_history01s3200.jpg/1280px-Kanagawa_prefectural_museum_of_cultural_history01s3200.jpg",
  museum_n:   "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Kanagawa_Prefectural_Museum_of_Cultural_History_at_night.JPG/1280px-Kanagawa_Prefectural_Museum_of_Cultural_History_at_night.JPG",
  motomachi:  "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/MotomachiYokohama.JPG/1280px-MotomachiYokohama.JPG",
  hachimangu: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/TsurugaokaHachiman-M8867.jpg/1280px-TsurugaokaHachiman-M8867.jpg",
  daibutsu:   "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/230128_Kamakura_Daibutsu_Japan01s3.jpg/1280px-230128_Kamakura_Daibutsu_Japan01s3.jpg",
  hasedera:   "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/230128_Hasedera_Kamakura_Kanagawa_pref_Japan04s3.jpg/1280px-230128_Hasedera_Kamakura_Kanagawa_pref_Japan04s3.jpg",
  yuigahama:  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Yuigahama_2025_June_30_various_2.jpg/1280px-Yuigahama_2025_June_30_various_2.jpg",
  kenchoji:   "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Kenchoji_Main_Complex.jpg/1280px-Kenchoji_Main_Complex.jpg",
  enoshima:   "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Shonan_View_from_the_Enoshima_Sea_Candle_2024_Dec_24_various_18_16_54_096000.jpeg/1280px-Shonan_View_from_the_Enoshima_Sea_Candle_2024_Dec_24_various_18_16_54_096000.jpeg",
  enobch:     "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Enoshima_eastside_beach_02.jpg/1280px-Enoshima_eastside_beach_02.jpg",
  yumoto:     "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/161222_Hakone-Yumoto_Station_Hakone_Japan02s3.jpg/1280px-161222_Hakone-Yumoto_Station_Hakone_Japan02s3.jpg",
  odawara:    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Odawara-jo.jpg/1280px-Odawara-jo.jpg",
  odawara2:   "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Odawara_Castle_02.jpg/1280px-Odawara_Castle_02.jpg",
  dobuita:    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Dobuita_street.jpg/1280px-Dobuita_street.jpg",
  miura:      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Miura_Beach_01.jpg/1280px-Miura_Beach_01.jpg",
  miura2:     "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Miura_Kaigan_02.jpg/1280px-Miura_Kaigan_02.jpg",
  chigasaki:  "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Southern_Beach_Chigasaki.jpg/1280px-Southern_Beach_Chigasaki.jpg",
  lazona:     "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/LAZONAkawasaki_001.jpg/1280px-LAZONAkawasaki_001.jpg",
  yoko_sta:   "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Yokohama-STA_East-2023.jpg/1280px-Yokohama-STA_East-2023.jpg",
  noge:       "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Seiyosha_stockroom_NOGE_storefront_Yokohama.jpg/1280px-Seiyosha_stockroom_NOGE_storefront_Yokohama.jpg",
  shin_yoko:  "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Shin-Yokohama_seen_from_Shinkansen.jpg/1280px-Shin-Yokohama_seen_from_Shinkansen.jpg",
  tamapla:    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Tama-Plaza_Station_02.jpg/1280px-Tama-Plaza_Station_02.jpg",
  kohoku:     "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Around_Center_Kita_sta.jpg/1280px-Around_Center_Kita_sta.jpg",
};

function s(
  n: number, name: string, type: string, area: string,
  purpose: string, desc: string, imgs: string[],
  specs: { k: string; v: string }[], transit?: string,
): RankItem {
  return {
    rank: `SPOT ${String(n).padStart(2, "0")}`,
    rankNum: n,
    name, cuisine: type, area, purpose, desc,
    images: imgs, specs, transit,
  };
}

function side(t: string, id: string, img: string) {
  return { t, h: `/feature/${id}`, img };
}

// ═══════════════════════════════════════════════════════
// ARTICLE DEFINITIONS (30本)
// ═══════════════════════════════════════════════════════

export const NEW_GUIDE_FEATURES: Feature[] = [
  // 1
  {
    id: "new-minatomirai-date",
    no: "NG-01", tag: "デート", kicker: "MINATOMIRAI DATE",
    title: "みなとみらいデート5選。昼から夜景までつながる場所",
    sub: "汽車道、コスモクロック、スカイガーデン。横浜の港を一日かけて歩く",
    image: I.mm_blue,
  },
  // 2
  {
    id: "new-minatomirai-rainy-date",
    no: "NG-02", tag: "雨の日", kicker: "MINATOMIRAI RAINY DATE",
    title: "みなとみらい雨の日デート5選。濡れずに一日楽しめる場所",
    sub: "カップヌードルミュージアム、横浜美術館、AIR CABIN。天気に強い港町のデート",
    image: I.cosmo,
  },
  // 3
  {
    id: "new-sakuragicho-night-date",
    no: "NG-03", tag: "デート", kicker: "SAKURAGICHO NIGHT DATE",
    title: "桜木町夜デート5選。夜景と光が似合う場所",
    sub: "汽車道の夜、コスモクロック21、AIR CABIN。桜木町から歩いて回る夜の港",
    image: I.cosmo,
  },
  // 4
  {
    id: "new-akarenga-date",
    no: "NG-04", tag: "デート", kicker: "AKARENGA DATE",
    title: "赤レンガ倉庫周辺デート3選。港の空気を感じる場所",
    sub: "赤レンガ倉庫、象の鼻パーク、ハンマーヘッド。海沿いを歩くだけで成立するデート",
    image: I.akarenga,
  },
  // 5
  {
    id: "new-osanbashi-nightview-date",
    no: "NG-05", tag: "デート", kicker: "OSANBASHI NIGHT VIEW",
    title: "大さん橋周辺で夜景を見るデート3選",
    sub: "大さん橋屋上デッキ、山下公園、港の見える丘公園。横浜夜景の三定番",
    image: I.osanbashi,
  },
  // 6
  {
    id: "new-bashamichi-architecture",
    no: "NG-06", tag: "街歩き", kicker: "BASHAMICHI ARCHITECTURE",
    title: "馬車道レトロ建築さんぽ5選。明治・大正の洋館を歩く",
    sub: "旧横浜正金銀行、旧生糸検査所、県庁本庁舎。関内で重なる時代の層",
    image: I.museum,
  },
  // 7
  {
    id: "new-kannai-nihondori",
    no: "NG-07", tag: "街歩き", kicker: "KANNAI NIHONDORI WALK",
    title: "関内・日本大通りさんぽ5選。横浜発祥の街を歩く",
    sub: "日本大通り、開港資料館、スタジアム界隈。横浜らしさが残る中心地の歩き方",
    image: I.museum_n,
  },
  // 8
  {
    id: "new-yamashita-date",
    no: "NG-08", tag: "デート", kicker: "YAMASHITA DATE",
    title: "山下公園周辺デート5選。港と丘をつなぐ横浜の定番",
    sub: "山下公園、氷川丸、港の見える丘公園、山手洋館。海から丘へ歩くコース",
    image: I.yamashita,
  },
  // 9
  {
    id: "new-chinatown-sightseeing",
    no: "NG-09", tag: "観光", kicker: "CHINATOWN SIGHTSEEING",
    title: "横浜中華街周辺で遊ぶ5選。食べる以外の楽しみ方",
    sub: "関帝廟、媽祖廟、山下公園、元町。中華街を起点に広げる横浜散策",
    image: I.chinatown,
  },
  // 10
  {
    id: "new-motomachi-yamate",
    no: "NG-10", tag: "街歩き", kicker: "MOTOMACHI YAMATE WALK",
    title: "元町・山手さんぽ5選。坂と洋館を歩く横浜",
    sub: "元町ストリート、外国人墓地、ブラフ18番館、山手イタリア山庭園。港が見える丘の街",
    image: I.motomachi,
  },
  // 11
  {
    id: "new-yokohama-station-rainy",
    no: "NG-11", tag: "雨の日", kicker: "YOKOHAMA STATION RAINY DATE",
    title: "横浜駅周辺雨の日デート5選。屋内でも飽きない場所",
    sub: "そごう、ジョイナス、ベイクォーター、アンパンマン。雨でも一日動ける横浜駅",
    image: I.yoko_sta,
  },
  // 12
  {
    id: "new-yokohama-station-bored",
    no: "NG-12", tag: "街歩き", kicker: "YOKOHAMA STATION BORED",
    title: "横浜駅周辺で暇つぶし5選。時間ができたときの定番",
    sub: "東口ベイクォーター、鶴屋町、天理スタミナラーメン、西口地下街。駅から徒歩圏内の過ごし方",
    image: I.yoko_sta,
  },
  // 13
  {
    id: "new-noge-bar-hop",
    no: "NG-13", tag: "街歩き", kicker: "NOGE PRE-DRINK WALK",
    title: "野毛ではしご酒前に歩きたい場所3選",
    sub: "野毛山動物園、野毛山公園、野毛本通り。飲む前の30分で行ける場所",
    image: I.noge,
  },
  // 14
  {
    id: "new-shin-yokohama-bored",
    no: "NG-14", tag: "街歩き", kicker: "SHIN-YOKOHAMA TIME FILLER",
    title: "新横浜で時間調整するなら5選",
    sub: "ラーメン博物館、日産スタジアム、新横浜公園、鶴見川。新幹線の前後に使いやすい場所",
    image: I.shin_yoko,
  },
  // 15
  {
    id: "new-yokohama-arena-spots",
    no: "NG-15", tag: "街歩き", kicker: "YOKOHAMA ARENA SPOTS",
    title: "横浜アリーナ前後に寄りたい場所5選",
    sub: "ラーメン博物館、新横浜プリンスペペ、新横浜公園、鶴見川沿い。ライブ前後の時間の使い方",
    image: I.shin_yoko,
  },
  // 16
  {
    id: "new-kamakura-komachi",
    no: "NG-16", tag: "街歩き", kicker: "KAMAKURA KOMACHI WALK",
    title: "鎌倉小町通り周辺さんぽ5選。食べながら歩く鎌倉の入口",
    sub: "小町通り、鶴岡八幡宮、段葛、若宮大路。鎌倉駅から歩いて回れる定番コース",
    image: I.hachimangu,
  },
  // 17
  {
    id: "new-hase-yuigahama-date",
    no: "NG-17", tag: "デート", kicker: "HASE YUIGAHAMA DATE",
    title: "長谷・由比ヶ浜デート5選。大仏と海を一日で歩く",
    sub: "長谷寺、鎌倉大仏、由比ヶ浜、御霊神社。江ノ電で移動するゆっくりした鎌倉デート",
    image: I.hasedera,
  },
  // 18
  {
    id: "new-enoshima-evening-date",
    no: "NG-18", tag: "デート", kicker: "ENOSHIMA EVENING DATE",
    title: "江の島夕方デート5選。日没前後が一番きれいな場所",
    sub: "シーキャンドル、稚児ヶ淵、片瀬東浜、龍恋の鐘。夕景を軸に回る江の島コース",
    image: I.enoshima,
  },
  // 19
  {
    id: "new-kamakura-rainy",
    no: "NG-19", tag: "雨の日", kicker: "KAMAKURA RAINY DAY",
    title: "鎌倉雨の日観光5選。雨でも楽しめる寺社と屋根のある場所",
    sub: "長谷寺、建長寺、鎌倉文学館、小町通り。雨の鎌倉で予定を崩さない",
    image: I.kenchoji,
  },
  // 20
  {
    id: "new-kawasaki-rainy-date",
    no: "NG-20", tag: "雨の日", kicker: "KAWASAKI RAINY DATE",
    title: "川崎駅周辺雨の日デート5選。駅直結で濡れずに過ごせる場所",
    sub: "ラゾーナ川崎、ミューザ川崎、モアーズ、アトレ、チッタデッラ。雨に強い川崎駅圏内",
    image: I.lazona,
  },
  // 21
  {
    id: "new-musashikosugi-family",
    no: "NG-21", tag: "家族", kicker: "MUSASHI-KOSUGI FAMILY",
    title: "武蔵小杉で子連れおでかけ5選。駅近で子どもが喜ぶ場所",
    sub: "等々力緑地、中原平和公園、武蔵小杉周辺公園、コスギサード。川崎市のちょうどいい規模感",
    image: I.lazona,
  },
  // 22
  {
    id: "new-tamaplaza-azamino",
    no: "NG-22", tag: "街歩き", kicker: "TAMAPLAZA AZAMINO WALK",
    title: "たまプラーザ・あざみ野さんぽ5選。緑と商業施設が混ざる郊外の歩き方",
    sub: "たまプラーザテラス、こどもの国、恩田川、あざみ野ガーデンズ。週末に使いやすい街",
    image: I.tamapla,
  },
  // 23
  {
    id: "new-hakoneyumoto",
    no: "NG-23", tag: "観光", kicker: "HAKONE YUMOTO WALK",
    title: "箱根湯本駅周辺さんぽ5選。温泉街を歩いて感じる箱根の入口",
    sub: "湯本温泉街、早川沿い、阿弥陀寺、旧街道石畳、足湯スポット。箱根の玄関口を味わう",
    image: I.yumoto,
  },
  // 24
  {
    id: "new-odawara",
    no: "NG-24", tag: "観光", kicker: "ODAWARA HALF-DAY",
    title: "小田原駅周辺半日観光5選。城下町を歩いて感じる小田原",
    sub: "小田原城、報徳二宮神社、ミナカ小田原、なりわい交流館、小田原漁港。箱根の手前で寄れる街",
    image: I.odawara,
  },
  // 25
  {
    id: "new-chigasaki-beach",
    no: "NG-25", tag: "街歩き", kicker: "CHIGASAKI BEACH WALK",
    title: "茅ヶ崎海沿いさんぽ5選。サザンと烏帽子岩の街を歩く",
    sub: "サザンビーチ、烏帽子岩、ヘッドランド、茅ヶ崎公園、柳島海岸。湘南のゆるい空気感",
    image: I.chigasaki,
  },
  // 26
  {
    id: "new-fujisawa-bored",
    no: "NG-26", tag: "街歩き", kicker: "FUJISAWA TIME FILLER",
    title: "藤沢駅周辺で時間調整5選。江の島の前後に使いやすい場所",
    sub: "遊行寺、藤沢本町商店街、ふじさわ宿交流館、境川。江の島に向かう前の藤沢の過ごし方",
    image: I.enobch,
  },
  // 27
  {
    id: "new-yokosuka-dobuita",
    no: "NG-27", tag: "街歩き", kicker: "YOKOSUKA DOBUITA WALK",
    title: "横須賀どぶ板通り周辺さんぽ5選。米軍と港町が混ざる街",
    sub: "どぶ板通り、ヴェルニー公園、軍港めぐり、横須賀美術館、猿島。横須賀らしさを歩く",
    image: I.dobuita,
  },
  // 28
  {
    id: "new-miura-kaigan",
    no: "NG-28", tag: "観光", kicker: "MIURA KAIGAN DAY TRIP",
    title: "三浦海岸日帰りさんぽ5選。京急で行く半島の先端",
    sub: "三浦海岸、城ヶ島、三崎港、毘沙門天、剣崎灯台。マグロと海と断崖のある三浦半島",
    image: I.miura,
  },
  // 29
  {
    id: "new-kohoku-nt-family",
    no: "NG-29", tag: "家族", kicker: "KOHOKU NT FAMILY",
    title: "港北ニュータウン子連れおでかけ5選。整備された街で半日遊ぶ",
    sub: "センター北・南、横浜市歴史博物館、大塚・歳勝土遺跡公園、花木園。港北区の子連れ定番",
    image: I.kohoku,
  },
  // 30
  {
    id: "new-yokohama-first-date",
    no: "NG-30", tag: "デート", kicker: "YOKOHAMA FIRST DATE",
    title: "横浜で初デートに使いやすい街5選",
    sub: "みなとみらい、元町・中華街、桜木町、関内、横浜駅西口。初めてのデートで外さない横浜の選び方",
    image: I.mm_blue,
  }];

// ═══════════════════════════════════════════════════════
// ARTICLE DETAIL (FeatureArticle)
// ═══════════════════════════════════════════════════════

export const NEW_GUIDE_FEATURE_ARTICLES: Record<string, FeatureArticle> = {

  // ─── 1. みなとみらいデート5選 ───
  "new-minatomirai-date": {
    id: "new-minatomirai-date",
    no: "NG-01", articleType: "guide",
    kicker: "MINATOMIRAI DATE",
    title: "みなとみらいデート5選。昼から夜景までつながる場所",
    titleHTML: "みなとみらい<br>デート5選。",
    subtitle: "汽車道、コスモクロック、スカイガーデン。横浜の港を一日かけて歩く",
    lede: "みなとみらい21は1989年の横浜博覧会を契機に開発が始まった、横浜のランドマーク集積エリア。桜木町駅とみなとみらい駅を結ぶ約1.5kmの間に、ランドマークタワー・コスモワールド・パシフィコ横浜・赤レンガ倉庫・カップヌードルミュージアムが並び、徒歩で全部繋がる「歩く観光地」として完成度が高い。デートとしては、昼から始めて夕方の夜景まで6〜8時間で組める動線が王道。ここでは初訪問の2人でも迷わないみなとみらいデート5スポットを紹介する。",
    date, reading: "約7分", author,
    heroImage: I.mm_blue,
    ranking: [
      s(1, "汽車道", "プロムナード", "みなとみらい",
        "昼に歩く。海風と鉄橋が写真になる",
        "桜木町駅から徒歩5分、旧臨港鉄道の線路跡を整備した550mの遊歩道。3本の鉄橋が残りレンガ敷きが続く。海面との距離が近く、対岸のランドマークタワーを背景にした構図がそのままデート写真になる。平日昼は比較的空いており、ゆっくり歩ける。",
        [I.kishamichi, I.kisha2],
        [
          { k: "最寄り駅", v: "桜木町駅 徒歩5分" },
          { k: "所要時間", v: "片道20〜30分" },
          { k: "雨の日", v: "✕ 屋外のため不向き" },
          { k: "おすすめ時間", v: "午前〜昼" }]),
      s(2, "コスモクロック21 / コスモワールド", "観覧車・遊園地", "みなとみらい",
        "夕方から夜。動きながら眺める横浜の夜景",
        "日本最大級の時計型大観覧車。一周約15分、ゴンドラから横浜港・ランドマークタワー・ベイブリッジが一望できる。夜は全体がライトアップされ、乗っているときも、外から見ているときもどちらも絵になる。周囲の遊園地エリアと合わせて1〜2時間過ごせる。",
        [I.cosmo, I.mm_blue],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩3分" },
          { k: "料金目安", v: "観覧車 900円（変動あり）" },
          { k: "雨の日", v: "△ 観覧車は可、遊園地は一部制限あり" },
          { k: "おすすめ時間", v: "夕方〜夜" }]),
      s(3, "臨港パーク", "公園・水辺", "みなとみらい",
        "開放感が欲しいときに。芝生と海風で休む",
        "パシフィコ横浜に隣接する海沿いの公園。整備された芝生広場が広く、持ち込んだ食べ物で休憩するのに使いやすい。海に向かって開けており、正面に横浜ベイブリッジ、右手にランドマークタワーが見える。人が多すぎず、座って話す時間が作りやすい。",
        [I.mm_blue, I.mm_sakura],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩8分" },
          { k: "所要時間", v: "30分〜1時間" },
          { k: "雨の日", v: "✕ 屋外芝生エリア" },
          { k: "おすすめ時間", v: "昼〜夕方" }]),
      s(4, "横浜ランドマークタワー スカイガーデン", "展望台", "みなとみらい",
        "高さ273mから見下ろす横浜全景",
        "69階の展望フロアから360度の眺望が得られる。晴れた日は富士山も見え、東京湾から横浜市街までが一望できる。エレベーターが分速750mで45秒で到着するのも体験として面白い。夜景目的なら日没後30分が最も美しい時間帯。",
        [I.mm_blue],
        [
          { k: "最寄り駅", v: "みなとみらい駅 直結" },
          { k: "料金", v: "大人 1,000円" },
          { k: "雨の日", v: "◎ 屋内・展望フロア" },
          { k: "おすすめ時間", v: "夕暮れ〜夜" }]),
      s(5, "大さん橋国際客船ターミナル", "展望デッキ", "中区・山下",
        "夜景の定番。屋上デッキで横浜港を見渡す",
        "木のデッキが波打つように続く屋上広場は、開放的で座る場所が多い。横浜ベイブリッジ、みなとみらいのビル群、氷川丸が同時に見える。入場無料のため立ち寄りやすく、散歩の締めとして使いやすい。夜は風が強い日もあるので上着を持参すると良い。",
        [I.osanbashi, I.osanbashi2],
        [
          { k: "最寄り駅", v: "日本大通り駅 徒歩7分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "△ 一部屋内あり、デッキは雨天不可" },
          { k: "おすすめ時間", v: "夕方〜夜" }])],
    sideArticles: [
      side("みなとみらい雨の日デート5選", "new-minatomirai-rainy-date", I.cosmo),
      side("大さん橋夜景デート3選", "new-osanbashi-nightview-date", I.osanbashi)],
    quote: "みなとみらいは順番を決めてから来ると、倍楽しくなる。",
    quoteCite: author,
    closing: "標準動線は、桜木町駅→汽車道（13:00〜14:00 散歩）→コスモワールド（14:00〜15:30 観覧車）→赤レンガ倉庫（16:00〜17:30 ショッピング＋カフェ）→大さん橋（17:30〜18:30 夕景）→山下公園・港の見える丘公園（19:00〜20:30 夜景）→中華街でディナー。所要約7時間、予算は1人6,000〜12,000円が目安。「横浜の代表的な観光ルートを1日で網羅したい人」「夜景デートを港町で組みたい人」「観覧車・大さん橋・赤レンガという王道を外したくない人」に向く。土日夕方17〜20時はコスモワールド・赤レンガ・大さん橋すべてピーク混雑、平日デートまたは早めの動き出しが現実的。雨の日はコスモワールド屋外を諦めて、赤レンガ倉庫＋クイーンズスクエア＋カップヌードルミュージアムの屋内中心に切り替える。時間がない場合は、汽車道→赤レンガ倉庫→大さん橋の3点で4時間に圧縮できる。迷ったら、日没30分前にどこか1ヶ所で夕景を見る、と決めて動き始めると満足度が最大化する。",
  },

  // ─── 2. みなとみらい雨の日デート5選 ───
  "new-minatomirai-rainy-date": {
    id: "new-minatomirai-rainy-date",
    no: "NG-02", articleType: "guide",
    kicker: "MINATOMIRAI RAINY DATE",
    title: "みなとみらい雨の日デート5選。濡れずに一日楽しめる場所",
    titleHTML: "みなとみらい<br>雨の日デート5選。",
    subtitle: "カップヌードルミュージアム、横浜美術館、AIR CABIN。天気に強い港町のデート",
    lede: "みなとみらいは雨の日に強い屋内施設の密度が高いエリア。横浜美術館・カップヌードルミュージアム・三菱みなとみらい技術館・ランドマークタワー展望・AIR CABIN（屋内型ロープウェイ）が、徒歩圏内に揃っている。屋外の汽車道や赤レンガ広場が使えなくても、屋内だけで一日が成立する珍しい湾岸エリア。ここでは雨の日に2人で過ごす、みなとみらいの屋内中心5スポットを紹介する。雨天時の傘の煩わしさを最小化する動線設計を意識して並べた。",
    date, reading: "約7分", author,
    heroImage: I.cosmo,
    ranking: [
      s(1, "カップヌードルミュージアム 横浜", "体験型ミュージアム", "みなとみらい",
        "自分だけのカップヌードルを作る体験が軸",
        "日清食品創業者・安藤百福の生涯と即席麺の発明を展示する体験型施設。「マイカップヌードルファクトリー」ではオリジナルカップと具材を選んで作ることができ、所要時間は2〜3時間。事前予約不要で当日参加できる枠もある。みなとみらい駅から徒歩8分。",
        [I.mm_blue],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩8分" },
          { k: "料金", v: "大人 500円（マイカップ体験別途）" },
          { k: "雨の日", v: "◎ 全屋内" },
          { k: "所要時間", v: "2〜3時間" }]),
      s(2, "横浜美術館", "美術館", "みなとみらい",
        "2024年リニューアル。近現代美術のコレクションを見る",
        "2024年3月にリニューアルオープン。パブリックスペースが拡充され、カフェも使いやすくなった。コレクション展は近現代アートが中心で、企画展は季節ごとに変わる。みなとみらい駅から徒歩3分、ランドマークタワーと同じ敷地のグランモール内にある。",
        [I.mm_blue],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩3分" },
          { k: "料金", v: "展示により異なる（コレクション展 500円〜）" },
          { k: "雨の日", v: "◎ 全屋内" },
          { k: "所要時間", v: "1〜2時間" }]),
      s(3, "マークイズみなとみらい", "ショッピングモール", "みなとみらい",
        "地下でランドマークタワーと繋がる大型モール",
        "5階建ての大型商業施設で、ファッション・雑貨・飲食が揃う。ランドマークタワーとは地下で直結しており、傘を使わずに移動できる。フードコートが充実しているため昼食・休憩に使いやすい。みなとみらい駅から直結。",
        [I.mm_blue],
        [
          { k: "最寄り駅", v: "みなとみらい駅 直結" },
          { k: "料金", v: "無料（ショッピング・飲食別途）" },
          { k: "雨の日", v: "◎ 全屋内・駅直結" },
          { k: "所要時間", v: "1〜3時間" }]),
      s(4, "横浜ランドマークタワー スカイガーデン", "展望台", "みなとみらい",
        "雨でも楽しめる。窓ガラスに霧が映える日もある",
        "地上273mの展望フロア。晴れとは違う景観だが、雨天や曇天の日は雲の動きや霧の中に浮かぶ市街地が見えて、晴れとは違う表情がある。マークイズ・ランドマークプラザと屋内で繋がるため、移動中に濡れない。",
        [I.mm_blue],
        [
          { k: "最寄り駅", v: "みなとみらい駅 直結" },
          { k: "料金", v: "大人 1,000円" },
          { k: "雨の日", v: "◎ 屋内展望フロア" },
          { k: "おすすめ時間", v: "どの時間帯でも可" }]),
      s(5, "YOKOHAMA AIR CABIN", "ロープウェイ", "みなとみらい",
        "都市型ゴンドラ。雨の日でも乗れる",
        "桜木町駅とみなとみらいの運河パークを結ぶ全長630mの都市型ゴンドラ。悪天候時は運休になることがあるが、小雨程度なら運行継続していることが多い。ゴンドラの中から見る雨の港町は晴れと違う質感がある。乗車時間は約5分。",
        [I.mm_blue],
        [
          { k: "最寄り駅", v: "桜木町駅 直結" },
          { k: "料金", v: "片道 1,000円" },
          { k: "雨の日", v: "△ 強風・強雨で運休あり" },
          { k: "所要時間", v: "約5分" }])],
    sideArticles: [
      side("みなとみらいデート5選", "new-minatomirai-date", I.mm_blue),
      side("横浜駅周辺雨の日デート", "new-yokohama-station-rainy", I.mm_blue)],
    quote: "雨でも選択肢が多いのがみなとみらいの強み。事前に屋内の動線を決めておくだけで安心感が違う。",
    quoteCite: author,
    closing: "標準動線は、みなとみらい駅→横浜美術館（11:00〜13:00）→館内カフェでランチ→ランドマークタワー展望スカイガーデン（14:00〜15:30）→AIR CABIN で運河パーク方向へ（15:30〜15:45）→カップヌードルミュージアム（16:00〜17:30）→赤レンガ倉庫内のレストランで夕食。所要5〜6時間、予算は美術館・展望・AIR CABIN・夕食込みで1人6,000〜10,000円が目安。「雨の日でもみなとみらいデートを成立させたい人」「アート・体験型施設・展望のバランスを取りたい人」に向く。土日午後は美術館・展望ともピーク混雑、平日または雨予報の日が比較的空いている。晴天時はAIR CABINよりも徒歩・汽車道のほうが景色が良いので、雨予報のときに使う発想で十分。時間がない場合は、横浜美術館＋ランドマーク展望の2点で3時間半に圧縮できる。迷ったら、雨の日ほどアート・展望の屋内空間が空いている事実を活かして、平日に来られる人は雨の日狙いがコスパが良い。",
  },

  // ─── 3. 桜木町夜デート5選 ───
  "new-sakuragicho-night-date": {
    id: "new-sakuragicho-night-date",
    no: "NG-03", articleType: "guide",
    kicker: "SAKURAGICHO NIGHT DATE",
    title: "桜木町夜デート5選。夜景と光が似合う場所",
    titleHTML: "桜木町<br>夜デート5選。",
    subtitle: "汽車道の夜、コスモクロック21、AIR CABIN。桜木町から歩いて回る夜の港",
    lede: "桜木町は夜景デートに最も特化した横浜のエリア。JR根岸線・横浜市営地下鉄・みなとみらい線が交差し、駅から徒歩5分以内にコスモワールドの観覧車・ランドマークタワー・ロープウェイ AIR CABIN・赤レンガ倉庫が並ぶ。夜18時以降に動き始めて、22時頃まで4時間で複数の夜景スポットを回れる動線が組める。ここでは初訪問でも迷わずに桜木町で夜景を回れる5スポットを紹介する。夜の集合・解散がしやすい桜木町駅を起点に解説する。",
    date, reading: "約7分", author,
    heroImage: I.cosmo,
    ranking: [
      s(1, "汽車道（夜）", "プロムナード", "みなとみらい",
        "夜は街灯と水面の反射で雰囲気が変わる",
        "日中とは違う顔を見せる汽車道。沿道のライトと水面の反射が重なり、同じ道でも別の場所に感じる。桜木町駅から出てすぐ歩き始められ、コスモワールドまで迷わずたどり着ける。夜10時頃まで人通りがある。",
        [I.kishamichi, I.kisha2],
        [
          { k: "最寄り駅", v: "桜木町駅 徒歩5分" },
          { k: "雨の日", v: "✕ 屋外遊歩道" },
          { k: "おすすめ時間", v: "日没後〜22時頃" }]),
      s(2, "コスモクロック21（夜）", "観覧車", "みなとみらい",
        "ライトアップされた観覧車が夜の象徴",
        "夜のコスモクロック21はゴンドラがカラフルに輝き、みなとみらいのランドマークとして機能する。乗るのもいいが、外から眺めるだけでも絵になる。周囲のコスモワールドの乗り物と合わせて1〜2時間過ごせる。予算を決めてから入ると計画しやすい。",
        [I.cosmo],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩3分" },
          { k: "料金目安", v: "観覧車 900円" },
          { k: "おすすめ時間", v: "19時〜22時" }]),
      s(3, "YOKOHAMA AIR CABIN（夜）", "ロープウェイ", "みなとみらい",
        "夜のゴンドラから見る港の光",
        "夜間も運行しており、ゴンドラの中から見る夜景が晴れた日の昼間とは全く違う景観になる。乗車時間は約5分と短いが、会話が自然にできるサイズ感で使いやすい。桜木町駅乗り場から乗って、みなとみらい側で降りると移動手段にもなる。",
        [I.mm_blue],
        [
          { k: "最寄り駅", v: "桜木町駅 直結" },
          { k: "料金", v: "片道 1,000円" },
          { k: "おすすめ時間", v: "夕暮れ〜夜" }]),
      s(4, "野毛山公園（夜景スポット）", "公園・展望", "野毛",
        "地元の人が使う穴場の夜景スポット",
        "桜木町駅から徒歩15分の小高い丘。公園の展望広場からみなとみらいのビル群が眺められる。観光客が少なく、人が少ない夜景スポットを探しているときに使いやすい。駅から少し歩くため、食事の前後に組み込むより、散歩を楽しむ余裕があるときに向いている。",
        [I.cosmo],
        [
          { k: "最寄り駅", v: "桜木町駅 徒歩15分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" },
          { k: "おすすめ時間", v: "日没後" }]),
      s(5, "新港ふ頭・横浜ハンマーヘッド", "ウォーターフロント", "新港",
        "夜の港に停泊する船と光を見る",
        "赤レンガ倉庫の隣に位置するハンマーヘッドは、クルーズ客船が寄港する岸壁に整備された複合施設。夜は照明がシックで、海に向かって開けた広場がある。にぎやかすぎず、二人で座って話すための空間がある。",
        [I.akarenga, I.osanbashi],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩10分" },
          { k: "料金", v: "無料（ショッピング・飲食別途）" },
          { k: "おすすめ時間", v: "夕方〜夜" }])],
    sideArticles: [
      side("みなとみらいデート5選", "new-minatomirai-date", I.mm_blue),
      side("赤レンガ倉庫周辺デート3選", "new-akarenga-date", I.akarenga)],
    quote: "桜木町の夜は、歩き始めればそのまま景色が続く。目的地を決めすぎないほうが気持ちよく過ごせる。",
    quoteCite: author,
    closing: "標準動線は、桜木町駅集合18:00→AIR CABIN で運河パーク方向（18:00〜18:30）→コスモワールド観覧車（18:30〜19:30）→赤レンガ倉庫散歩＋ディナー（19:30〜21:30）→大さん橋屋上で夜景（22:00〜22:30）→桜木町駅で解散。所要4〜5時間、予算は1人5,000〜10,000円が目安。「夜景デートを徒歩で複数スポット回りたい人」「東京方面より落ち着いた港町の夜を体験したい人」「写真撮影が好きな2人」に向く。土日19〜21時はピーク混雑、平日夜または冬の平日が落ち着いている。雨の日はAIR CABIN・ランドマーク展望・赤レンガ屋内エリアに切り替えると、傘なしでも夜景デートが組める。時間がない場合は、観覧車→大さん橋の2点で90分コースに圧縮できる。迷ったら、観覧車→赤レンガ倉庫→大さん橋の三点をシンプルに歩く、というのが桜木町夜景デートの王道。",
  },

  // ─── 4. 赤レンガ倉庫周辺デート3選 ───
  "new-akarenga-date": {
    id: "new-akarenga-date",
    no: "NG-04", articleType: "guide",
    kicker: "AKARENGA DATE",
    title: "赤レンガ倉庫周辺デート3選。港の空気を感じる場所",
    titleHTML: "赤レンガ倉庫<br>周辺デート3選。",
    subtitle: "赤レンガ倉庫、象の鼻パーク、ハンマーヘッド。海沿いを歩くだけで成立するデート",
    lede: "赤レンガ倉庫周辺は、明治・大正の歴史的港湾遺構と、近代的なみなとみらいの景観が交差する横浜らしいエリア。1911年竣工の赤レンガ倉庫を中心に、象の鼻パーク・横浜ハンマーヘッドが徒歩で繋がる海沿いのデートルートが組める。海風と歴史建築のコンビネーションが、東京とは違う「港町デート」の質感を作り出す。ここでは赤レンガ倉庫を起点に、海沿いを歩く3スポットを紹介する。",
    date, reading: "約6分", author,
    heroImage: I.akarenga,
    ranking: [
      s(1, "横浜赤レンガ倉庫", "歴史建築・商業施設", "新港",
        "明治期の倉庫がそのまま商業施設に。食事もショッピングもできる",
        "1911年・1913年竣工の2棟が現存し、国の重要文化財に準じた歴史的建造物。1号館はイベントホール・レストラン、2号館はショップと飲食が入る。前庭広場から海側を向くとみなとみらいのビル群と港の景色が広がり、屋外に出るだけで絵になる。周辺でマルシェや季節イベントが定期的に開催される。",
        [I.akarenga],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩12分 / 馬車道駅 徒歩6分" },
          { k: "営業時間", v: "施設により異なる（11時〜20時頃）" },
          { k: "雨の日", v: "◎ 屋内施設あり、広場は屋外" }]),
      s(2, "象の鼻パーク", "公園・ウォーターフロント", "新港",
        "開港の歴史と現在の海がある、無料で開放された広場",
        "横浜港発祥の地として整備された公園。「象の鼻防波堤」と名付けられた歴史的な防波堤が残り、カフェが一軒入っている。赤レンガ倉庫から大さん橋まで歩いてつなげられる動線上にあり、途中の休憩・写真スポットとして自然に立ち寄れる。入場無料。",
        [I.osanbashi2],
        [
          { k: "最寄り駅", v: "日本大通り駅 徒歩5分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ ほぼ屋外" },
          { k: "所要時間", v: "15〜30分" }]),
      s(3, "横浜ハンマーヘッド", "ウォーターフロント複合施設", "新港",
        "赤レンガの隣の新しい港。開放的な岸壁テラス",
        "2019年に整備された複合施設で、飲食・ショッピング・ホテルが入る。岸壁沿いのデッキから海面を直接見下ろせ、みなとみらいとは反対側の横浜港が見える。赤レンガ倉庫から徒歩5分以内で移動できるため、倉庫を見た後に立ち寄りやすい。夜は静かで落ち着いた雰囲気になる。",
        [I.akarenga, I.osanbashi],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩10分" },
          { k: "料金", v: "無料（飲食別途）" },
          { k: "雨の日", v: "△ 屋内部分あり" },
          { k: "おすすめ時間", v: "夕方〜夜" }])],
    sideArticles: [
      side("大さん橋夜景デート3選", "new-osanbashi-nightview-date", I.osanbashi),
      side("みなとみらいデート5選", "new-minatomirai-date", I.mm_blue)],
    quote: "赤レンガ→象の鼻→ハンマーヘッドの順に歩くと、海との距離感が変わりながら港を体感できる。",
    quoteCite: author,
    closing: "標準動線は、馬車道駅→赤レンガ倉庫（14:00〜16:00 ショッピング＋カフェ）→象の鼻パーク（16:00〜17:00 散歩＋夕景）→横浜ハンマーヘッド（17:00〜19:00 ディナー）→海沿い夜景観賞。所要4〜5時間、予算は1人4,500〜8,000円が目安。「歴史建築と港の景色をゆっくり歩きたい人」「みなとみらいの混雑を避けて静かなデートを組みたい人」「海沿いの散歩が好きな2人」に向く。土日夕方の赤レンガ広場はイベント時に大混雑するが、平日や象の鼻パークは比較的空いている。雨の日は赤レンガ倉庫館内・ハンマーヘッド館内で完結できるので、屋内中心ルートに切り替えれば傘を最小限に。時間がない場合は、赤レンガ倉庫だけ60〜90分滞在で完結できる。迷ったら、夕方17時頃に赤レンガに到着し、夕景と夜景の境目を象の鼻パークで見るのが最もコスパが良い。",
  },

  // ─── 5. 大さん橋周辺で夜景を見るデート3選 ───
  "new-osanbashi-nightview-date": {
    id: "new-osanbashi-nightview-date",
    no: "NG-05", articleType: "guide",
    kicker: "OSANBASHI NIGHT VIEW",
    title: "大さん橋周辺で夜景を見るデート3選",
    titleHTML: "大さん橋周辺で<br>夜景を見るデート3選",
    subtitle: "大さん橋屋上デッキ、山下公園、港の見える丘公園。横浜夜景の三定番",
    lede: "横浜の夜景デートで「ハズレなし」の3スポットといえば、大さん橋屋上デッキ・山下公園・港の見える丘公園。いずれも入場無料で、徒歩圏内に並んでおり、海風と夜景を浴びながら歩く動線が組める。高い展望台に登らなくても、地上から見上げる港の夜景は十分に美しい。ここでは元町・中華街駅を起点に、無料で完結する横浜夜景3スポットを紹介する。",
    date, reading: "約6分", author,
    heroImage: I.osanbashi,
    ranking: [
      s(1, "大さん橋国際客船ターミナル 屋上デッキ", "展望デッキ", "中区・新港",
        "横浜港を360度見渡せる、入場無料の屋上",
        "波打つ木のデッキが特徴的な屋上広場は、みなとみらいのビル群・横浜ベイブリッジ・山下公園側の夜景が同時に見える場所。入場は24時間無料で、混雑しすぎず座れる場所がある。夜は風が出ることが多いため羽織り物は必須。日没の30分前から着いていると、変化していく空の色が見られる。",
        [I.osanbashi, I.osanbashi2],
        [
          { k: "最寄り駅", v: "日本大通り駅 徒歩7分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外デッキ" },
          { k: "おすすめ時間", v: "日没〜22時" }]),
      s(2, "山下公園（夜）", "公園・水辺", "中区・山下",
        "氷川丸を横目に、海沿いを歩く夜散歩",
        "横浜港に沿って伸びる公園。夜は照明が控えめで、氷川丸（旧日本郵船の客船）の光と港の反射が絵になる。大さん橋から徒歩10分。海側の柵沿いを歩くと、正面にみなとみらいのビル群が続く。ベンチが多く、座って話せる場所が確保しやすい。",
        [I.yamashita, I.yamashita2],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩3分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" },
          { k: "おすすめ時間", v: "夜〜21時頃" }]),
      s(3, "港の見える丘公園", "展望公園", "山手",
        "山の上から見下ろす横浜港の夜景",
        "元町・中華街駅から徒歩10分の高台にある公園。横浜港、大さん橋、みなとみらいのビル群が一望できる無料の展望スポット。バラ園が有名で、季節によっては花と夜景が同時に楽しめる。山下公園から坂を上がる形でつなげると、高低差が加わり景色の変化が楽しめる。",
        [I.yamashita],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩10分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" },
          { k: "おすすめ時間", v: "日没後" }])],
    sideArticles: [
      side("山下公園周辺デート5選", "new-yamashita-date", I.yamashita),
      side("赤レンガ倉庫周辺デート3選", "new-akarenga-date", I.akarenga)],
    quote: "大さん橋から山下公園を歩いて、丘に上がる。この30分の動線が横浜夜景の答えになる。",
    quoteCite: author,
    closing: "標準動線は、元町・中華街駅で18:00集合→中華街でディナー（18:00〜19:30）→山下公園で夜景散歩（19:30〜20:30）→大さん橋屋上デッキで夜景観賞（20:30〜21:30）→港の見える丘公園で締め（22:00〜22:30）→元町・中華街駅で解散。所要4〜5時間、予算はディナー込みで1人3,500〜7,000円が目安（夜景3スポットすべて無料）。「予算を抑えてロマンチックな夜景デートを組みたい人」「徒歩で港町の夜を歩きたい人」「展望台に並ぶのが嫌な2人」に向く。土日19〜21時は大さん橋がやや混むが、無料スポットなので並ばずに入れる。雨の日は屋外中心の動線なので傘必須、または屋内（赤レンガ倉庫・ランドマーク）に切り替える。時間がない場合は、大さん橋→山下公園の2点で1時間半に圧縮できる。迷ったら、まず大さん橋屋上に座って夜景を眺めるだけで、横浜デートの満足度は十分に成立する。",
  },

  // ─── 6. 馬車道レトロ建築さんぽ5選 ───
  "new-bashamichi-architecture": {
    id: "new-bashamichi-architecture",
    no: "NG-06", articleType: "guide",
    kicker: "BASHAMICHI ARCHITECTURE",
    title: "馬車道レトロ建築さんぽ5選。明治・大正の洋館を歩く",
    titleHTML: "馬車道<br>レトロ建築さんぽ5選。",
    subtitle: "旧横浜正金銀行、旧生糸検査所、県庁本庁舎。関内で重なる時代の層",
    lede: "馬車道は1869年に日本で最初に「馬車道」として整備された通り。明治・大正の歴史的洋館が今も現役で残る、東京駅丸の内側に匹敵する近代建築遺産の集積地。横浜開港資料館・神奈川県立歴史博物館・旧横浜正金銀行（現・神奈川県立歴史博物館本館）・旧生糸検査所など、保存状態の良い建築が徒歩圏に並ぶ。建築好きの2人が平日の落ち着いた午後に歩くと、東京と並ぶ建築文化の厚みが見えてくる。ここでは馬車道駅を起点に、洋館建築を巡る5スポットを紹介する。",
    date, reading: "約7分", author,
    heroImage: I.museum,
    ranking: [
      s(1, "神奈川県立歴史博物館（旧横浜正金銀行本店）", "歴史建築・博物館", "馬車道",
        "1904年竣工のネオ・バロック様式。ドームが目印",
        "旧横浜正金銀行本店として1904年に建てられた石造建築。緑色のドームと重厚な円柱が特徴で、関東大震災でドームが焼失したが戦後に復元された。現在は神奈川県立歴史博物館として使われ、内部の見学も可能。馬車道駅から徒歩1分、通りの中でも最も存在感のある建物。",
        [I.museum, I.museum_n],
        [
          { k: "最寄り駅", v: "馬車道駅 徒歩1分" },
          { k: "入館料", v: "常設展 300円" },
          { k: "雨の日", v: "◎ 屋内見学可" }]),
      s(2, "旧横浜市庁舎（横浜市歴史的建造物）", "歴史建築", "関内",
        "1959年竣工の市庁舎がそのまま保存活用中",
        "2020年まで現役だった旧横浜市庁舎。近代建築の外観が関内の街並みのなかで存在感を持ち、現在はリノベーション事業として活用が進んでいる。外観の撮影だけでも訪れる価値があり、正面の広場から見上げると建物の縦のラインがよくわかる。",
        [I.museum],
        [
          { k: "最寄り駅", v: "関内駅 徒歩5分" },
          { k: "料金", v: "外観無料" },
          { k: "雨の日", v: "△ 外観見学のみの場合は天候依存" }]),
      s(3, "横浜第二合同庁舎（旧横浜生糸検査所）", "歴史建築", "馬車道",
        "1926年の生糸検査所が現在も現役の庁舎として使われている",
        "横浜港から荷揚げされた生糸を検査していた施設。昭和初期の石造りの外観が残り、道路側から見学できる。馬車道沿いにあり、県立歴史博物館と組み合わせて歩きやすい位置関係。内部は一般非公開だが外観の存在感で十分記憶に残る。",
        [I.museum_n],
        [
          { k: "最寄り駅", v: "馬車道駅 徒歩3分" },
          { k: "料金", v: "外観無料" }]),
      s(4, "神奈川県庁本庁舎（キングの塔）", "歴史建築", "関内",
        "横浜三塔のひとつ「キング」。帝冠様式の塔が目印",
        "1928年竣工の帝冠様式建築で、横浜港に入港した船から見えた「横浜三塔」のうちのひとつ（キング）。内部の見学も時間限定で可能。正面エントランスの意匠が特徴的で、近づくと彫刻の細かさに気づく。日本大通りと組み合わせて歩くと見どころがまとまる。",
        [I.museum],
        [
          { k: "最寄り駅", v: "日本大通り駅 徒歩3分" },
          { k: "料金", v: "外観無料（内部見学は平日限定）" },
          { k: "雨の日", v: "◎ 内部見学可（要確認）" }]),
      s(5, "横浜開港資料館（旧英国総領事館）", "歴史建築・資料館", "日本大通り",
        "1931年竣工の旧英国総領事館。庭の大木と石造りが印象的",
        "1931年建設の旧英国総領事館を転用した資料館。中庭にある「たまくすの木」は横浜開港の歴史を見てきた老木として有名。常設展では横浜の開港から発展までが写真・文書で紹介される。外観・庭だけなら無料で入れる。",
        [I.museum_n],
        [
          { k: "最寄り駅", v: "日本大通り駅 徒歩1分" },
          { k: "入館料", v: "大人 200円" },
          { k: "雨の日", v: "◎ 屋内展示あり" }])],
    sideArticles: [
      side("関内・日本大通りさんぽ5選", "new-kannai-nihondori", I.museum_n),
      side("元町・山手さんぽ5選", "new-motomachi-yamate", I.motomachi)],
    quote: "馬車道から日本大通りにかけて1kmも歩けば、100年以上の建築が今も生きているのがわかる。",
    quoteCite: author,
    closing: "標準動線は、馬車道駅→神奈川県立歴史博物館（11:00〜12:30 建築＋常設展）→旧生糸検査所＋富士銀行旧館（12:30〜13:30 外観散歩）→日本大通り散歩（13:30〜14:30）→横浜開港資料館（14:30〜15:30）→神奈川県庁本庁舎キング塔（15:30〜16:00）→赤レンガ倉庫方向へ。所要4〜5時間、予算は博物館入場込みで1人2,500〜4,500円が目安。「明治・大正・昭和初期の近代建築が好きな人」「歴史散歩を組みたい2人」「赤レンガ倉庫の前のオプションとして文化的に時間を使いたい人」に向く。土日午後は神奈川県立歴史博物館で企画展がある時にやや混むが、平日午後は基本的に静か。雨の日は屋内中心ルート（県立歴史博物館＋横浜開港資料館）で2〜3時間過ごせる。時間がない場合は、神奈川県立歴史博物館＋日本大通り散歩の2点で2時間に圧縮できる。迷ったら、神奈川県立歴史博物館を内部見学し、その後は外観だけ巡る散歩、という組み立てが満足度が高い。",
  },

  // ─── 7. 関内・日本大通りさんぽ5選 ───
  "new-kannai-nihondori": {
    id: "new-kannai-nihondori",
    no: "NG-07", articleType: "guide",
    kicker: "KANNAI NIHONDORI WALK",
    title: "関内・日本大通りさんぽ5選。横浜発祥の街を歩く",
    titleHTML: "関内・日本大通り<br>さんぽ5選。",
    subtitle: "日本大通り、開港資料館、スタジアム界隈。横浜らしさが残る中心地の歩き方",
    lede: "関内・日本大通りは横浜開港（1859年）の発祥地であり、横浜の街として最初に都市計画された区画。日本大通り・横浜公園・横浜スタジアム・中華街が徒歩圏内で繋がり、横浜の「中心街」としての歴史的位置を体感できる。近代建築・スポーツ施設・公園・繁華街と性格の違うスポットが並ぶため、半日歩いても飽きない構成が組める。ここでは関内駅・日本大通り駅を起点に、5スポットを紹介する。",
    date, reading: "約7分", author,
    heroImage: I.museum_n,
    ranking: [
      s(1, "日本大通り", "歴史的街路", "関内",
        "日本初の西洋式街路。ケヤキ並木と歴史建築が並ぶ",
        "1875年に完成した日本初の西洋式街路計画道路。歩道が広く、ケヤキ並木が続く。沿道には神奈川県庁（キング）・開港資料館・横浜市開港記念会館（ジャック）が揃い、建築好きには見ごたえがある。秋の紅葉時期は特に雰囲気が良い。",
        [I.museum, I.museum_n],
        [
          { k: "最寄り駅", v: "日本大通り駅 直結" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "△ 並木道のため多少の雨なら歩ける" }]),
      s(2, "横浜市開港記念会館（ジャックの塔）", "歴史建築", "関内",
        "横浜三塔「ジャック」。1917年竣工のドーム付き建築",
        "横浜開港50周年を記念して1917年に完成した市民の記念館。塔のシルエットが横浜三塔の「ジャック」と親しまれる。ステンドグラスが美しく、内部見学も可能（時間帯要確認）。日本大通り駅から徒歩すぐで、日本大通りと組み合わせて自然に立ち寄れる。",
        [I.museum],
        [
          { k: "最寄り駅", v: "日本大通り駅 徒歩2分" },
          { k: "料金", v: "外観無料（内部見学は時間帯限定）" },
          { k: "雨の日", v: "◎ 内部見学可" }]),
      s(3, "横浜スタジアム周辺（横浜公園）", "公園", "関内",
        "球場を囲む公園。チューリップの名所でもある",
        "プロ野球・DeNAベイスターズの本拠地・横浜スタジアムを囲む公園。試合がない日は静かで、公園内のベンチに座ってゆっくりできる。チューリップが有名で春は色とりどりの花が咲く。周辺のカフェや飲食店が充実しており、休憩しやすい。",
        [I.museum_n],
        [
          { k: "最寄り駅", v: "関内駅 徒歩3分" },
          { k: "料金", v: "無料（試合観戦は別途）" },
          { k: "雨の日", v: "✕ 屋外" }]),
      s(4, "横浜開港資料館", "資料館・歴史建築", "日本大通り",
        "旧英国総領事館を転用した資料館。庭の老木が印象的",
        "横浜の開港から発展の歴史を写真・文書・模型で展示。中庭のたまくすの木のそばに座って休憩できる。展示は充実しているが、外観と中庭だけを無料で楽しんで隣の日本大通りに戻る使い方もできる。",
        [I.museum],
        [
          { k: "最寄り駅", v: "日本大通り駅 徒歩1分" },
          { k: "入館料", v: "大人 200円" },
          { k: "雨の日", v: "◎ 屋内展示あり" }]),
      s(5, "馬車道商店街", "歴史的商店街", "馬車道",
        "レンガ敷きの歩道が続く横浜らしい通り",
        "伊勢佐木町から関内を結ぶ商店街。レンガ舗装と独特の街灯が続き、個人経営の老舗と新しいカフェが混在する。観光地的な華やかさはないが、横浜の街の日常に近い空気がある。馬車道駅から歩き始めて、大通り公園まで抜けると自然な散歩コースになる。",
        [I.museum_n],
        [
          { k: "最寄り駅", v: "馬車道駅 直結" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "△ アーケードなし" }])],
    sideArticles: [
      side("馬車道レトロ建築さんぽ5選", "new-bashamichi-architecture", I.museum),
      side("横浜中華街周辺で遊ぶ5選", "new-chinatown-sightseeing", I.chinatown)],
    quote: "関内から日本大通りを歩くと、横浜がどうやってできた街なのかが少しわかってくる。",
    quoteCite: author,
    closing: "標準動線は、日本大通り駅→日本大通り散歩（13:00〜14:00）→横浜開港資料館（14:00〜15:00）→横浜公園・横浜スタジアム周辺散歩（15:00〜16:00）→ホテルニューグランドでアフタヌーンティーまたはカフェ（16:00〜17:30）→山下公園散歩で締め。所要4〜5時間、予算はカフェ・博物館込みで1人3,500〜6,000円が目安。「横浜の発祥地である関内の歴史を体感したい人」「ナイトゲーム観戦と組み合わせたい人」「ホテルニューグランドで横浜の戦前文化に触れたい人」に向く。ベイスターズのホームゲーム日（公式サイトで確認）は18時以降の関内駅周辺が混雑するので、デートでは試合日を避けるか、観戦を組み込むか決めて来る。雨の日は横浜開港資料館＋ホテルニューグランドの屋内中心で2〜3時間過ごせる。時間がない場合は、日本大通り散歩＋ホテルニューグランドカフェの2点で2時間に圧縮できる。迷ったら、午後の早めに来て横浜開港資料館で歴史を抑え、その後で街を歩くと、見る場所の意味が深まる。",
  },

  // ─── 8. 山下公園周辺デート5選 ───
  "new-yamashita-date": {
    id: "new-yamashita-date",
    no: "NG-08", articleType: "guide",
    kicker: "YAMASHITA DATE",
    title: "山下公園周辺デート5選。港と丘をつなぐ横浜の定番",
    titleHTML: "山下公園<br>周辺デート5選。",
    subtitle: "山下公園、氷川丸、港の見える丘公園、山手洋館。海から丘へ歩くコース",
    lede: "山下公園は1930年開園の日本初の臨海公園で、横浜の港町としての象徴的な公園。約700mの遊歩道に沿って、氷川丸・インド水塔・未来のバラ園・噴水・水の階段が並び、海と港の景色を一気に体感できる。山下公園を起点に、徒歩圏内で港の見える丘公園・中華街・元町商店街と異なる性格のスポットに繋げられる動線が組める。ここでは山下公園を中心とした5スポットを、午後〜夕方のデートルートとして紹介する。",
    date, reading: "約7分", author,
    heroImage: I.yamashita,
    ranking: [
      s(1, "山下公園", "公園・水辺", "中区・山下",
        "横浜港に沿って伸びる公園。花と海と氷川丸",
        "1930年に開園した横浜を代表する公園。港に沿って細長く伸びており、対岸にみなとみらいが見える。赤い靴の女の子の像、インド水塔、バラ園など見どころがある。氷川丸が公園の外縁に停泊しており、外観だけなら無料で近くまで寄れる。",
        [I.yamashita, I.yamashita2],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩3分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" },
          { k: "おすすめ時間", v: "午前〜夕方" }]),
      s(2, "氷川丸（日本郵船氷川丸）", "船舶ミュージアム", "山下",
        "現役引退した客船をそのまま見学できる",
        "1930年就航の元旅客船。山下公園に永久係留され、船内を見学できる。デッキからの横浜港の眺めが良く、船旅の雰囲気が体験できる。山下公園を歩く流れで自然に立ち寄れる。",
        [I.yamashita],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩5分" },
          { k: "入館料", v: "大人 300円" },
          { k: "雨の日", v: "◎ 船内見学は屋内" }]),
      s(3, "港の見える丘公園", "展望公園", "山手",
        "山の上から横浜港が一望できる無料の展望スポット",
        "元町・中華街駅から徒歩10分の丘にある公園。バラ園が有名で、開花シーズンは花と港の景色が両方楽しめる。ベンチも多く、横浜港全体が見渡せる開放的な場所。山下公園から坂を歩いて上がる形でコースが作れる。",
        [I.yamashita],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩10分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" }]),
      s(4, "山手西洋館エリア（ブラフ18番館など）", "歴史建築", "山手",
        "明治〜大正期の洋館が7棟公開。入場無料",
        "山手の丘に残る西洋館群。ブラフ18番館・エリスマン邸・ベーリック・ホールなど7棟が無料公開されている。外国人居留地として発展した時代の住宅建築が、今も当時の内装を保ちながら公開されている。港の見える丘公園と組み合わせると1〜2時間のコースになる。",
        [I.motomachi],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩10〜15分" },
          { k: "料金", v: "無料（一部施設は有料）" },
          { k: "雨の日", v: "◎ 屋内見学可" }]),
      s(5, "マリンタワー", "展望台", "山下",
        "改修後リニューアル。山下公園の正面にある展望台",
        "2022年にリニューアルオープン。地上から約94mの展望フロアから、山下公園・横浜港・みなとみらいを俯瞰できる。昼間は港の全景、夜は夜景が見える。山下公園のすぐ隣にあり、公園散歩とセットで訪れやすい。",
        [I.yamashita2],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩5分" },
          { k: "入館料", v: "大人 750円" },
          { k: "雨の日", v: "◎ 屋内展望フロア" }])],
    sideArticles: [
      side("大さん橋夜景デート3選", "new-osanbashi-nightview-date", I.osanbashi),
      side("元町・山手さんぽ5選", "new-motomachi-yamate", I.motomachi)],
    quote: "山下公園は起点。ここから海沿いか丘側か、どちらに向かうかで一日の景色が変わる。",
    quoteCite: author,
    closing: "標準動線は、元町・中華街駅→山下公園で散歩（13:00〜14:00）→氷川丸見学（14:00〜15:00）→港の見える丘公園で展望（15:00〜16:00）→元町商店街でショッピング＋カフェ（16:00〜17:30）→中華街でディナー。所要5〜6時間、予算は氷川丸＋食事込みで1人5,000〜8,000円が目安。「横浜の港町と外国人居留地の歴史を歩きたい人」「老舗ブランドのウィンドウショッピングを楽しみたい人」「中華街の前後の散歩動線を組みたい人」に向く。土日午後は元町商店街と港の見える丘公園のバラ園が混雑、平日午後または朝が落ち着いている。雨の日は氷川丸見学＋元町商店街の屋内中心で半日が組める。時間がない場合は、山下公園散歩→中華街ディナーの2点で2時間に圧縮できる。迷ったら、夕方17時前に山下公園に着いて夕景を見てから中華街でディナー、というシンプルな組み立てが横浜の王道。",
  },

  // ─── 9. 横浜中華街周辺で遊ぶ5選 ───
  "new-chinatown-sightseeing": {
    id: "new-chinatown-sightseeing",
    no: "NG-09", articleType: "guide",
    kicker: "CHINATOWN SIGHTSEEING",
    title: "横浜中華街周辺で遊ぶ5選。食べる以外の楽しみ方",
    titleHTML: "横浜中華街<br>周辺で遊ぶ5選。",
    subtitle: "関帝廟、媽祖廟、山下公園、元町。中華街を起点に広げる横浜散策",
    lede: "横浜中華街は食事目的で来る場所というイメージが強いが、周辺に歩いて楽しめるスポットが多くある。中華街を食事の前後に立ち寄るスポットを組み合わせると、半日の予定が自然に埋まる。",
    date, reading: "約5分", author,
    heroImage: I.chinatown,
    ranking: [
      s(1, "横浜中華街（街歩き）", "中国文化・グルメ", "中華街",
        "中国の廟や門を見ながら食べ歩く",
        "約600店舗が集まる日本最大の中華街。南北・東西に十字の通りが通り、各方角に牌楼（門）が立つ。関帝廟・媽祖廟・横浜大世界など観光スポットも点在する。食べ歩きよりも先に廟や門を見て歩くと、中華街の構造がわかり回りやすくなる。",
        [I.chinatown, I.china_nite],
        [
          { k: "最寄り駅", v: "元町・中華街駅 直結" },
          { k: "料金", v: "無料（飲食別途）" },
          { k: "雨の日", v: "△ 屋根のある商店街あり" }]),
      s(2, "関帝廟（横浜中華街）", "中国寺院", "中華街",
        "中華街の中心にある関羽を祀る廟。内部見学可",
        "商売の神様・関羽を祀る廟。内部には色鮮やかな彫刻と香炉があり、線香の煙と参拝者の往来が本場の廟の雰囲気を再現している。入廟料100円で内部に入れる。中華街に来たなら食事の前後に立ち寄ると、ただ食べるだけでは終わらない滞在になる。",
        [I.chinatown],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩5分" },
          { k: "入廟料", v: "100円" },
          { k: "雨の日", v: "◎ 屋内" }]),
      s(3, "横浜媽祖廟", "中国寺院", "中華街",
        "2006年創建の新しい廟。台湾・福建の海の神様を祀る",
        "海の女神・媽祖を祀る廟で、台湾・福建省の文化が色濃い。関帝廟と少し雰囲気が異なり、どちらも見比べると面白い。廟の周辺は比較的静かで、中華街の喧騒から少し外れた場所にある。",
        [I.china_nite],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩8分" },
          { k: "料金", v: "無料（参拝自由）" },
          { k: "雨の日", v: "◎ 屋内" }]),
      s(4, "山下公園（食後の散歩）", "公園・水辺", "山下",
        "食事後の散歩に。中華街から徒歩5分",
        "中華街の南口から歩いて5分で山下公園に出る。食後の散歩コースとして使いやすく、海風を感じながら歩くと食事の満足感が高まる。みなとみらいの景色を見ながらのんびりするには最適な距離感。",
        [I.yamashita, I.yamashita2],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩3分" },
          { k: "料金", v: "無料" },
          { k: "おすすめ時間", v: "食後の夕方〜夜" }]),
      s(5, "元町ショッピングストリート", "商店街", "元町",
        "中華街から歩いてすぐ。横浜らしい個性派ショップが並ぶ",
        "中華街と元町は徒歩5分以内の距離。食事後に元町のストリートを歩くと、雰囲気が一気に変わる。外国人居留地の影響を受けた独自の洋風文化が残る商店街で、個人オーナーの店が多い。買い物目的でなくても歩いて楽しめる街並みが続く。",
        [I.motomachi],
        [
          { k: "最寄り駅", v: "元町・中華街駅 直結" },
          { k: "料金", v: "無料（ショッピング別途）" },
          { k: "雨の日", v: "△ アーケードなし" }])],
    sideArticles: [
      side("元町・山手さんぽ5選", "new-motomachi-yamate", I.motomachi),
      side("山下公園周辺デート5選", "new-yamashita-date", I.yamashita)],
    quote: "中華街は食事の前後に歩く廟と山下公園があると、立体的な時間が作れる。",
    quoteCite: author,
    closing: "中華街で食事→関帝廟・媽祖廟を巡る→山下公園を散歩→元町に移動という動線が、半日で充実する横浜の定番コース。",
  },

  // ─── 10. 元町・山手さんぽ5選 ───
  "new-motomachi-yamate": {
    id: "new-motomachi-yamate",
    no: "NG-10", articleType: "guide",
    kicker: "MOTOMACHI YAMATE WALK",
    title: "元町・山手さんぽ5選。坂と洋館を歩く横浜",
    titleHTML: "元町・山手<br>さんぽ5選。",
    subtitle: "元町ストリート、外国人墓地、ブラフ18番館、山手イタリア山庭園。港が見える丘の街",
    lede: "元町から山手にかけては、坂を上がるたびに景色が変わる。洋館が公開されており、入場無料で見られる施設が多い。外国人居留地として栄えた時代の空気が、建築と街路に今も残る。",
    date, reading: "約5分", author,
    heroImage: I.motomachi,
    ranking: [
      s(1, "元町ショッピングストリート", "商店街", "元町",
        "横浜固有の「ハマトラ」文化が生まれた通り",
        "元町・中華街駅から直結する約600mのショッピング街。1970年代に「横浜トラディショナル」（ハマトラ）ファッションが生まれた発祥地。老舗と個人店が混在し、デパートのような画一性がない。早い時間帯は比較的静かで、ウィンドウショッピングに向く。",
        [I.motomachi],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩1分" },
          { k: "料金", v: "無料（ショッピング別途）" },
          { k: "雨の日", v: "△ アーケードなし" }]),
      s(2, "外国人墓地（横浜外国人墓地）", "歴史スポット", "山手",
        "幕末から続く外国人墓地。春と秋は一般公開",
        "江戸末期から明治にかけて横浜に滞在した外国人の墓地。春・秋の特定期間に一般公開される。石造りの墓碑と緑の斜面が印象的で、港の見える丘公園に向かう途中に位置する。公開期間外でも外から眺めることはできる。",
        [I.motomachi],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩10分" },
          { k: "料金", v: "寄付制（公開期間中）" },
          { k: "雨の日", v: "✕ 屋外" }]),
      s(3, "ブラフ18番館", "歴史建築（西洋館）", "山手",
        "1920年代の外国人居留地の住宅。無料で内部見学可",
        "関東大震災後の1920年代に建てられた木造洋館。当時の家具・調度品が展示されており、居留地時代の生活が再現されている。入場無料で内部に入れる数少ない洋館のひとつ。庭から港の見える丘公園に続く散歩コースと組み合わせやすい。",
        [I.motomachi],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩15分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "◎ 屋内見学可" }]),
      s(4, "山手イタリア山庭園", "庭園", "山手",
        "明治期の外交官邸跡地が公開庭園に",
        "明治期にイタリア領事館があった丘の跡地を整備した庭園。「外交官の家」（1910年建造の歴史的建造物）と「ブラフ18番館」が庭園内に移築保存されている。庭からの眺めも良く、静かに過ごせる場所。横浜市認定の歴史建造物を無料で見られる。",
        [I.motomachi],
        [
          { k: "最寄り駅", v: "石川町駅 徒歩10分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "△ 庭は屋外、建物内は可" }]),
      s(5, "港の見える丘公園", "展望公園", "山手",
        "山手さんぽの締め。横浜港と大橋が見える展望広場",
        "山手散策の起点・終点として使いやすい公園。バラ園・フランス山・展望広場があり、横浜港・ベイブリッジ・みなとみらいの景色が広がる。元町・中華街駅から徒歩10分で、山手の洋館エリアとセットで回ると自然な流れになる。",
        [I.yamashita],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩10分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外メイン" },
          { k: "おすすめ時間", v: "午前〜夕方" }])],
    sideArticles: [
      side("横浜中華街周辺で遊ぶ5選", "new-chinatown-sightseeing", I.chinatown),
      side("山下公園周辺デート5選", "new-yamashita-date", I.yamashita)],
    quote: "元町から山手の坂を上がると、横浜の外国人居留地時代の時間が感じられる。",
    quoteCite: author,
    closing: "元町ストリート→外国人墓地→ブラフ18番館→イタリア山庭園→港の見える丘公園という2〜3時間コース。無料スポットが多く、気軽に歩ける。",
  },

  // NG-11 ─────────────────────────────────────────────────
  "new-yokohama-station-rainy": {
    id: "new-yokohama-station-rainy",
    no: "NG-11", articleType: "guide", kicker: "YOKOHAMA STATION RAINY DAY",
    title: "横浜駅雨の日5選。濡れずに一日楽しめるショッピングモール＆スポット",
    titleHTML: "横浜駅<br>雨の日5選。",
    subtitle: "そごう・ポルタ・ジョイナス。横浜駅周辺は地下街でつながった屋内スポットの宝庫",
    lede: "横浜駅周辺は東口・西口それぞれに屋内施設が直結しており、地下街でもつながっているため雨の日でも傘なしで動き回れる。百貨店・ショッピングモール・エンタメ施設が揃い、1日で何軒はしごしても飽きない。",
    date, reading: "約4分", author,
    heroImage: I.yoko_sta,
    ranking: [
      s(1, "そごう横浜店", "百貨店", "横浜駅東口",
        "駅直結の大型百貨店。美術展・催事も充実",
        "横浜駅東口に直結する大型百貨店。地下食料品売り場・コスメ・ファッションに加え、8Fの「そごう美術館」では年間を通じてアート系の企画展を開催している。雨の日は美術館目当てで訪れるのが賢い。カフェスペースもあり、ゆったり過ごせる。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅 直結（徒歩0分）" },
          { k: "営業時間", v: "10:00〜20:00（美術館は展覧会による）" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(2, "横浜ポルタ", "地下街", "横浜駅",
        "横浜駅地下に広がるショッピング街。飲食店多数",
        "横浜駅地下に広がる老舗ショッピングモール。ファッション・雑貨・飲食約100店舗が入り、雨に関係なく回れる。横浜駅の各線ホームから直結しているため、乗り換え待ちや雨宿りにも使いやすい。ランチタイムは混むが、14時以降は落ち着く。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅 地下直結" },
          { k: "営業時間", v: "11:00〜21:00（店舗による）" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(3, "横浜ジョイナス", "ショッピングモール", "横浜駅",
        "相鉄線横浜駅直上のモール。ファッション・雑貨",
        "相鉄線横浜駅直上のショッピングモール。ファッション・雑貨・書籍・飲食など幅広く揃う。JR・市営地下鉄からも近く、雨の日のショッピングに向いている。地下1FでポルタとつながりJRホームへのアクセスも良い。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅 直結（相鉄）" },
          { k: "営業時間", v: "11:00〜21:00" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(4, "横浜モアーズ", "ショッピングモール", "横浜駅西口",
        "西口直結の複合商業施設。若者向け〜カジュアルまで",
        "横浜駅西口に直結した商業施設。1F〜9Fにファッション・雑貨・飲食が入り、映画館（横浜ブルク13）も近接する。雨の日は映画→ショッピング→飲食の流れでまる一日過ごしやすい。駅からほぼ濡れずに到達できる。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅西口 徒歩1分" },
          { k: "営業時間", v: "11:00〜21:00" },
          { k: "雨の日", v: "◎ ほぼ屋内" }]),
      s(5, "横浜高島屋", "百貨店", "横浜駅西口",
        "西口を代表する老舗百貨店。食料品・催事が充実",
        "横浜駅西口の老舗百貨店。地下食料品売り場は神奈川・横浜のグルメが揃い、お土産・手土産の調達にも便利。催事スペースでは食フェアや物産展が定期開催されており、雨の日の屋内散策として楽しめる。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅西口 徒歩2分" },
          { k: "営業時間", v: "10:00〜20:00" },
          { k: "雨の日", v: "◎ 完全屋内" }])],
    sideArticles: [
      side("みなとみらい雨の日デート5選", "new-minatomirai-rainy-date", I.cosmo),
      side("川崎雨の日デート5選", "new-kawasaki-rainy-date", I.lazona)],
    quote: "横浜駅周辺は地下街と百貨店がつながっており、雨の日でも完全屋内で一日楽しめる。",
    quoteCite: author,
    closing: "そごう美術館でアートを楽しんでから、ポルタ→ジョイナスとはしごして夕食まで屋内で完結できる。横浜駅周辺は雨の日に強いエリア。",
  },

  // NG-12 ─────────────────────────────────────────────────
  "new-yokohama-station-bored": {
    id: "new-yokohama-station-bored",
    no: "NG-12", articleType: "guide", kicker: "YOKOHAMA STATION TIME",
    title: "横浜駅周辺で時間つぶし5選。待ち時間・移動前に寄れる場所",
    titleHTML: "横浜駅周辺で<br>時間つぶし5選。",
    subtitle: "地下街からそごう美術館まで。横浜駅は「時間が空いたら」のスポットに困らない",
    lede: "横浜駅は乗り換えが多い分、待ち時間が生まれやすい。地下街・百貨店・アートスペースまで徒歩圏内に揃っており、30分から半日まで、時間の長さに合わせて選べる選択肢がある。",
    date, reading: "約4分", author,
    heroImage: I.yoko_sta,
    ranking: [
      s(1, "そごう美術館", "美術館", "横浜駅東口",
        "横浜駅直結で行けるアート空間。企画展が年間通じて開催",
        "そごう横浜店8Fにある私設美術館。印象派〜現代アートまで幅広いジャンルの企画展を開催。入館料は展覧会により異なるが1,000〜1,500円程度。横浜駅から雨に濡れずに行けて、1〜1.5時間で回れるちょうどよいサイズ感が使いやすい。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅 直結（徒歩5分）" },
          { k: "入館料", v: "展覧会による（1,000〜1,500円程度）" },
          { k: "雨の日", v: "◎" }]),
      s(2, "アソビル", "複合エンタメ施設", "横浜駅東口",
        "ゲーム・謎解き・バー・DJブース。横浜駅徒歩2分の遊び場",
        "横浜駅東口徒歩2分の複合エンタメビル。謎解きゲーム・卓球・ダーツ・クレーンゲームなどが入り、友人同士や気軽なデートに向いている。夜はバーとして使えるフロアもあり、昼から夜まで通しで楽しめる。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅東口 徒歩2分" },
          { k: "営業時間", v: "11:00〜23:00（フロアによる）" },
          { k: "雨の日", v: "◎" }]),
      s(3, "横浜ポルタ（散策）", "地下街", "横浜駅",
        "地下街をぶらぶらするだけでも時間が過ぎる",
        "横浜駅地下のショッピング街。ウィンドウショッピングや食べ歩きに向いており、30分〜1時間の時間つぶしに最適。飲食店も多いのでカフェで時間を潰すこともできる。各方面への地下通路としても機能しており、次の目的地への動線を確認しながら歩けるのも利点。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅 地下直結" },
          { k: "料金", v: "無料（飲食・ショッピング別途）" },
          { k: "雨の日", v: "◎" }]),
      s(4, "CIAL横浜", "駅ビル", "横浜駅",
        "JR横浜駅直結の駅ビル。土産・カフェ・雑貨",
        "JR横浜駅に直結した駅ビル。横浜みやげ・スイーツ・カフェが集まっており、旅行前後の土産調達から待ち時間つぶしまで使いやすい。コンコース側にはフードコートもあり、軽食を取りながら待てる。新幹線改札口の近くでは特に使い勝手が良い。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅 直結" },
          { k: "営業時間", v: "10:00〜21:00（一部店舗異なる）" },
          { k: "雨の日", v: "◎" }]),
      s(5, "横浜ランドマークタワー展望台（スカイガーデン）", "展望台", "みなとみらい",
        "横浜駅から徒歩15分。69Fから見る横浜の全景",
        "横浜駅みなとみらい口から徒歩15分、みなとみらい中心部にある273mのタワー。69Fのスカイガーデンからは横浜港・東京湾・富士山まで見渡せる。時間に余裕があれば横浜駅から歩いて訪れたい展望台。入場料は大人1,000円程度。",
        [I.yoko_sta],
        [
          { k: "最寄り駅", v: "横浜駅 徒歩15分 / みなとみらい駅 徒歩5分" },
          { k: "入場料", v: "大人1,000円" },
          { k: "雨の日", v: "◎ 屋内展望台" }])],
    sideArticles: [
      side("横浜駅雨の日5選", "new-yokohama-station-rainy", I.mm_blue),
      side("みなとみらいデート5選", "new-minatomirai-date", I.mm_blue)],
    quote: "横浜駅は東口・西口それぞれに百貨店・地下街・エンタメ施設が揃い、時間が空いても困らない。",
    quoteCite: author,
    closing: "そごう美術館とアソビルを組み合わせれば3〜4時間の時間つぶしになる。みなとみらいへ足を延ばすとさらに時間が作れる。",
  },

  // NG-13 ─────────────────────────────────────────────────
  "new-noge-bar-hop": {
    id: "new-noge-bar-hop",
    no: "NG-13", articleType: "guide", kicker: "NOGE BAR HOP",
    title: "野毛はしご酒3選。横浜の昭和飲み屋街をぶらぶらする夜",
    titleHTML: "野毛<br>はしご酒3選。",
    subtitle: "都橋商店街、野毛小路、日ノ出町ガード下。横浜の大人の夜を楽しむエリア",
    lede: "桜木町駅から大岡川を渡ってすぐ、野毛は昭和から続く飲み屋文化が今も生きている横浜の歓楽街だ。みなとみらいの整った景観から徒歩数分の距離に、立ち飲み・もつ焼き・小さなバーが密集し、1軒1,000〜2,500円ほどで2軒・3軒とはしごできる密度がある。観光客向けに整備された街ではなく、横浜の地元客が日常的に通う場所なので、おしゃれさより人情と価格のバランスが優先される。ここでは「最初の1軒」「中盤の腰を据える1軒」「締めの1軒」という3段構えで動線を組むのが現実的だ。",
    date, reading: "約6分", author,
    heroImage: I.noge,
    ranking: [
      s(1, "都橋商店街（野毛小路）", "レトロ飲み屋街", "野毛",
        "大岡川沿いに並ぶ昭和の名残。2階建て弧状の飲み屋建築",
        "大岡川の弧に沿うように建てられた長屋型の飲み屋ビル群。昭和30年代の木造2階建てがそのまま現役で、幅2〜3畳の小さなバー・スナック・居酒屋がびっしりと連なる。営業時間や客層は店ごとに大きく異なり、地元の常連が多い店ほど一見でも歓迎してくれる傾向がある。18時前後の人がまだ少ない時間帯に1軒目として使うと、店主と話しながら店を選び直す余白ができる。観光客しか集まらない店もあるため、店頭のメニューと価格表示を見てから入るのが安全。桜木町駅から徒歩5分、終電を逃しても帰路を組み直しやすい立地もはしごの起点として優秀。",
        [I.noge],
        [
          { k: "最寄り駅", v: "桜木町駅 徒歩5分 / 日ノ出町駅 徒歩5分" },
          { k: "料金", v: "店舗による（1,000〜3,000円/軒）" },
          { k: "おすすめ時間", v: "18:00〜24:00" }]),
      s(2, "野毛大道芸エリア（野毛本通り）", "飲み屋街", "野毛",
        "大道芸イベントで有名。日常的にも飲食店が密集するエリア",
        "野毛本通り・宮川町通り・野毛小路を中心とした、いわゆる「野毛の中心」エリア。もつ焼き・串揚げ・中華・餃子・町中華・スパイスカレーまで業態が広く、夕方17時から営業する店が多い。毎年春に「野毛大道芸」が開催されるが、普段から路上に椅子を出した立ち飲みが何軒もあり、1軒目より2軒目以降に腰を落ち着けて飲む場所として向く。予算は1人2,000〜3,500円が中心で、現金のみ・伝票なしの店もあるので小銭を多めに持って行きたい。金土の20時以降は満席になりやすく、空席を求めて路地を歩くうちに次の店が見つかるのも野毛の楽しみ方。",
        [I.noge],
        [
          { k: "最寄り駅", v: "桜木町駅 徒歩7分" },
          { k: "料金", v: "立ち飲み500円〜" },
          { k: "おすすめ時間", v: "17:00〜" }]),
      s(3, "日ノ出町ガード下", "バー・居酒屋", "日ノ出町",
        "京急高架下の小規模バーが集まるエリア。野毛と徒歩圏",
        "京急本線・日ノ出町駅の高架下から続く、野毛より少し新しい世代の小箱が並ぶ一帯。クラフトビール・ナチュラルワイン・ジャズバー・スタンディングと、野毛本通りの大衆酒場ではあまり見ない業態が増えている。野毛本通りから徒歩7〜10分で移動でき、はしごの「締め」として20時以降に入る使い方が向く。深夜まで営業する店が多く、最終電車の時間まで腰を据えやすい。ただし福富町方面（黄金町・伊勢佐木町寄り）は客引きが出る区画もあるため、付いていかず店頭表示で判断すること。京急の日ノ出町駅から横浜・品川方面に戻りやすいのも締めの動線として現実的。",
        [I.noge],
        [
          { k: "最寄り駅", v: "日ノ出町駅 徒歩2分" },
          { k: "料金", v: "店舗による" },
          { k: "おすすめ時間", v: "19:00〜" }])],
    sideArticles: [
      side("桜木町夜景デート5選", "new-sakuragicho-night-date", I.cosmo),
      side("馬車道・歴史建築5選", "new-bashamichi-architecture", I.museum)],
    quote: "野毛の飲み屋街は、昭和の大衆酒場文化がいまも息づく横浜の名所。",
    quoteCite: author,
    closing: "標準動線は、都橋商店街（18:00〜19:00で軽く1軒目）→野毛本通り（19:00〜21:00で食事中心の2軒目）→日ノ出町ガード下（21:00〜終電で締めの一杯）。所要1.5〜3時間、予算は1人5,000〜8,000円が目安。観光客的に「横浜らしい昭和の飲み屋街」を体感したい人、地元店主と話したい人、価格を抑えてはしごしたい人に向く。金土の20時以降と大道芸の週末は混雑で待ち時間が長くなるので、開店直後の17〜18時スタートが快適。雨の日は屋根のある都橋商店街→日ノ出町ガード下のルートに絞ると傘を畳んだまま動ける。迷ったら最初の1軒は都橋商店街、最後の1軒は日ノ出町ガード下のクラフトビール系、と決めておくと間の野毛本通りで「今日の気分」に任せて2〜3軒選ぶ余白を持てる。桜木町駅と日ノ出町駅の終電は深夜0〜1時で、京急・JR京浜東北線とも品川・横浜方面へ戻りやすいため、終電を意識した動線設計がしやすいのも野毛のはしご酒の良さ。観光地化した飲み屋街にありがちなチャージ不明確な店ではなく、料金表示のある店を選んで入るのが基本。",
  },

  // NG-14 ─────────────────────────────────────────────────
  "new-shin-yokohama-bored": {
    id: "new-shin-yokohama-bored",
    no: "NG-14", articleType: "guide", kicker: "SHIN-YOKOHAMA TIME",
    title: "新横浜で時間つぶし5選。新幹線待ち・ライブ前後に使える場所",
    titleHTML: "新横浜で<br>時間つぶし5選。",
    subtitle: "ラーメン博物館、スケートリンク、新横浜公園。新幹線の待ち時間にも対応できるエリア",
    lede: "新横浜は新幹線・横浜市営地下鉄・東急の乗り換え拠点。ラーメン博物館を軸に徒歩圏内でスケートリンクや公園が揃い、30分から半日まで対応できる。",
    date, reading: "約4分", author,
    heroImage: I.shin_yoko,
    ranking: [
      s(1, "新横浜ラーメン博物館", "フードテーマパーク", "新横浜",
        "全国の有名ラーメン店が集結。昭和33年の街並みを再現",
        "1994年開業の日本初のフードテーマパーク。全国の有名ラーメン店が常時8店舗前後入れ替わりながら出店している。地下に降りると昭和33年の横丁を再現した空間が広がり、食べ歩き・ハシゴに向いている。新横浜駅から徒歩2分で、新幹線の待ち時間に訪れやすい。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 徒歩2分" },
          { k: "入場料", v: "大人380円" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(2, "新横浜スケートセンター", "屋内スケートリンク", "新横浜",
        "通年営業の本格スケートリンク。初心者も貸靴あり",
        "新横浜公園内にある屋内アイススケートリンク。通年営業で、初心者向けのレンタルスケートも用意されている。1〜2時間の体験で体を動かせるため、観光や待ち時間の合間に使いやすい。新横浜駅から徒歩10分程度。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 徒歩10分" },
          { k: "料金", v: "大人1,500円程度（スケートレンタル別途）" },
          { k: "雨の日", v: "◎ 屋内" }]),
      s(3, "新横浜公園", "公園", "新横浜",
        "日産スタジアム隣接の広大な都市公園",
        "日産スタジアム（横浜国際総合競技場）に隣接する広大な公園。野球場・テニスコート・芝生広場が整備されており、散歩・ジョギングに使われている。川沿いの遊歩道が気持ちよく、ライブ・試合前後の時間つぶしにも向いている。入場無料。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 徒歩10分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" }]),
      s(4, "キュービックプラザ新横浜", "駅ビル", "新横浜",
        "新横浜駅直結のショッピング施設。飲食・土産も充実",
        "新横浜駅直結の商業施設。ファッション・飲食・土産コーナーが揃い、新幹線の出発前の時間調整に使いやすい。フードコートもあり、軽食を取りながら待てる。B1〜8Fの各フロアに幅広い業態が入っている。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 直結" },
          { k: "営業時間", v: "10:00〜21:00" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(5, "日産スタジアム（横浜国際総合競技場）", "スタジアム", "新横浜",
        "収容7.2万人の国内最大スタジアム。イベント時は周辺が賑わう",
        "収容72,327人を誇る国内最大のサッカー・陸上競技場。Jリーグ・代表戦・コンサートなどが開催される。試合やライブがない日は外観の見学と新横浜公園の散策が主。周辺にはグルメ・土産店が集まり、ライブ後の食事にも使いやすいエリアが形成されている。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 徒歩12分 / 小机駅 徒歩10分" },
          { k: "料金", v: "イベントによる（外観見学は無料）" }])],
    sideArticles: [
      side("横浜アリーナ周辺5選", "new-yokohama-arena-spots", I.mm_blue),
      side("横浜駅周辺で時間つぶし5選", "new-yokohama-station-bored", I.mm_blue)],
    quote: "新横浜はラーメン博物館を軸に、スケートリンクや公園と組み合わせれば半日楽しめる。",
    quoteCite: author,
    closing: "新幹線前後の時間は「ラーメン博物館→キュービックプラザで土産」が最も効率的。時間があれば新横浜公園まで足を延ばすと気分転換になる。",
  },

  // NG-15 ─────────────────────────────────────────────────
  "new-yokohama-arena-spots": {
    id: "new-yokohama-arena-spots",
    no: "NG-15", articleType: "guide", kicker: "YOKOHAMA ARENA SPOTS",
    title: "横浜アリーナ周辺5選。ライブ前後に使えるスポット",
    titleHTML: "横浜アリーナ<br>周辺5選。",
    subtitle: "ラーメン博物館、スケートリンク、新横浜公園。ライブの待ち時間を快適に過ごす方法",
    lede: "横浜アリーナは新横浜駅から徒歩10分圏内に飲食・体験施設が揃う。開演2〜3時間前に到着しても時間を持て余さないのが、このエリアの強み。",
    date, reading: "約4分", author,
    heroImage: I.shin_yoko,
    ranking: [
      s(1, "新横浜ラーメン博物館", "フードテーマパーク", "新横浜",
        "ライブ前の腹ごしらえに最適。アリーナから徒歩5分",
        "横浜アリーナから徒歩5分の立地にある全国区のラーメンテーマパーク。ライブ前の食事場所として定番で、早い時間から賑わう。複数店舗から選べるので好みに合わせやすい。入場料380円で昭和レトロな空間ごと楽しめる。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 徒歩2分" },
          { k: "入場料", v: "380円" },
          { k: "雨の日", v: "◎" }]),
      s(2, "新横浜公園・鶴見川沿い遊歩道", "公園・遊歩道", "新横浜",
        "アリーナ横の公園。開演前の散歩・飲食にちょうどいい",
        "横浜アリーナに隣接する広大な公園。鶴見川沿いの遊歩道が整備されており、ライブ前に体をほぐす散歩コースとして使いやすい。入場無料で、自分で持ち込んだ飲食物を楽しむ場所としても開放されている。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 徒歩10分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" }]),
      s(3, "キュービックプラザ新横浜", "駅ビル", "新横浜",
        "駅直結でグッズ袋の一時保管・土産購入にも対応",
        "新横浜駅直結の商業ビル。ライブグッズを持ちながらでも移動しやすく、ファッション・コンビニ・飲食が揃う。ライブ後の食事スポットとして飲食フロアを利用する人が多い。終演後は混雑するため、少し時間を置いてから利用するのがスムーズ。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 直結" },
          { k: "営業時間", v: "10:00〜21:00" },
          { k: "雨の日", v: "◎" }]),
      s(4, "新横浜スケートセンター", "屋内スケートリンク", "新横浜",
        "ライブ前日や翌日に体を動かしたいときに",
        "通年営業の屋内アイススケートリンク。横浜アリーナから徒歩10分圏内にある。ライブ遠征で前乗りした際や、翌日観光前の時間つぶしに向いている。体を動かしてからライブに向かうと気分が高まる。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 徒歩10分" },
          { k: "料金", v: "大人1,500円程度" },
          { k: "雨の日", v: "◎" }]),
      s(5, "新横浜近辺のカフェ・コワーキング", "カフェ", "新横浜",
        "遠方から来た場合の休憩・荷物まとめに使えるカフェ",
        "新横浜駅周辺にはチェーン系カフェ（スタバ・ドトール・タリーズ等）が複数ある。開場待ちや終演後の時間調整に使いやすく、荷物をまとめる場所としても活用できる。新横浜は新幹線駅でもあるため、全国各地からのライブ参加者が集まり、駅周辺の飲食店は夜遅くまで営業している。",
        [I.shin_yoko],
        [
          { k: "最寄り駅", v: "新横浜駅 周辺" },
          { k: "料金", v: "500〜1,000円程度" },
          { k: "雨の日", v: "◎" }])],
    sideArticles: [
      side("新横浜で時間つぶし5選", "new-shin-yokohama-bored", I.mm_blue),
      side("横浜駅周辺で時間つぶし5選", "new-yokohama-station-bored", I.mm_blue)],
    quote: "横浜アリーナ周辺は新横浜駅から徒歩圏内に飲食・体験施設が揃い、前後の時間を使いやすい。",
    quoteCite: author,
    closing: "開演2〜3時間前に到着してラーメン博物館→公園散策→キュービックプラザで土産というルートが定番。終演後は混雑するので、電車に乗るタイミングを少しずらすのがコツ。",
  },

  // NG-16 ─────────────────────────────────────────────────
  "new-kamakura-komachi": {
    id: "new-kamakura-komachi",
    no: "NG-16", articleType: "guide", kicker: "KAMAKURA KOMACHI",
    title: "鎌倉小町通り・鶴岡八幡宮周辺5選。鎌倉観光の王道ルート",
    titleHTML: "鎌倉<br>小町通り5選。",
    subtitle: "小町通りの食べ歩き、鶴岡八幡宮の参拝、若宮大路の歩き方",
    lede: "鎌倉駅から鶴岡八幡宮まで続く小町通りは、食べ歩きと参拝が自然につながるコース。週末は混雑するが、歩けば歩くだけ発見がある鎌倉観光の核心エリア。",
    date, reading: "約4分", author,
    heroImage: I.hachimangu,
    ranking: [
      s(1, "小町通り", "食べ歩き・ショッピング街", "鎌倉駅東口",
        "鎌倉駅から鶴岡八幡宮まで続く食べ歩きストリート",
        "鎌倉駅東口から鶴岡八幡宮まで約400mの参道商店街。コロッケ・クレープ・抹茶スイーツ・鎌倉彫の土産など、食べ歩きと買い物が同時に楽しめる。週末は混雑するため、早朝〜10時頃に訪れると比較的ゆっくり歩ける。雨の日も軒下・屋内店舗が多く歩きやすい。",
        [I.hachimangu],
        [
          { k: "最寄り駅", v: "鎌倉駅東口 徒歩1分" },
          { k: "料金", v: "無料（飲食・購入別途）" },
          { k: "雨の日", v: "△ 屋根あり店舗多数" }]),
      s(2, "鶴岡八幡宮", "神社・歴史", "雪ノ下",
        "鎌倉の総鎮守。段葛・本殿・ぼたん園と見どころ多数",
        "源頼朝が整備した鎌倉の総鎮守。本殿への参道「段葛」は春は桜、夏は緑が美しい。本殿のほか、境内には鶴岡八幡宮ミュージアム・ぼたん苑・池があり、ゆっくり回ると1〜1.5時間かかる。初詣は全国屈指の参拝者数を誇る。",
        [I.hachimangu],
        [
          { k: "最寄り駅", v: "鎌倉駅東口 徒歩10分" },
          { k: "料金", v: "境内無料（ぼたん苑・宝物殿は別途）" },
          { k: "雨の日", v: "△ 屋外メイン" }]),
      s(3, "鎌倉国宝館", "博物館", "雪ノ下",
        "鶴岡八幡宮境内にある博物館。国宝・重文の仏像が充実",
        "鶴岡八幡宮境内に位置する博物館。鎌倉市内の寺社から集めた国宝・重要文化財の仏像・絵画・工芸品を展示する。雨の日でも屋内でゆっくり見学でき、鶴岡八幡宮参拝と合わせてまわると充実する。入館料は一般500円程度。",
        [I.hachimangu],
        [
          { k: "最寄り駅", v: "鎌倉駅東口 徒歩12分（鶴岡八幡宮境内）" },
          { k: "入館料", v: "一般700円" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(4, "若宮大路", "参道・散策路", "鎌倉駅周辺",
        "鎌倉駅から海へ続く参道。3段構造の「段葛」が映える",
        "鎌倉駅から由比ヶ浜まで続く約1.8kmの大路。中央に盛り土された参道「段葛」が残る歴史的な道で、鶴岡八幡宮の一の鳥居から三の鳥居まで歩ける。桜の季節は特に美しく、散策しながら歴史的景観を感じられる。鎌倉駅から由比ヶ浜まで歩いて約20分。",
        [I.hachimangu],
        [
          { k: "最寄り駅", v: "鎌倉駅 徒歩1分（起点）" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" }]),
      s(5, "鎌倉幕府跡（鎌倉歴史文化交流館）", "歴史スポット", "御成町",
        "頼朝の幕府があった場所。発掘品と歴史を展示する施設",
        "鎌倉幕府の政庁「大倉幕府」があったとされる場所の近隣に位置する市の文化施設。鎌倉の発掘調査で出土した中世遺物や歴史資料を展示する。入館無料で気軽に入れる。小町通りから徒歩10分ほどで、観光の合間に立ち寄れる。",
        [I.hachimangu],
        [
          { k: "最寄り駅", v: "鎌倉駅 徒歩10分" },
          { k: "入館料", v: "無料" },
          { k: "雨の日", v: "◎" }])],
    sideArticles: [
      side("長谷・由比ヶ浜デート5選", "new-hase-yuigahama-date", I.hasedera),
      side("鎌倉雨の日5選", "new-kamakura-rainy", I.kenchoji)],
    quote: "鎌倉駅から鶴岡八幡宮まで、小町通りで食べ歩きしながら歩くのが鎌倉観光の王道。",
    quoteCite: author,
    closing: "鎌倉駅→小町通り（食べ歩き）→若宮大路→鶴岡八幡宮→鎌倉国宝館という半日コース。帰りに小町通りで土産を買って戻るのが定番の流れ。",
  },

  // NG-17 ─────────────────────────────────────────────────
  "new-hase-yuigahama-date": {
    id: "new-hase-yuigahama-date",
    no: "NG-17", articleType: "guide", kicker: "HASE YUIGAHAMA DATE",
    title: "長谷・由比ヶ浜デート5選。大仏と海を一日で楽しむ鎌倉コース",
    titleHTML: "長谷・由比ヶ浜<br>デート5選。",
    subtitle: "高徳院（鎌倉大仏）、長谷寺、由比ヶ浜。江ノ電で巡る海と寺のデートルート",
    lede: "江ノ電で長谷駅に降りれば、大仏・長谷寺・由比ヶ浜が徒歩圏内に揃う。鎌倉の中でも「海と寺」が最もコンパクトに体験できるエリアで、半日で十分楽しめる。",
    date, reading: "約5分", author,
    heroImage: I.daibutsu,
    ranking: [
      s(1, "高徳院（鎌倉大仏）", "史跡・仏像", "長谷",
        "高さ11.3mの国宝銅造阿弥陀如来坐像。胎内拝観も可",
        "鎌倉を代表する観光地。高さ11.3m・重さ約121tの国宝の大仏は1252年建立。境内の拝観料は300円で、大仏の胎内に入る胎内拝観（別途50円）も人気。長谷駅から徒歩10分のアクセスで、江ノ電利用のデートコースにそのまま組み込める。",
        [I.daibutsu],
        [
          { k: "最寄り駅", v: "江ノ電 長谷駅 徒歩10分" },
          { k: "拝観料", v: "300円（胎内拝観+50円）" },
          { k: "雨の日", v: "△ 屋外メインだが大仏自体は見られる" }]),
      s(2, "長谷寺", "寺院・庭園", "長谷",
        "見晴台からの海の眺め。アジサイの季節は特に美しい",
        "坂東三十三観音第四番札所。本尊の十一面観音菩薩立像（高さ約9.18m）は木造では国内最大級とされる。境内の見晴台からは由比ヶ浜・相模湾を見渡せ、6月のアジサイ・秋の紅葉が特に美しい。高徳院（大仏）と同じ長谷エリアにあり、セットで回れる。",
        [I.hasedera],
        [
          { k: "最寄り駅", v: "江ノ電 長谷駅 徒歩5分" },
          { k: "拝観料", v: "400円" },
          { k: "雨の日", v: "△ 堂内は可、庭は雨天も美しい" }]),
      s(3, "由比ヶ浜海岸", "海水浴場・散策", "由比ヶ浜",
        "夏は海水浴、オフシーズンは散歩。鎌倉市民の海",
        "鎌倉の中心部からアクセスしやすい海岸。夏は海水浴客で賑わうが、オフシーズン（秋〜春）は人も少なく、波の音を聞きながらゆっくり歩ける。長谷寺から徒歩10分圏内で、散策コースとして自然につながる。夕暮れ時のシルエットが美しい。",
        [I.yuigahama],
        [
          { k: "最寄り駅", v: "江ノ電 由比ヶ浜駅 徒歩3分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕ 屋外" }]),
      s(4, "鎌倉文学館", "文学館・庭園", "長谷",
        "旧前田侯爵別邸を活用した文学館。バラ庭園が有名",
        "旧前田侯爵家の別邸を改装した文学館。川端康成・里見弴など鎌倉ゆかりの文人の資料を展示する。5月と10月の「バラまつり」期間中はバラ庭園が開放され、デートスポットとして人気。由比ヶ浜エリアにあり、長谷寺から徒歩10分程度。",
        [I.yuigahama],
        [
          { k: "最寄り駅", v: "江ノ電 由比ヶ浜駅 徒歩10分" },
          { k: "入館料", v: "500円" },
          { k: "雨の日", v: "◎ 屋内展示あり" }]),
      s(5, "江ノ電 長谷駅周辺カフェ", "カフェ", "長谷",
        "長谷駅周辺には隠れ家系カフェが点在。散策の休憩に",
        "江ノ電長谷駅周辺には鎌倉らしいこじんまりとしたカフェや甘味処が点在する。大仏・長谷寺の観光を終えた後の休憩スポットとして最適で、地元の食材を使ったスイーツや抹茶を提供する店が多い。由比ヶ浜へ向かう前に立ち寄ると、散策の気分転換になる。",
        [I.hasedera],
        [
          { k: "最寄り駅", v: "江ノ電 長谷駅 周辺" },
          { k: "料金", v: "700〜1,500円程度" },
          { k: "雨の日", v: "◎" }])],
    sideArticles: [
      side("鎌倉小町通り・八幡宮5選", "new-kamakura-komachi", I.hachimangu),
      side("江ノ島夕暮れデート5選", "new-enoshima-evening-date", I.enoshima)],
    quote: "大仏→長谷寺→由比ヶ浜という長谷エリアの定番コースは、半日でテンポよく回れる鎌倉デートの王道。",
    quoteCite: author,
    closing: "鎌倉駅から江ノ電で長谷へ。大仏→長谷寺→鎌倉文学館→由比ヶ浜というルートが自然な動線。夕暮れに由比ヶ浜で波を見て、江ノ電で帰途につく。",
  },

  // NG-18 ─────────────────────────────────────────────────
  "new-enoshima-evening-date": {
    id: "new-enoshima-evening-date",
    no: "NG-18", articleType: "guide", kicker: "ENOSHIMA EVENING DATE",
    title: "江ノ島夕暮れデート5選。サンセットと夜景が見えるスポット",
    titleHTML: "江ノ島<br>夕暮れデート5選。",
    subtitle: "シーキャンドル、稚児ヶ淵、岩屋洞窟。湘南の島で迎える夕暮れ",
    lede: "江ノ島は午後から入れば夕暮れまでの時間が自然にコースになる。島を南西に歩くほど人が少なくなり、稚児ヶ淵では富士山に沈む夕日が待っている。",
    date, reading: "約5分", author,
    heroImage: I.enoshima,
    ranking: [
      s(1, "江ノ島シーキャンドル（江の島展望灯台）", "展望台", "江ノ島",
        "高さ59.8mの展望灯台。湘南の海と夕焼けを360度見渡せる",
        "江ノ島頂上部に建つ高さ59.8mの展望灯台。展望フロアからは富士山・伊豆半島・相模湾・湘南海岸が一望でき、夕暮れ時は特に美しい。灯台は日没後もライトアップされ、夜景スポットとしても人気が高い。展望フロア料金は500円程度。",
        [I.enoshima],
        [
          { k: "最寄り駅", v: "小田急 片瀬江ノ島駅 徒歩20分（島内）" },
          { k: "料金", v: "展望料金500円（別途入園料）" },
          { k: "おすすめ時間", v: "日没1時間前〜日没後" }]),
      s(2, "稚児ヶ淵", "岩場・展望", "江ノ島 岩屋",
        "江ノ島西側の岩場。夕日が海に沈む瞬間が見られる",
        "江ノ島の西端にある岩場。相模湾に向かって広がる岩棚から、富士山に沈む夕日が見られることで知られる。波の音と共に過ごす夕暮れはデートにも向いている。岩場への道は岩屋洞窟と同じ方向で、帰りは江ノ島エスカーを使って戻ることができる。",
        [I.enobch],
        [
          { k: "最寄り駅", v: "片瀬江ノ島駅 徒歩30分（島内）" },
          { k: "料金", v: "無料" },
          { k: "おすすめ時間", v: "夕方（日没時間に合わせて）" }]),
      s(3, "江ノ島岩屋洞窟", "洞窟・観光", "江ノ島 岩屋",
        "波食洞窟を歩いて探検。全長152mの自然洞窟",
        "江ノ島の最奥にある波食洞窟。奥行き152m・25mの2洞からなり、ロウソクを持って内部を歩く探検気分が楽しめる。稚児ヶ淵のすぐそばにあり、夕暮れ前に立ち寄るのに適している。波が高い日は閉鎖されることがあるので事前確認が必要。",
        [I.enobch],
        [
          { k: "最寄り駅", v: "片瀬江ノ島駅 徒歩35分（島内）" },
          { k: "料金", v: "500円" },
          { k: "雨の日", v: "◎（屋内洞窟）" }]),
      s(4, "江ノ島弁天仲見世通り", "参道・食べ歩き", "江ノ島",
        "島の入口から続く参道。たこせん・しらす丼の食べ歩き",
        "江ノ島大橋を渡ってすぐの参道商店街。しらす料理・たこせんべい・生しらす丼など江ノ島名物の食べ歩きが楽しめる。帰りにここでお土産と食事を済ませると効率的。夕方以降は混雑が落ち着くため、夕暮れデートの帰り道に立ち寄りやすい。",
        [I.enobch],
        [
          { k: "最寄り駅", v: "片瀬江ノ島駅 徒歩5分（入口）" },
          { k: "料金", v: "食べ歩き300〜1,000円程度" }]),
      s(5, "湘南港（ヨットハーバー）", "港・散策", "江ノ島",
        "江ノ島西側の港。ヨットが並ぶ夕景がおしゃれ",
        "江ノ島の南西に位置するマリーナ。ヨットや釣り船が停泊する港の景色が夕日に映える。シーキャンドルへ上る前後の散策コースに組み込みやすく、人も少なく静かに過ごせる場所。周辺にはカフェも点在する。",
        [I.enoshima],
        [
          { k: "最寄り駅", v: "片瀬江ノ島駅 徒歩20分" },
          { k: "料金", v: "無料（周辺カフェ利用は別途）" },
          { k: "おすすめ時間", v: "夕方" }])],
    sideArticles: [
      side("長谷・由比ヶ浜デート5選", "new-hase-yuigahama-date", I.hasedera),
      side("茅ヶ崎ビーチ5選", "new-chigasaki-beach", I.chigasaki)],
    quote: "江ノ島のシーキャンドルから見る夕日は、湘南で迎える夕暮れの中でも特別な景色。",
    quoteCite: author,
    closing: "弁天仲見世通り→江ノ島神社→シーキャンドル（夕日）→稚児ヶ淵→岩屋洞窟というルートで、島内を3〜4時間かけて一周できる。帰りの弁天橋からの夜景も見逃せない。",
  },

  // NG-19 ─────────────────────────────────────────────────
  "new-kamakura-rainy": {
    id: "new-kamakura-rainy",
    no: "NG-19", articleType: "guide", kicker: "KAMAKURA RAINY DAY",
    title: "鎌倉雨の日5選。雨でも楽しめる屋内スポットと濡れても美しい庭",
    titleHTML: "鎌倉<br>雨の日5選。",
    subtitle: "鎌倉国宝館、建長寺方丈、円覚寺。雨がむしろ似合う鎌倉の寺社と博物館",
    lede: "雨の鎌倉は観光客が減り、濡れた苔と石畳が静かな禅の空気感を際立てる。晴れの日より混まず、寺社本来の空気に近づける日でもある。",
    date, reading: "約4分", author,
    heroImage: I.kenchoji,
    ranking: [
      s(1, "鎌倉国宝館", "博物館", "雪ノ下",
        "鶴岡八幡宮境内の屋内博物館。国宝・重文の仏像が充実",
        "鶴岡八幡宮境内にある博物館で、雨の日でも快適に見学できる。鎌倉市内の寺社から集めた国宝・重要文化財の仏像・絵画・工芸品が充実。国宝を間近で見られる機会として貴重で、雨の日に特にオススメできるスポット。入館料700円。",
        [I.kenchoji],
        [
          { k: "最寄り駅", v: "鎌倉駅 徒歩12分" },
          { k: "入館料", v: "700円" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(2, "長谷寺（雨天）", "寺院", "長谷",
        "雨の日の長谷寺は濡れた石段と緑が美しい。混雑も少ない",
        "雨の日の長谷寺は、晴れの日とは違う静けさと美しさがある。濡れた苔・石畳・青もみじが境内に広がり、観光客も少なくなるため落ち着いて参拝できる。本堂は屋内で、見晴台から見える雨の相模湾も独特の趣がある。アジサイの季節は雨の日でも美しい。",
        [I.hasedera],
        [
          { k: "最寄り駅", v: "江ノ電 長谷駅 徒歩5分" },
          { k: "拝観料", v: "400円" },
          { k: "雨の日", v: "○ 雨天の庭も見どころ" }]),
      s(3, "円覚寺", "禅寺", "北鎌倉",
        "北鎌倉の名刹。雨に濡れた山門と境内の雰囲気が格別",
        "鎌倉五山第二位の禅宗寺院。JR北鎌倉駅から徒歩1分という好立地にある。広大な境内は複数の堂宇からなり、雨の日はほとんど人がいないため静かに参拝できる。国宝の洪鐘（おおがね）や舎利殿は必見。有料エリアへの入場は500円。",
        [I.kenchoji],
        [
          { k: "最寄り駅", v: "JR北鎌倉駅 徒歩1分" },
          { k: "拝観料", v: "500円" },
          { k: "雨の日", v: "○ 濡れた境内が趣深い" }]),
      s(4, "建長寺（方丈・庭園）", "禅寺", "山ノ内",
        "鎌倉五山第一位。方丈庭園は雨の日こそ見ごたえあり",
        "鎌倉五山第一位の禅宗寺院。北鎌倉駅から徒歩15分で、山号・天源山の深い自然に囲まれる。方丈（本堂）裏の庭園は枯山水で、雨の日は砂紋に雨粒が落ちる様子が幻想的。天園ハイキングコースの入口でもあるが、雨の日はハイキングを避けて庭園見学に集中するのが安全。",
        [I.kenchoji],
        [
          { k: "最寄り駅", v: "JR北鎌倉駅 徒歩15分 / 鎌倉駅 徒歩20分" },
          { k: "拝観料", v: "500円" },
          { k: "雨の日", v: "○" }]),
      s(5, "鎌倉歴史文化交流館", "博物館", "御成町",
        "旧川喜多邸の建物を活用。鎌倉の発掘品と文化財を展示",
        "鎌倉市が整備した歴史・文化の発信施設。旧川喜多邸（映画プロデューサー・川喜多長政の邸宅）の建物を活用し、鎌倉の遺跡・発掘品・武家文化に関する展示を行う。入館無料で気軽に立ち寄れる。鎌倉駅から徒歩10分で、雨宿りを兼ねて訪れやすい。",
        [I.kenchoji],
        [
          { k: "最寄り駅", v: "鎌倉駅 徒歩10分" },
          { k: "入館料", v: "無料" },
          { k: "雨の日", v: "◎" }])],
    sideArticles: [
      side("鎌倉小町通り・八幡宮5選", "new-kamakura-komachi", I.hachimangu),
      side("長谷・由比ヶ浜デート5選", "new-hase-yuigahama-date", I.daibutsu)],
    quote: "雨の鎌倉は、観光客が減り、濡れた苔と石畳が静かな禅の空気感を際立てる。",
    quoteCite: author,
    closing: "北鎌倉駅→円覚寺→建長寺→鎌倉駅→鎌倉国宝館→長谷寺という一日コース。雨の日こそ寺社の静けさを楽しめる鎌倉の本質がある。",
  },

  // NG-20 ─────────────────────────────────────────────────
  "new-kawasaki-rainy-date": {
    id: "new-kawasaki-rainy-date",
    no: "NG-20", articleType: "guide", kicker: "KAWASAKI RAINY DATE",
    title: "川崎雨の日デート5選。ラゾーナ川崎から映画まで濡れずに楽しむ",
    titleHTML: "川崎<br>雨の日デート5選。",
    subtitle: "ラゾーナ川崎、川崎市民ミュージアム、チネチッタ。雨でも快適な川崎の屋内スポット",
    lede: "川崎駅はラゾーナ川崎プラザが駅直結で、雨の日に最も強い横浜エリアの駅のひとつ。ショッピング・映画・グルメが一棟で完結するうえ、チネチッタや藤子ミュージアムとの組み合わせで一日設計できる。",
    date, reading: "約4分", author,
    heroImage: I.lazona,
    ranking: [
      s(1, "ラゾーナ川崎プラザ", "ショッピングモール", "川崎駅西口",
        "JR川崎駅直結の大型モール。200店舗以上で雨の日に最強",
        "JR川崎駅西口に直結する延床面積約18万㎡の大型ショッピングモール。ファッション・雑貨・飲食・映画（ユナイテッド・シネマ）が一棟に集まり、一日中雨に濡れずに過ごせる。週末は混雑するため、昼前到着がおすすめ。フードコートやレストランフロアも充実している。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "JR川崎駅西口 直結" },
          { k: "営業時間", v: "10:00〜21:00（飲食は〜23:00）" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(2, "ユナイテッド・シネマ川崎（ラゾーナ内）", "映画館", "川崎駅西口",
        "ラゾーナ川崎3Fの映画館。IMAX・ドルビーも完備",
        "ラゾーナ川崎3Fに入る映画館。IMAXシアター・ドルビーシネマを備えた本格的な設備で、最新作・話題作を上映している。ショッピングの合間に映画を組み込みやすく、ラゾーナ内で食事→映画という流れが定番。駐車場も広く、車でも訪れやすい。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "JR川崎駅西口 直結" },
          { k: "料金", v: "一般2,000円（作品による）" },
          { k: "雨の日", v: "◎" }]),
      s(3, "川崎チネチッタ", "映画館・エンタメ街", "川崎駅東口",
        "川崎駅東口のシネマ複合エリア。La Cittadella内",
        "JR川崎駅東口から徒歩5分の「La Cittadella」内にあるシネマコンプレックス。北イタリアの広場を模した内装が特徴的で、映画鑑賞後にショッピング・飲食を楽しめる。音楽ライブ・イベントも開催されており、映画以外の目的でも訪れる価値がある。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "JR川崎駅東口 徒歩5分" },
          { k: "料金", v: "一般2,000円（作品による）" },
          { k: "雨の日", v: "◎" }]),
      s(4, "川崎市藤子・F・不二雄ミュージアム", "博物館", "登戸（川崎市多摩区）",
        "ドラえもんの原作者・藤子F不二雄の作品世界を体験",
        "「ドラえもん」「パーマン」など藤子・F・不二雄作品の世界を体験できる美術館。完全予約制で、川崎駅から路線バスで約20分。雨の日も屋内展示で問題なく、子どもから大人まで楽しめる。チケットは事前購入が必須で、人気のため早めの予約が必要。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "JR登戸駅 バス5分 / JR川崎駅 バス約20分" },
          { k: "入館料", v: "大人1,000円（要事前予約）" },
          { k: "雨の日", v: "◎ 完全屋内" }]),
      s(5, "川崎市市民ミュージアム（仮移転中）", "博物館・美術館", "川崎",
        "考古・歴史・美術・マンガ文化を扱う総合博物館",
        "川崎市の総合博物館。2019年台風で被災し現在は市内で仮移転展示を行っているが、考古・歴史・映像・漫画文化に関する展示は雨の日の文化体験として充実している。最新の展示状況は公式サイトで確認のこと。入館料は展覧会による。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "仮移転先による（公式要確認）" },
          { k: "入館料", v: "展覧会による" },
          { k: "雨の日", v: "◎" }])],
    sideArticles: [
      side("横浜駅雨の日5選", "new-yokohama-station-rainy", I.mm_blue),
      side("武蔵小杉ファミリー5選", "new-musashikosugi-family", I.lazona)],
    quote: "川崎はラゾーナを軸に、映画・ショッピング・グルメが雨の日でも完結する都市型エンタメエリア。",
    quoteCite: author,
    closing: "川崎駅西口直結のラゾーナで一日完結するプランが最も楽。映画を予約して→ショッピング→映画→ディナーというシンプルな動線がおすすめ。",
  },

  // NG-21 ─────────────────────────────────────────────────
  "new-musashikosugi-family": {
    id: "new-musashikosugi-family",
    no: "NG-21", articleType: "guide", kicker: "MUSASHIKOSUGI FAMILY",
    title: "武蔵小杉ファミリースポット5選。子連れで一日過ごせる場所",
    titleHTML: "武蔵小杉<br>ファミリー5選。",
    subtitle: "ららテラス・グランツリー・等々力緑地。タワマン街の意外な子育て環境",
    lede: "武蔵小杉はタワーマンション街として知られるが、等々力緑地・多摩川河川敷・駅直結モールが揃う子連れに優しいエリアでもある。晴れの日は緑地、雨の日はモールと使い分けやすい。",
    date, reading: "約4分", author,
    heroImage: I.lazona,
    ranking: [
      s(1, "等々力緑地", "大型公園", "武蔵小杉",
        "川崎市最大の都市公園。野球場・プールと子どもが遊べる広場",
        "川崎市最大の総合公園。野球場・陸上競技場・プール・テニスコートに加え、子ども向けの遊具広場も整備されている。武蔵小杉駅から徒歩15〜20分で、スポーツ観戦（Jリーグ川崎フロンターレのホームスタジアム）や運動のためにも多くの人が訪れる。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "東急武蔵小杉駅 徒歩15分" },
          { k: "料金", v: "無料（施設利用は別途）" },
          { k: "雨の日", v: "✕ 屋外メイン" }]),
      s(2, "ららテラス武蔵小杉", "ショッピングモール", "武蔵小杉",
        "武蔵小杉駅直結のショッピング施設。子ども服・飲食充実",
        "武蔵小杉駅東口に直結する商業施設。子ども服・ベビー用品・飲食フロアが揃い、ファミリー利用に向いている。雨の日でもストレスなくショッピングができ、フードコートも広い。同エリアには「グランツリー武蔵小杉」も隣接しており、両方合わせると一日過ごせる。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "武蔵小杉駅 直結" },
          { k: "営業時間", v: "10:00〜21:00" },
          { k: "雨の日", v: "◎" }]),
      s(3, "グランツリー武蔵小杉", "ショッピングモール", "武蔵小杉",
        "子ども向けの体験型スポットが充実した大型モール",
        "武蔵小杉駅から徒歩5分の大型商業施設。地下〜5Fに多様な店舗が入り、子ども向けの遊び場「キドキド」やフードコートが家族連れに人気。屋外広場でのイベントも定期開催。ゆっくり回ると半日〜一日過ごせる規模感。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "武蔵小杉駅 徒歩5分" },
          { k: "営業時間", v: "10:00〜21:00" },
          { k: "雨の日", v: "◎" }]),
      s(4, "中原市民館・中原図書館", "公共施設", "武蔵小杉",
        "子連れで立ち寄れる公共施設。図書館の絵本コーナーが広い",
        "武蔵小杉駅から徒歩10分の複合公共施設。図書館の児童書・絵本コーナーは広く設計されており、小さな子どもと一緒に過ごしやすい。雨の日の時間つぶし・読み聞かせの場として活用できる。入館無料。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "武蔵小杉駅 徒歩10分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "◎" }]),
      s(5, "丸子橋・多摩川河川敷", "河川敷・散策", "武蔵小杉",
        "多摩川沿いの広い河川敷。バーベキュー・サイクリングにも",
        "武蔵小杉から徒歩20分、多摩川河川敷への入口。広い芝生の河川敷でピクニック・凧揚げ・サイクリングが楽しめる。晴れた日は富士山も見え、家族で半日過ごせる開放的な場所。整備された遊歩道が二子玉川まで続いており、自転車でのんびり走れる。",
        [I.lazona],
        [
          { k: "最寄り駅", v: "東急武蔵小杉駅 徒歩20分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕" }])],
    sideArticles: [
      side("川崎雨の日デート5選", "new-kawasaki-rainy-date", I.lazona),
      side("たまプラーザ・あざみ野5選", "new-tamaplaza-azamino", I.mm_blue)],
    quote: "武蔵小杉は等々力緑地とグランツリーを組み合わせると、子連れでも一日余裕で過ごせる。",
    quoteCite: author,
    closing: "晴れた日は等々力緑地・多摩川河川敷、雨の日はグランツリー・ららテラスという使い分けが武蔵小杉ファミリーの定番パターン。",
  },

  // NG-22 ─────────────────────────────────────────────────
  "new-tamaplaza-azamino": {
    id: "new-tamaplaza-azamino",
    no: "NG-22", articleType: "guide", kicker: "TAMAPLAZA AZAMINO",
    title: "たまプラーザ・あざみ野5選。子連れ・ファミリーに優しい郊外エリア",
    titleHTML: "たまプラーザ<br>ファミリー5選。",
    subtitle: "たまプラーザテラス、こどもの国、横浜市こども植物園。横浜北部のファミリー定番",
    lede: "東急田園都市線のたまプラーザ駅周辺は、駅直結モール・こどもの国・緑道が半径5km以内に集まる横浜北部のファミリーエリア。都心から田園都市線一本でアクセスできるのも便利。",
    date, reading: "約4分", author,
    heroImage: I.tamapla,
    ranking: [
      s(1, "たまプラーザテラス", "ショッピングモール", "たまプラーザ",
        "東急たまプラーザ駅直結の大型モール。ファミリー向け施設充実",
        "東急田園都市線たまプラーザ駅直結の大型商業施設。ファッション・飲食・スーパー・子育て施設が揃い、地元ファミリーの日常使いから観光利用まで幅広い。緑の多い開放的な造りが特徴で、週末は近隣の家族連れで賑わう。",
        [I.tamapla],
        [
          { k: "最寄り駅", v: "東急田園都市線 たまプラーザ駅 直結" },
          { k: "営業時間", v: "10:00〜21:00（飲食は〜22:00）" },
          { k: "雨の日", v: "◎" }]),
      s(2, "こどもの国（横浜市）", "子ども向けテーマパーク", "恩田・成瀬",
        "東京・横浜最大級の子ども向け施設。牧場・プール・遊具が揃う",
        "東京・神奈川にまたがる広大な公園型施設。牧場（乳搾り体験）・プール（夏季）・サイクリングコース・遊具広場など子ども向けの体験が充実。こどもの国線（東急）でアクセスでき、たまプラーザから乗り換え1回で行ける。一日中遊べるボリューム。",
        [I.tamapla],
        [
          { k: "最寄り駅", v: "東急こどもの国線 こどもの国駅 徒歩3分" },
          { k: "入場料", v: "大人800円・子ども500円" },
          { k: "雨の日", v: "△（一部屋内施設あり）" }]),
      s(3, "横浜市こども植物園", "植物園・公園", "旭区（二俣川）",
        "子どもが植物に触れられる体験型植物園。入園無料",
        "横浜市が運営する体験型植物園。バラ園・野草コーナー・温室があり、子どもが植物に直接触れる体験プログラムも定期開催。入園無料で気軽に立ち寄れる。二俣川駅から徒歩圏内で、あざみ野からもアクセスしやすい。",
        [I.tamapla],
        [
          { k: "最寄り駅", v: "相鉄 二俣川駅 徒歩15分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "△ 温室は可" }]),
      s(4, "あざみ野ガーデンズ", "ショッピングモール", "あざみ野",
        "東急あざみ野駅直結のショッピング施設",
        "東急田園都市線あざみ野駅直結の商業施設。スーパー・飲食・日用品が揃い、地元ファミリーの日常使いの場。たまプラーザと合わせて回ると充実した買い物ができる。駅直結で雨でも使いやすい。",
        [I.tamapla],
        [
          { k: "最寄り駅", v: "東急田園都市線 あざみ野駅 直結" },
          { k: "営業時間", v: "10:00〜21:00" },
          { k: "雨の日", v: "◎" }]),
      s(5, "港北ニュータウン・都筑区公園群", "公園", "都筑区",
        "たまプラーザ〜港北ニュータウン間の公園緑道。ファミリー散策に",
        "東急田園都市線沿線と市営地下鉄グリーンライン沿いに広がる都筑区の緑道・公園群。たまプラーザからセンター北・南へ延びるグリーンベルトは、子どもが走り回れる芝生広場が点在する。週末に地元家族がのんびり過ごす場所として定番化している。",
        [I.tamapla],
        [
          { k: "最寄り駅", v: "市営地下鉄 センター北・センター南駅周辺" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕" }])],
    sideArticles: [
      side("武蔵小杉ファミリー5選", "new-musashikosugi-family", I.lazona),
      side("港北NT・ファミリー5選", "new-kohoku-nt-family", I.mm_blue)],
    quote: "たまプラーザ周辺は公園・こどもの国・ショッピングモールが揃い、子連れで一日遊べる。",
    quoteCite: author,
    closing: "晴れた日はこどもの国・緑道、雨の日はたまプラーザテラスという使い分けが地元ファミリーの定番。都心から田園都市線一本でアクセスできるのも魅力。",
  },

  // NG-23 ─────────────────────────────────────────────────
  "new-hakoneyumoto": {
    id: "new-hakoneyumoto",
    no: "NG-23", articleType: "guide", kicker: "HAKONE YUMOTO",
    title: "箱根湯本5選。日帰り温泉と老舗の味を楽しむ半日コース",
    titleHTML: "箱根湯本<br>5選。",
    subtitle: "箱根湯本温泉、天山湯治郷、湯本商店街。小田原から20分で行ける温泉郷",
    lede: "箱根湯本は新宿から小田急ロマンスカーで85分、小田原から箱根登山電車で20分の温泉地。日帰り入浴を受け付ける施設が複数あり、温泉・食べ歩き・登山電車の乗車を半日でまとめられる。",
    date, reading: "約5分", author,
    heroImage: I.yumoto,
    ranking: [
      s(1, "箱根湯本温泉（日帰り入浴）", "温泉", "箱根湯本",
        "小田原から箱根登山電車20分。日帰り入浴できる旅館が複数",
        "箱根の玄関口に位置する老舗温泉街。日帰り入浴を受け付けている旅館・温泉施設が複数あり、「天山湯治郷」「弥次喜多の湯」「かっぱ天国」などが人気。泉質はpH9.0〜9.5のアルカリ性単純温泉が多く、肌にやさしいと言われる。",
        [I.yumoto],
        [
          { k: "最寄り駅", v: "箱根登山鉄道 箱根湯本駅 徒歩5〜20分（施設による）" },
          { k: "料金", v: "1,000〜2,000円程度（施設による）" },
          { k: "雨の日", v: "◎" }]),
      s(2, "天山湯治郷", "温泉施設", "箱根湯本",
        "箱根を代表する日帰り温泉。露天風呂・サウナ・食事処完備",
        "箱根湯本を代表する日帰り温泉施設。内湯・露天・サウナが揃い、食事処も併設。川のせせらぎが聞こえる静かな環境で、遠方からも訪れる温泉ファンが多い。タオル・館内着レンタルもあり手ぶらで行ける。箱根湯本駅からバスで10分程度。",
        [I.yumoto],
        [
          { k: "最寄り駅", v: "箱根湯本駅 バス10分 / タクシー5分" },
          { k: "料金", v: "大人1,300円（タオル別途）" },
          { k: "雨の日", v: "◎" }]),
      s(3, "箱根湯本商店街", "食べ歩き・土産", "箱根湯本",
        "箱根湯本駅から続く参道商店街。温泉まんじゅう・かまぼこが定番",
        "箱根湯本駅前から早川沿いに広がる商店街。温泉まんじゅう・箱根かまぼこ・七里ガ浜サブレ・黒たまごなど箱根みやげが揃う。温泉に入る前後に立ち寄りやすく、食べ歩きしながら湯本の雰囲気を楽しめる。",
        [I.yumoto],
        [
          { k: "最寄り駅", v: "箱根湯本駅 徒歩1分" },
          { k: "料金", v: "食べ歩き200〜500円程度" }]),
      s(4, "箱根湯本美術館", "美術館", "箱根湯本",
        "早川沿いに建つ日本画・工芸の美術館",
        "早川沿いの自然環境に溶け込むように建てられた美術館。日本画・工芸を中心に展示し、建物と庭の景観も楽しめる。箱根湯本駅から徒歩圏内で、温泉の前後に立ち寄れる。館内はゆったりとした雰囲気で、混雑なく鑑賞できることが多い。",
        [I.yumoto],
        [
          { k: "最寄り駅", v: "箱根湯本駅 徒歩15分" },
          { k: "入館料", v: "展覧会による" },
          { k: "雨の日", v: "◎" }]),
      s(5, "箱根登山電車（湯本→強羅）", "観光鉄道", "箱根湯本→強羅",
        "スイッチバックで山を登る登山電車。車窓のあじさいが有名",
        "日本屈指の急勾配を3回のスイッチバックで登る登山電車。6〜7月の紫陽花の季節は沿線が紫陽花で覆われ、乗るだけで観光になる路線。終点の強羅から早雲山・大涌谷へのルートにもつながる。箱根ロープウェイとの組み合わせで箱根観光の骨格となる。",
        [I.yumoto],
        [
          { k: "最寄り駅", v: "箱根湯本駅 発（所要45分で強羅）" },
          { k: "料金", v: "箱根湯本〜強羅：460円（フリーパス推奨）" }])],
    sideArticles: [
      side("小田原観光5選", "new-odawara", I.odawara),
      side("鎌倉雨の日5選", "new-kamakura-rainy", I.kenchoji)],
    quote: "箱根湯本は新宿から特急ロマンスカーで85分、小田原から20分。日帰り温泉の定番エリア。",
    quoteCite: author,
    closing: "湯本商店街で食べ歩き→天山湯治郷で日帰り温泉→箱根登山電車で強羅へというルートが日帰り箱根の王道。温泉上がりに一杯やるなら湯本駅近くの居酒屋・食事処が充実している。",
  },

  // NG-24 ─────────────────────────────────────────────────
  "new-odawara": {
    id: "new-odawara",
    no: "NG-24", articleType: "guide", kicker: "ODAWARA SIGHTSEEING",
    title: "小田原観光5選。小田原城と老舗グルメを楽しむ半日コース",
    titleHTML: "小田原<br>観光5選。",
    subtitle: "小田原城、かまぼこの里、小田原宿なりわい交流館。新幹線でも立ち寄れる城下町",
    lede: "小田原は東海道新幹線の停車駅で、箱根観光の起点でもある。小田原城・漁港・かまぼこ街道を半日コースにまとめると、箱根と組み合わせた一泊二日旅行のうち一日分として十分な密度になる。",
    date, reading: "約5分", author,
    heroImage: I.odawara,
    ranking: [
      s(1, "小田原城", "史跡・城郭", "小田原",
        "北条氏の居城。天守閣からは相模湾・富士山が見渡せる",
        "戦国時代の北条氏が拠点とした平山城。昭和35年に鉄筋コンクリートで再建された天守閣からは相模湾・富士山・箱根の山々が一望できる。城址公園として整備されており、本丸・二の丸庭園・小田原城歴史見聞館が公開されている。小田原駅から徒歩10分。",
        [I.odawara],
        [
          { k: "最寄り駅", v: "小田原駅 徒歩10分" },
          { k: "入場料", v: "天守閣：大人510円" },
          { k: "雨の日", v: "◎ 天守閣内は屋内" }]),
      s(2, "小田原かまぼこの里（鈴廣）", "食体験・土産", "風祭",
        "かまぼこの老舗・鈴廣の複合施設。製造体験・試食・土産",
        "神奈川の老舗かまぼこメーカー・鈴廣が運営する複合観光施設。かまぼこ・ちくわの手作り体験工房・直売店・レストランが一体になっており、試食しながら土産を選べる。小田急・箱根登山鉄道の風祭駅から徒歩1分。箱根旅行の帰りに立ち寄りやすい。",
        [I.odawara],
        [
          { k: "最寄り駅", v: "箱根登山鉄道 風祭駅 徒歩1分" },
          { k: "体験料", v: "かまぼこ作り：1,500円程度" },
          { k: "雨の日", v: "◎ 屋内" }]),
      s(3, "小田原宿なりわい交流館", "歴史展示", "小田原",
        "東海道小田原宿の歴史を伝える無料展示施設",
        "江戸時代の東海道小田原宿の歴史・文化を紹介する無料施設。小田原城の城下町として栄えた宿場町の様子を映像・模型・資料で伝える。小田原駅から徒歩5分の立地で、城見学の前後に立ち寄りやすい。入館無料。",
        [I.odawara2],
        [
          { k: "最寄り駅", v: "小田原駅 徒歩5分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "◎" }]),
      s(4, "小田原漁港（早川港）", "漁港・海鮮グルメ", "早川",
        "地魚の直売と食堂が並ぶ漁港。アジ・金目鯛が名物",
        "相模湾に面した小田原の漁港。早川駅から徒歩5分で、地魚の直売・食堂・干物販売が集まる。アジフライ・地魚定食・干物の買い食いが楽しめる。早朝から昼頃まで鮮度が高く、昼食スポットとして訪れるのが最適。",
        [I.odawara2],
        [
          { k: "最寄り駅", v: "JR・小田急 早川駅 徒歩5分" },
          { k: "料金", v: "定食1,000〜2,000円程度" },
          { k: "おすすめ時間", v: "朝〜昼（11:00〜14:00）" }]),
      s(5, "小田原文学館・白秋童謡館", "文学館", "小田原",
        "北原白秋ゆかりの場所。洋館の建物と庭が美しい",
        "小田原ゆかりの文学者・北原白秋を中心に、尾崎一雄・三好達治ら小田原に関係した文人の資料を展示する文学館。大正時代の洋館建築を活用した施設で、建物自体も見どころ。小田原城の南側に位置し、城見学と組み合わせやすい。入館300円。",
        [I.odawara],
        [
          { k: "最寄り駅", v: "小田原駅 徒歩12分" },
          { k: "入館料", v: "300円" },
          { k: "雨の日", v: "◎" }])],
    sideArticles: [
      side("箱根湯本5選", "new-hakoneyumoto", I.yumoto),
      side("三浦海岸5選", "new-miura-kaigan", I.miura)],
    quote: "小田原は新幹線の停車駅でもあり、半日だけでも城・かまぼこ・漁港グルメを楽しめる。",
    quoteCite: author,
    closing: "小田原駅→なりわい交流館→小田原城→早川漁港で昼食→かまぼこの里（土産）という半日コースが効率的。箱根の帰りに組み合わせるのがおすすめ。",
  },

  // NG-25 ─────────────────────────────────────────────────
  "new-chigasaki-beach": {
    id: "new-chigasaki-beach",
    no: "NG-25", articleType: "guide", kicker: "CHIGASAKI BEACH",
    title: "茅ヶ崎ビーチ5選。湘南のサーファーズパラダイスを歩く",
    titleHTML: "茅ヶ崎<br>ビーチ5選。",
    subtitle: "サザンビーチ、ヘッドランド、海沿いカフェ。茅ヶ崎で感じる湘南の空気",
    lede: "茅ヶ崎はJRで東京から1時間圏内にある湘南の海の街。サザンオールスターズの地元として全国的に知られ、烏帽子岩を望む砂浜とサーファーの文化が街の空気をつくっている。",
    date, reading: "約4分", author,
    heroImage: I.chigasaki,
    ranking: [
      s(1, "サザンビーチちがさき", "海水浴場・砂浜", "茅ヶ崎",
        "茅ヶ崎駅から徒歩15分。サザンオールスターズの聖地",
        "茅ヶ崎の中心海岸。「サザンオールスターズ」の地元として知られ、夏は海水浴・サーフィン・BBQで賑わう。オフシーズン（秋〜春）は人が少なく、波の音と砂浜の散歩が楽しめる。烏帽子岩（茅ヶ崎のシンボル）が沖合に見える景色が特徴的。",
        [I.chigasaki],
        [
          { k: "最寄り駅", v: "JR茅ヶ崎駅 徒歩15分" },
          { k: "料金", v: "無料" },
          { k: "おすすめ時間", v: "夕方（サンセット）" }]),
      s(2, "ヘッドランド（突堤）", "サーフスポット・散策", "茅ヶ崎",
        "人工突堤からの眺め。波が割れるサーフスポットとして有名",
        "茅ヶ崎海岸に作られた人工突堤（ヘッドランド）は、突端まで歩いていくと360度の海景色が広がる。サーファーが波待ちする姿が見られ、湘南らしい風景を楽しめるスポット。釣り人も多く、波と海風を感じながら散歩するだけでも気分が変わる。",
        [I.chigasaki],
        [
          { k: "最寄り駅", v: "JR茅ヶ崎駅 徒歩20分" },
          { k: "料金", v: "無料" }]),
      s(3, "Tバー（チャーム茅ヶ崎）周辺カフェ群", "カフェ・ダイニング", "茅ヶ崎",
        "海岸通り沿いのサーファーズカフェ。茅ヶ崎らしい雰囲気",
        "茅ヶ崎の海岸線沿いには、サーファーズカフェ・ハワイアンダイニング・シーフードレストランが点在する。テラス席から海を眺めながら食事できる店も多く、湘南らしいリゾート感を味わえる。夕食をここで取ってから帰るのが定番の流れ。",
        [I.chigasaki],
        [
          { k: "最寄り駅", v: "JR茅ヶ崎駅 徒歩15〜20分" },
          { k: "料金", v: "ランチ1,000〜2,500円程度" }]),
      s(4, "旧相模川橋脚（国指定史跡）", "史跡", "茅ヶ崎",
        "鎌倉時代の橋の橋脚が地震で出現。屋外の国指定史跡",
        "1923年の関東大震災で地盤が隆起し、地中から現れた鎌倉時代（約800年前）の橋の橋脚。国の史跡に指定されており、現在は屋外に保存・展示されている。マニアックながらも「なぜここに」という驚きがある歴史スポット。茅ヶ崎駅から自転車か車でアクセスしやすい。",
        [I.chigasaki],
        [
          { k: "最寄り駅", v: "JR茅ヶ崎駅 徒歩30分 or 自転車15分" },
          { k: "料金", v: "無料" }]),
      s(5, "茅ヶ崎公園（里山の丘公園）", "自然公園", "茅ヶ崎",
        "茅ヶ崎の内陸にある森の公園。里山の自然を保全",
        "茅ヶ崎市北部に広がる里山型自然公園。雑木林・湿地・野草地が保全されており、都市に近い自然環境を気軽に楽しめる。ハイキングコースは整備されており、家族連れや犬の散歩にも使いやすい。海側の賑わいとは対照的な静かな茅ヶ崎を感じられる。",
        [I.chigasaki],
        [
          { k: "最寄り駅", v: "JR茅ヶ崎駅 バス15分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕" }])],
    sideArticles: [
      side("江ノ島夕暮れデート5選", "new-enoshima-evening-date", I.enoshima),
      side("藤沢で時間つぶし5選", "new-fujisawa-bored", I.enobch)],
    quote: "茅ヶ崎は湘南の海とサーファー文化が一体になった場所。海岸線を歩くだけで湘南気分になれる。",
    quoteCite: author,
    closing: "茅ヶ崎駅→サザンビーチ→ヘッドランド→海沿いカフェでランチ→夕景というルートが湘南1日プランの定番。サンセット時刻に合わせて到着すると烏帽子岩のシルエットが見られる。",
  },

  // NG-26 ─────────────────────────────────────────────────
  "new-fujisawa-bored": {
    id: "new-fujisawa-bored",
    no: "NG-26", articleType: "guide", kicker: "FUJISAWA TIME",
    title: "藤沢で時間つぶし5選。江ノ島・湘南の拠点駅でできること",
    titleHTML: "藤沢で<br>時間つぶし5選。",
    subtitle: "藤沢駅周辺・鵠沼海岸・江ノ島。江ノ電の出発点で時間が空いたときのプラン",
    lede: "藤沢はJR・小田急・江ノ電が交わる湘南の拠点駅。江ノ島まで江ノ電で20分、海岸まで徒歩圏内という位置にあり、時間が空いたときに「どこへでも行けてしまう」ことが最大の強み。",
    date, reading: "約4分", author,
    heroImage: I.enobch,
    ranking: [
      s(1, "藤沢駅周辺ショッピング（藤沢ルミネ・サンパール広場）", "ショッピング", "藤沢駅",
        "小田急・JR・江ノ電が集まる拠点駅のショッピング施設",
        "藤沢駅はJR東海道線・小田急・江ノ電が乗り入れる交通の要所。駅ビル「ルミネ藤沢」・「藤沢OPA」などショッピング施設が充実しており、電車待ちや移動前の時間つぶしに使いやすい。江ノ電出発前のカフェタイムにも最適。",
        [I.enobch],
        [
          { k: "最寄り駅", v: "藤沢駅 直結・徒歩1分" },
          { k: "営業時間", v: "10:00〜21:00" },
          { k: "雨の日", v: "◎" }]),
      s(2, "鵠沼海岸（辻堂〜片瀬）", "海岸・散策", "鵠沼海岸",
        "藤沢から自転車15分。湘南の広大な砂浜が続く",
        "藤沢駅から自転車か江ノ電で10〜15分。辻堂から片瀬江ノ島にかけて続く広大な砂浜。サーフィンのメッカとして知られ、海岸沿いには湘南系カフェ・レストランが点在する。江ノ島まで砂浜を歩けるルートもあり、晴れた日の散策に最適。",
        [I.enobch],
        [
          { k: "最寄り駅", v: "江ノ電 鵠沼海岸駅 徒歩5分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕" }]),
      s(3, "江ノ島（藤沢からのアクセス）", "観光島", "片瀬江ノ島",
        "藤沢から江ノ電で20分。島内の観光は2〜3時間",
        "藤沢駅から江ノ電で片瀬江ノ島駅へ約20分。江ノ島神社・シーキャンドル・岩屋洞窟を巡る観光が楽しめる。藤沢から日帰りで気軽に行けるため、「時間が空いたから江ノ島まで」という使い方をしやすい。島内は2〜3時間あれば主要スポットを回れる。",
        [I.enoshima],
        [
          { k: "最寄り駅", v: "江ノ電 片瀬江ノ島駅 （藤沢から20分）" },
          { k: "料金", v: "江ノ電片道260円（フリーパス推奨）" }]),
      s(4, "藤沢市民ギャラリー", "ギャラリー", "藤沢",
        "無料で入れる市民ギャラリー。企画展が定期開催",
        "藤沢駅近くの無料ギャラリー施設。地元作家の絵画・写真・工芸を紹介する企画展が定期的に開催されており、入場無料で気軽に立ち寄れる。雨の日の時間つぶしに向いており、駅から徒歩圏内でアクセスしやすい。",
        [I.enobch],
        [
          { k: "最寄り駅", v: "藤沢駅 徒歩5分" },
          { k: "料金", v: "無料（展示による）" },
          { k: "雨の日", v: "◎" }]),
      s(5, "藤沢本町・遊行寺", "寺院・散策", "藤沢本町",
        "時宗の総本山・清浄光寺（遊行寺）。銀杏の大木が有名",
        "時宗の総本山・清浄光寺（通称・遊行寺）。境内に樹齢700年以上とされる大銀杏があり、秋の黄葉は圧巻。藤沢本町駅から徒歩5分で、静かな参拝と境内散策が楽しめる。藤沢駅から1駅なので、江ノ島や海岸観光と組み合わせやすい。",
        [I.enobch],
        [
          { k: "最寄り駅", v: "小田急 藤沢本町駅 徒歩5分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "△" }])],
    sideArticles: [
      side("茅ヶ崎ビーチ5選", "new-chigasaki-beach", I.chigasaki),
      side("江ノ島夕暮れデート5選", "new-enoshima-evening-date", I.enoshima)],
    quote: "藤沢は江ノ電・江ノ島への玄関口。時間が空いたら江ノ島まで足を延ばすのが湘南の楽しみ方。",
    quoteCite: author,
    closing: "藤沢駅→江ノ電で鵠沼海岸→砂浜散歩→片瀬江ノ島→江ノ島観光という流れが湘南の王道ルート。帰りは藤沢駅から小田急で新宿へ直通できる。",
  },

  // NG-27 ─────────────────────────────────────────────────
  "new-yokosuka-dobuita": {
    id: "new-yokosuka-dobuita",
    no: "NG-27", articleType: "guide", kicker: "YOKOSUKA DOBUITA",
    title: "横須賀どぶ板通り5選。米軍基地の街で日本離れした体験を",
    titleHTML: "横須賀<br>どぶ板通り5選。",
    subtitle: "どぶ板通り、猿島、三笠公園。横須賀の独自文化とアメリカンな空気",
    lede: "横須賀は米海軍と海上自衛隊が拠点を置く港湾都市。どぶ板通りのアメリカンな商店街・戦艦三笠・無人島「猿島」と、日本の他の街にはない独自性がある。",
    date, reading: "約5分", author,
    heroImage: I.dobuita,
    ranking: [
      s(1, "どぶ板通り", "ショッピング・グルメ", "横須賀中央",
        "米海軍横須賀基地隣接の商店街。横須賀バーガー・タトゥー・米軍放出品",
        "米海軍横須賀基地の正門に隣接する歓楽街。アメリカンなバー・軍放出品店・タトゥーショップ・横須賀バーガーの専門店が軒を連ね、日本離れした独特の雰囲気が漂う。横須賀ネイビーバーガー（ブラックペッパーが効いた巨大バーガー）はここでしか食べられない名物。",
        [I.dobuita],
        [
          { k: "最寄り駅", v: "京急 汐入駅 徒歩3分" },
          { k: "料金", v: "バーガー1,500〜2,000円程度" }]),
      s(2, "猿島（東京湾唯一の無人島）", "島・史跡", "猿島",
        "横須賀港からフェリー10分。幕末の要塞跡が残る無人島",
        "東京湾に浮かぶ神奈川県唯一の無人島。横須賀港からフェリーで約10分でアクセスでき、幕末〜明治期に建設された砲台・弾薬庫・兵舎跡がほぼそのまま残る。映画・ドラマのロケ地としても知られる。BBQ・釣り・ハイキングも楽しめ、一日過ごせる。",
        [I.dobuita],
        [
          { k: "最寄り駅", v: "横須賀中央駅 徒歩15分（三笠桟橋から乗船）" },
          { k: "フェリー料金", v: "往復1,300円（別途入島料300円）" },
          { k: "雨の日", v: "✕（海況による）" }]),
      s(3, "三笠公園・戦艦三笠", "史跡・公園", "横須賀",
        "日本海海戦で活躍した戦艦三笠が保存展示。公園も広大",
        "日露戦争の日本海海戦（1905年）で旗艦として活躍した戦艦三笠が保存・公開されている公園。艦内に入って見学でき、東郷平八郎の指揮所も見られる。隣接する三笠公園は横須賀港を見渡す広大な公園で、散策・ベンチでのひと休みにも使いやすい。",
        [I.dobuita],
        [
          { k: "最寄り駅", v: "京急 横須賀中央駅 徒歩15分" },
          { k: "入場料", v: "500円（三笠艦内）" },
          { k: "雨の日", v: "○ 艦内は屋内" }]),
      s(4, "ヴェルニー公園（横須賀港ビュー）", "公園", "横須賀",
        "海上自衛隊・米海軍の艦船が見える港沿いの公園",
        "JR・京急横須賀駅のすぐそばにある公園。フェンス越しに海上自衛隊・米海軍の艦船が停泊しているのが見え、護衛艦ファンにとっては外せないスポット。バラ園が整備されており、春・秋のバラの季節は美しい。入園無料。",
        [I.dobuita],
        [
          { k: "最寄り駅", v: "JR横須賀駅 徒歩2分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "△（屋外）" }]),
      s(5, "横須賀美術館", "美術館", "観音崎",
        "相模湾を望む丘の上の美術館。建物と自然環境が一体",
        "三浦半島の観音崎に建つ海辺の美術館。海に向かって開けた立地で、晴れた日は展望デッキから相模湾の絶景が広がる。コレクション展に加え企画展も充実しており、雨の日でも半日楽しめる。横須賀中央駅からバスで約30分。",
        [I.dobuita],
        [
          { k: "最寄り駅", v: "横須賀中央駅 バス約30分" },
          { k: "入館料", v: "コレクション展：300円" },
          { k: "雨の日", v: "◎" }])],
    sideArticles: [
      side("三浦海岸5選", "new-miura-kaigan", I.miura),
      side("小田原観光5選", "new-odawara", I.odawara)],
    quote: "どぶ板通りのアメリカンな雰囲気と猿島の幕末遺跡は、横須賀でしか体験できない景色。",
    quoteCite: author,
    closing: "横須賀中央駅→どぶ板通り（ランチ）→三笠公園・戦艦三笠→ヴェルニー公園（護衛艦ウォッチ）→猿島フェリー（晴れの日のみ）という一日コース。横須賀の特別な空気感は都内にはない。",
  },

  // NG-28 ─────────────────────────────────────────────────
  "new-miura-kaigan": {
    id: "new-miura-kaigan",
    no: "NG-28", articleType: "guide", kicker: "MIURA KAIGAN",
    title: "三浦海岸5選。東京から最も近い本格的な海でできること",
    titleHTML: "三浦海岸<br>5選。",
    subtitle: "三浦海岸、城ヶ島、三崎港のマグロ。三浦半島の先端まで行く価値",
    lede: "三浦海岸は京急で品川から約70分。都内からアクセスできる海の中では透明度が高く、冬には河津桜と菜の花の共演でも知られる。マグロの三崎港・城ヶ島も同じ半島内に揃い、一日コースが組みやすい。",
    date, reading: "約5分", author,
    heroImage: I.miura,
    ranking: [
      s(1, "三浦海岸", "海水浴場", "三浦海岸",
        "京急で都内から約70分。透明度の高い砂浜と水平線",
        "京急三浦海岸駅から徒歩5分でアクセスできる砂浜。砂浜の長さは約1kmで、夏は海水浴・バーベキューで賑わう。冬〜春は菜の花畑が広がる「三浦海岸桜まつり」（1月〜2月）が有名で、河津桜と菜の花のコントラストが楽しめる。",
        [I.miura],
        [
          { k: "最寄り駅", v: "京急 三浦海岸駅 徒歩5分" },
          { k: "料金", v: "無料" },
          { k: "おすすめ時間", v: "晴天時、午前〜夕方" }]),
      s(2, "城ヶ島", "離島・自然", "三浦市城ヶ島",
        "三浦半島南端の小島。断崖と磯が続く自然景観",
        "三浦半島南端に浮かぶ神奈川県最大の離島。橋で本土とつながっており、断崖・岩礁・磯が続く荒々しい自然景観が魅力。城ヶ島灯台・馬の背洞門（波食洞穴）などの見どころがある。三崎港からバスで10分程度。磯遊び・ハイキングに向いている。",
        [I.miura2],
        [
          { k: "最寄り駅", v: "三崎口駅 バス25分" },
          { k: "料金", v: "無料（公園内）" },
          { k: "雨の日", v: "✕ 屋外" }]),
      s(3, "三崎港・まぐろの食堂街", "海鮮グルメ", "三崎港",
        "マグロの水揚げ量で知られる漁港。地魚・まぐろ定食",
        "全国有数のマグロ水揚げ漁港。港周辺にはマグロを使った丼・定食・寿司を提供する食堂・飲食店が多数並んでいる。「まぐろの漬け丼」「赤身・大トロ定食」などが名物で、価格帯は1,000〜2,500円程度。三崎口駅からバスで20分。",
        [I.miura2],
        [
          { k: "最寄り駅", v: "三崎口駅 バス20分" },
          { k: "料金", v: "まぐろ定食1,500〜2,500円" },
          { k: "おすすめ時間", v: "ランチ（11:00〜14:00）" }]),
      s(4, "剱崎（けんざき）灯台", "灯台・自然", "三浦市剱崎",
        "三浦半島東岸の灯台。東京湾入口を見渡す展望地",
        "三浦半島の東岸に立つ白い灯台。東京湾の入口に位置し、大型船が行き交う海の景色が広がる。磯釣りのポイントとしても知られ、周囲は手つかずの磯が続く。三崎口駅から車またはバスでアクセス。灯台自体の一般公開は限定的だが、周辺の絶景は自由に楽しめる。",
        [I.miura],
        [
          { k: "最寄り駅", v: "三崎口駅 バス・タクシー15分" },
          { k: "料金", v: "無料" }]),
      s(5, "三浦海岸 河津桜まつり（1〜2月）", "季節イベント", "三浦海岸",
        "日本一早咲きの河津桜と菜の花。1月下旬〜2月末が見頃",
        "三浦海岸駅〜小松ヶ池公園にかけて約1kmにわたって河津桜が咲く冬の名所。早咲きの河津桜と黄色い菜の花のコントラストが美しく、2月のシーズンには多くの観光客が訪れる。駅から徒歩すぐでアクセスも良く、日帰りで十分楽しめる。",
        [I.miura],
        [
          { k: "最寄り駅", v: "京急 三浦海岸駅 徒歩1分" },
          { k: "期間", v: "1月下旬〜2月末頃（年により変動）" },
          { k: "料金", v: "無料" }])],
    sideArticles: [
      side("横須賀どぶ板5選", "new-yokosuka-dobuita", I.dobuita),
      side("茅ヶ崎ビーチ5選", "new-chigasaki-beach", I.chigasaki)],
    quote: "三浦海岸は「東京から一番近い本格的な海」として、日帰りで海気分を味わいたいときの定番。",
    quoteCite: author,
    closing: "三浦海岸駅→砂浜散歩→バスで三崎港→マグロ昼食→城ヶ島（自然散策）というルートが三浦半島一日プランの定番。冬に訪れるなら河津桜まつりの季節が最もおすすめ。",
  },

  // NG-29 ─────────────────────────────────────────────────
  "new-kohoku-nt-family": {
    id: "new-kohoku-nt-family",
    no: "NG-29", articleType: "guide", kicker: "KOHOKU NT FAMILY",
    title: "港北ニュータウン・ファミリースポット5選。センター北・南の子連れ定番",
    titleHTML: "港北NT<br>ファミリー5選。",
    subtitle: "モザイクモール、都筑区ふるさと公園、大塚・歳勝土遺跡公園。計画都市の緑と施設",
    lede: "横浜市都筑区の港北ニュータウンは計画的に整備された都市で、公園・緑道・商業施設のバランスが取れている。センター北・南を軸に弥生時代の遺跡公園や歴史博物館まであり、子連れの半日コースが組みやすい。",
    date, reading: "約4分", author,
    heroImage: I.kohoku,
    ranking: [
      s(1, "モザイクモール港北", "ショッピングモール", "センター北",
        "センター北駅直結の大型モール。子ども向け施設・映画館完備",
        "市営地下鉄センター北駅直結の大型商業施設。子ども服・ベビー用品・飲食フロア・映画館が一棟に入り、ファミリーの週末スポットとして定着している。屋外の広場スペースでは定期的にイベントも開催。雨の日も屋内で一日過ごせる。",
        [I.kohoku],
        [
          { k: "最寄り駅", v: "市営地下鉄 センター北駅 直結" },
          { k: "営業時間", v: "10:00〜21:00" },
          { k: "雨の日", v: "◎" }]),
      s(2, "都筑区ふるさと公園", "自然公園", "都筑区",
        "港北ニュータウン内の自然保全区。緑道が続く散歩コース",
        "港北ニュータウン開発の際に保全された里山・緑地が連続する公園群の一つ。緑道で複数の公園がつながっており、ベビーカーでも歩きやすい整備が施されている。センター南・センター北エリアから歩いてアクセスでき、都市の中で自然を感じられる。",
        [I.kohoku],
        [
          { k: "最寄り駅", v: "市営地下鉄 センター南駅 徒歩10分" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕" }]),
      s(3, "大塚・歳勝土遺跡公園（弥生の丘展示館）", "史跡・公園", "都筑区",
        "弥生時代の集落跡が復元展示。子どもが古代生活を学べる",
        "弥生時代の環濠集落跡を復元した公園。竪穴式住居・高床倉庫が実物大で再現されており、子どもが古代の生活を体感できる。隣接する「弥生の丘展示館」（無料）では出土品・歴史資料を展示。センター北駅から徒歩10分程度。",
        [I.kohoku],
        [
          { k: "最寄り駅", v: "市営地下鉄 センター北駅 徒歩10分" },
          { k: "料金", v: "公園無料（展示館無料）" },
          { k: "雨の日", v: "△（展示館は可）" }]),
      s(4, "港北ニュータウン緑道（牛久保緑道ほか）", "緑道・散策", "港北区〜都筑区",
        "市営地下鉄沿線に続く緑道。ベビーカーでも歩ける遊歩道",
        "港北ニュータウン一帯を縦横に走る緑道ネットワーク。センター南〜センター北〜仲町台にかけて整備された緑道は、植栽が豊かで季節ごとに景観が変わる。ウォーキング・ジョギング・ベビーカー散歩に使いやすく、地元ファミリーの日常の場となっている。",
        [I.kohoku],
        [
          { k: "最寄り駅", v: "センター北・南・仲町台駅 周辺" },
          { k: "料金", v: "無料" },
          { k: "雨の日", v: "✕" }]),
      s(5, "横浜市歴史博物館", "博物館", "センター北",
        "港北ニュータウンに建つ横浜市の総合歴史博物館",
        "大塚・歳勝土遺跡公園に隣接する横浜市の歴史博物館。原始〜近現代にかけての横浜の歴史を体系的に展示する。企画展も充実しており、常設展と合わせると2〜3時間楽しめる。遺跡公園と合わせて訪れると、弥生時代の歴史が立体的に理解できる。入館300円。",
        [I.kohoku],
        [
          { k: "最寄り駅", v: "市営地下鉄 センター北駅 徒歩10分" },
          { k: "入館料", v: "300円" },
          { k: "雨の日", v: "◎" }])],
    sideArticles: [
      side("たまプラーザ・あざみ野5選", "new-tamaplaza-azamino", I.mm_blue),
      side("武蔵小杉ファミリー5選", "new-musashikosugi-family", I.lazona)],
    quote: "港北ニュータウンは計画都市らしく、公園・緑道・商業施設のバランスが取れたファミリーエリア。",
    quoteCite: author,
    closing: "センター北駅→弥生の丘展示館（無料）→大塚・歳勝土遺跡公園→モザイクモールでランチ→緑道散歩という半日コース。雨の日はモザイクモール一択で一日過ごせる。",
  },

  // NG-30 ─────────────────────────────────────────────────
  "new-yokohama-first-date": {
    id: "new-yokohama-first-date",
    no: "NG-30", articleType: "guide", kicker: "YOKOHAMA FIRST DATE",
    title: "横浜初デート5選。初めての相手を連れて行くなら絶対外さない場所",
    titleHTML: "横浜<br>初デート5選。",
    subtitle: "みなとみらい、山下公園、中華街。横浜の「定番」がなぜ定番なのか",
    lede: "横浜の定番コースは「外れない」だけでなく、5ヶ所が一本の動線でつながるという設計の良さがある。みなとみらいから始めて中華街で締めるルートは、初デートの会話が途切れても景色が補ってくれる。",
    date, reading: "約5分", author,
    heroImage: I.mm_blue,
    ranking: [
      s(1, "みなとみらい・ランドマークタワー〜スカイガーデン", "展望台・港", "みなとみらい",
        "初デートに外れなし。展望台→汽車道→赤レンガという王道ルート",
        "横浜初デートの定番スタート地点。ランドマークタワー69Fのスカイガーデンから横浜の全景を俯瞰してから、汽車道→赤レンガ倉庫へと歩くルートは3〜4時間で自然に流れる。会話が途切れても景色が補ってくれるため、初めての相手と歩くのに向いている。",
        [I.mm_blue],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩3分" },
          { k: "スカイガーデン入場料", v: "大人1,000円" },
          { k: "おすすめ時間", v: "夕方〜夜景" }]),
      s(2, "赤レンガ倉庫", "複合施設・散策", "みなとみらい",
        "明治の倉庫をリノベした定番スポット。港の景色と一緒に",
        "1911〜1913年建造の歴史的倉庫を活用した商業施設。内部のショップ・カフェを楽しみつつ、屋外デッキから横浜港・大さん橋・ベイブリッジを眺められる。みなとみらいの中でも「写真映え」する場所として知られ、初デートでの撮影スポットとしても定番。",
        [I.akarenga],
        [
          { k: "最寄り駅", v: "馬車道駅 徒歩6分 / みなとみらい駅 徒歩12分" },
          { k: "料金", v: "無料（飲食・ショッピング別途）" }]),
      s(3, "山下公園・大さん橋", "公園・展望", "山下町",
        "港の見える公園と客船ターミナル。横浜らしい景色の核心",
        "横浜を代表する海沿い公園。元町・中華街駅から徒歩5分で、園内からは大さん橋に停泊する大型客船・ベイブリッジ・みなとみらいのスカイラインが一望できる。大さん橋の屋上デッキは開放的な芝生広場で、海風を感じながらのんびり過ごせる。",
        [I.yamashita],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩5分" },
          { k: "料金", v: "無料" },
          { k: "おすすめ時間", v: "夕方〜夜景" }]),
      s(4, "横浜中華街", "グルメ・観光", "中華街",
        "初デートの夕食は中華街で決まり。日本最大の中華街",
        "日本最大・アジア最大規模の中華街。山下公園から徒歩5分で、関帝廟・横濱媽祖廟といった廟の参拝から食べ歩き・コース料理まで幅広い楽しみ方ができる。初デートの夕食場所として使いやすく、食の選択肢が多いため好みに合わせやすい。",
        [I.chinatown],
        [
          { k: "最寄り駅", v: "元町・中華街駅 徒歩2分" },
          { k: "料金", v: "食べ歩き200円〜 / コース料理3,000〜8,000円" }]),
      s(5, "コスモクロック21（夜景）", "観覧車・夜景", "みなとみらい",
        "デートの締めはコスモクロック。横浜港の夜景と一緒に",
        "高さ112.5mの大観覧車。一周約15分で横浜港の夜景を楽しめる。みなとみらいの夜景の象徴として定着しており、初デートの「締め」として使いやすい。ゴンドラは半密室になるため、2人の時間を自然に作れる。料金は訪問前に公式サイトでご確認ください。",
        [I.cosmo],
        [
          { k: "最寄り駅", v: "みなとみらい駅 徒歩5分" },
          { k: "料金", v: "900円" },
          { k: "おすすめ時間", v: "夜（20:00〜）" }])],
    sideArticles: [
      side("みなとみらいデート5選", "new-minatomirai-date", I.mm_blue),
      side("山下公園デート5選", "new-yamashita-date", I.yamashita)],
    quote: "横浜の「定番」は、なぜ定番かを分かっている人だけが連れて行ける場所。初めての相手に横浜を案内するなら、この5ヶ所で外れはない。",
    quoteCite: author,
    closing: "みなとみらい（展望台・汽車道）→赤レンガ（散策・カフェ）→山下公園・大さん橋（夕景）→中華街（夕食）→コスモクロック（夜景）という全5スポットが1本の動線でつながる。横浜初デートの完全版コース。",
  },
};
