/**
 * サイト内検索のための読み仮名（ひらがな）。**固定の語だけ**に持つ: 都道府県・業種・種類（業態）。
 * 駅・店・市区町村の読みはデータに無いので持たない（推測で作らない）。
 * 検索側でカタカナはひらがなにそろえるので、ここはどちらで書いてもよい。
 */

/** 都道府県 slug → [正式名の読み, 短い名前の読み] */
export const PREF_KANA: Record<string, [string, string]> = {
  hokkaido: ["ほっかいどう", "ほっかいどう"],
  aomori: ["あおもりけん", "あおもり"],
  iwate: ["いわてけん", "いわて"],
  miyagi: ["みやぎけん", "みやぎ"],
  akita: ["あきたけん", "あきた"],
  yamagata: ["やまがたけん", "やまがた"],
  fukushima: ["ふくしまけん", "ふくしま"],
  ibaraki: ["いばらきけん", "いばらき"],
  tochigi: ["とちぎけん", "とちぎ"],
  gunma: ["ぐんまけん", "ぐんま"],
  saitama: ["さいたまけん", "さいたま"],
  chiba: ["ちばけん", "ちば"],
  tokyo: ["とうきょうと", "とうきょう"],
  kanagawa: ["かながわけん", "かながわ"],
  niigata: ["にいがたけん", "にいがた"],
  toyama: ["とやまけん", "とやま"],
  ishikawa: ["いしかわけん", "いしかわ"],
  fukui: ["ふくいけん", "ふくい"],
  yamanashi: ["やまなしけん", "やまなし"],
  nagano: ["ながのけん", "ながの"],
  gifu: ["ぎふけん", "ぎふ"],
  shizuoka: ["しずおかけん", "しずおか"],
  aichi: ["あいちけん", "あいち"],
  mie: ["みえけん", "みえ"],
  shiga: ["しがけん", "しが"],
  kyoto: ["きょうとふ", "きょうと"],
  osaka: ["おおさかふ", "おおさか"],
  hyogo: ["ひょうごけん", "ひょうご"],
  nara: ["ならけん", "なら"],
  wakayama: ["わかやまけん", "わかやま"],
  tottori: ["とっとりけん", "とっとり"],
  shimane: ["しまねけん", "しまね"],
  okayama: ["おかやまけん", "おかやま"],
  hiroshima: ["ひろしまけん", "ひろしま"],
  yamaguchi: ["やまぐちけん", "やまぐち"],
  tokushima: ["とくしまけん", "とくしま"],
  kagawa: ["かがわけん", "かがわ"],
  ehime: ["えひめけん", "えひめ"],
  kochi: ["こうちけん", "こうち"],
  fukuoka: ["ふくおかけん", "ふくおか"],
  saga: ["さがけん", "さが"],
  nagasaki: ["ながさきけん", "ながさき"],
  kumamoto: ["くまもとけん", "くまもと"],
  oita: ["おおいたけん", "おおいた"],
  miyazaki: ["みやざきけん", "みやざき"],
  kagoshima: ["かごしまけん", "かごしま"],
  okinawa: ["おきなわけん", "おきなわ"],
};

/** 業種 key → 読み */
export const VERTICAL_KANA: Record<string, string> = {
  gourmet: "ぐるめ",
  beauty: "びゅーてぃー",
  bodycare: "ぼでぃけあ",
  pet: "ぺっと",
  leisure: "おでかけ",
  stay: "すてい",
};

/** 新業種の種類（`${業種key}/${slug}`）→ 読み（複数あれば「|」区切り） */
export const CATEGORY_KANA: Record<string, string> = {
  "beauty/hair": "びようしつ|へあさろん",
  "beauty/nail": "ねいる",
  "beauty/eyelash": "まつげ|まゆ",
  "beauty/esthetic": "えすて",
  "beauty/hair-removal": "だつもう",
  "beauty/headspa": "へっどすぱ",
  "bodycare/seitai": "せいたい",
  "bodycare/sekkotsu": "せいこついん|せっこついん",
  "bodycare/shinkyu": "しんきゅう|しんきゅういん|はりきゅう",
  "bodycare/massage": "まっさーじ",
  "bodycare/relaxation": "りらくぜーしょん",
  "bodycare/stretch": "すとれっち",
  "pet/trimming": "とりみんぐ",
  "pet/pet-hotel": "ぺっとほてる",
  "pet/vet": "どうぶつびょういん",
  "pet/dog-cafe": "どっぐかふぇ",
  "pet/dog-run": "どっぐらん",
  "pet/pet-shop": "ぺっとしょっぷ",
  "leisure/sightseeing": "かんこう|かんこうすぽっと",
  "leisure/experience": "たいけん|あくてぃびてぃ",
  "leisure/onsen": "おんせん|ひがえりおんせん|すぱ",
  "leisure/park": "てーまぱーく|こうえん",
  "leisure/outdoor": "あうとどあ",
  "leisure/museum": "びじゅつかん|はくぶつかん",
  "stay/hotel": "ほてる",
  "stay/ryokan": "りょかん",
  "stay/pension": "みんしゅく|ぺんしょん",
  "stay/glamping": "ぐらんぴんぐ|きゃんぷ",
  "stay/guesthouse": "げすとはうす",
};

/** グルメの業態（lib/cuisineGroups.ts の label）→ 読み */
export const CUISINE_KANA: Record<string, string> = {
  居酒屋: "いざかや",
  焼き鳥: "やきとり",
  焼肉: "やきにく|ほるもん",
  "和食・割烹": "わしょく|かっぽう",
  "寿司・海鮮": "すし|かいせん",
  ラーメン: "らーめん",
  "そば・うどん": "そば|うどん",
  中華: "ちゅうか",
  イタリアン: "いたりあん|ぱすた|ぴざ",
  フレンチ: "ふれんち|びすとろ",
  "カフェ・喫茶": "かふぇ|きっさ|こーひー",
  "定食・洋食": "ていしょく|ようしょく",
  お好み焼き: "おこのみやき|てっぱんやき",
  "バー・バル": "ばー|ばる",
};
